# Yarn berry
# Path where the downloaded packages are stored on your system.
cacheFolder: ./.yarn/cache
#Define whether the cache should be shared between all local projects.
enableGlobalCache: false
# Disable lifecycle scripts to protect against malicious packages locally
enableScripts: false
# Amount of time to wait before cancelling pending HTTP requests.
httpTimeout: 5m
# Description: The linker used for installing Node packages, one of: "pnp", "pnpm", or "node-modules"
nodeLinker: node-modules
# Minimum age of a package version according to the published date on the npm registry to be considered for installation
npmMinimalAgeGate: 7d # Temporarily set to a shorter window than the internal recommendation still better than no gate
