# Generated by Django 2.2.10 on 2020-03-30 11:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("helusers", "0001_add_ad_groups"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(name="user", options={"ordering": ("id",)},),
        migrations.AddField(
            model_name="user",
            name="ad_groups",
            field=models.ManyToManyField(blank=True, to="helusers.ADGroup"),
        ),
        migrations.AddField(
            model_name="user",
            name="department_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
