# Generated by Django 2.2.12 on 2020-05-29 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_add_helusers_migration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user", name="uuid", field=models.UUIDField(unique=True),
        ),
    ]
