# Generated by Django 2.2.17 on 2020-12-16 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_bypass_operational_area_for_existing_users"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "User", "verbose_name_plural": "Users"},
        ),
        migrations.AlterField(
            model_name="user",
            name="operational_areas",
            field=models.ManyToManyField(
                blank=True,
                related_name="users",
                to="traffic_control.OperationalArea",
                verbose_name="Operational areas",
            ),
        ),
    ]
