# Generated by Django 3.2.13 on 2022-06-13 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_control', '0051_help_texts'),
        ('users', '0007_move_responsible_entity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='operational_areas',
            field=models.ManyToManyField(blank=True, help_text='Operational areas, on which this user has permission to modify devices in.', related_name='users', to='traffic_control.OperationalArea', verbose_name='Operational areas'),
        ),
    ]
