# Generated by Django 4.2.26 on 2025-11-19 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_additional_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_api_use',
            field=models.DateField(blank=True, null=True, verbose_name='Latest API token usage date'),
        ),
    ]
