# Generated by Django 5.2.8 on 2026-02-24 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_last_api_use'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDeactivationStatus',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='deactivation_status', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('one_month_email_sent_at', models.DateTimeField(blank=True, help_text='Timestamp when the 30-day warning email was sent.', null=True, verbose_name='One month warning email sent at')),
                ('one_week_email_sent_at', models.DateTimeField(blank=True, help_text='Timestamp when the 7-day warning email was sent.', null=True, verbose_name='One week warning email sent at')),
                ('one_day_email_sent_at', models.DateTimeField(blank=True, help_text='Timestamp when the 1-day warning email was sent.', null=True, verbose_name='One day warning email sent at')),
                ('deactivated_at', models.DateTimeField(blank=True, help_text='Timestamp when the user was deactivated.', null=True, verbose_name='Deactivated at')),
            ],
            options={
                'verbose_name': 'User Deactivation Status',
                'verbose_name_plural': 'User Deactivation Statuses',
                'db_table': 'user_deactivation_status',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='reactivated_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when admin manually reactivated this user account. Prevents automatic deactivation.', null=True, verbose_name='Reactivated at'),
        ),
    ]
