# Generated by Django 5.2.8 on 2026-02-26 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_userdeactivationstatus_user_reactivated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='receives_admin_notification_emails',
            field=models.BooleanField(default=False, help_text='If enabled, this user will receive admin notification emails about user deactivations and system events. Only users with valid email addresses will receive notifications.', verbose_name='Receives admin notification emails'),
        ),
    ]
