version: 2
updates:
  # Python / Poetry dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    # Disable version updates and only allow security updates
    open-pull-requests-limit: 0

  # JavaScript / Yarn dependencies
  - package-ecosystem: "npm"
    directory: "/map-view"
    schedule:
      interval: "daily"
    # Disable version updates and only allow security updates
    open-pull-requests-limit: 0
