# Generated by Django 5.2.9 on 2026-01-16 16:32

import enumfields.fields
import site_alert.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='When enabled, display this message to users in the admin pages.', verbose_name='Message active')),
                ('level', enumfields.fields.EnumIntegerField(default=0, enum=site_alert.models.SiteAlertLevel, help_text='Select a style of warning to reflect how critical it is', verbose_name='Alert level')),
                ('message_en', models.TextField(help_text='English message', verbose_name='Message (English)')),
                ('message_fi', models.TextField(help_text='Finnish message', verbose_name='Message (Finnish)')),
                ('message_sv', models.TextField(help_text='Swedish message', verbose_name='Message (Swedish)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
        ),
    ]
