# Generated by Django 5.2.9 on 2026-01-20 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_alert', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitealert',
            name='message_fi',
            field=models.TextField(blank=True, help_text='Finnish message', verbose_name='Message (Finnish)'),
        ),
        migrations.AlterField(
            model_name='sitealert',
            name='message_sv',
            field=models.TextField(blank=True, help_text='Swedish message', verbose_name='Message (Swedish)'),
        ),
    ]
