# Generated by Django 5.2.9 on 2026-01-20 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_alert', '0002_alter_sitealert_message_fi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitealert',
            name='end_at',
            field=models.DateTimeField(blank=True, help_text='(Optional) When to stop showing this alert. Leave blank to show indefinitely.', null=True, verbose_name='End time'),
        ),
        migrations.AddField(
            model_name='sitealert',
            name='start_at',
            field=models.DateTimeField(blank=True, help_text='(Optional) When to start showing this alert. Leave blank to show immediately.', null=True, verbose_name='Start time'),
        ),
    ]
