# Generated by Django 5.2.8 on 2026-01-20 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_alert', '0003_sitealert_end_at_sitealert_start_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitealert',
            options={'verbose_name': 'Site Alert', 'verbose_name_plural': 'Site Alerts'},
        ),
    ]
