sudo: false
language: python

cache:
  directories:
    - "$HOME/.cache/pip"
env:
  global:
    - DEBUG=1

python: 3.7
install:
  - pip install -U pip
  - pip install -r requirements.txt -r requirements-dev.txt

script:
  - flake8
  #- py.test -ra -vvv --cov
  - isort -rc
