dist: bionic

env:
  global:
    - DEBUG=1
    - OIDC_AUTHENTICATION_ENABLED=0

services:
  - postgresql

addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10-postgis-2.5
      - postgresql-10-postgis-2.5-scripts

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt

before_script:
  - psql -U postgres template1 -c 'create extension postgis;'
  - psql -U postgres -c 'create database "city-infrastructure-platform";'

script:
  - flake8
  - black --check .
  - isort . -c
  - pytest -ra -vvv --cov=.

after_success:
  - curl -s https://codecov.io/bash | bash

cache: pip

matrix:
  include:
    - language: python
      python:
        - 3.6

    - language: python
      python:
        - 3.7

    - language: python
      python:
        - 3.8

    - language: node_js
      node_js:
        - 12.18
      before_install:
        - cd map-view
      install:
        - yarn install
      script:
        - yarn test
      cache:
        bundler: true
        directories:
          - map-view/node_modules
