dist: bionic

language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

cache: pip

services:
   - postgresql

addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10-postgis-2.5
      - postgresql-10-postgis-2.5-scripts

env:
  global:
    - DEBUG=1
    - OIDC_AUTHENTICATION_ENABLED=0

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt

before_script:
  - psql -U postgres template1 -c 'create extension postgis;'
  - psql -U postgres -c 'create database "city-infrastructure-platform";'

script:
  - flake8
  - black --check .
  - isort -c
  - pytest -ra -vvv --cov=.

after_success:
  - curl -s https://codecov.io/bash | bash
