[project]
name = "city-infrastructure-platform"
version = "1.45.0"
description = ""
authors = []
requires-python = ">=3.12,<4"
dependencies = [
    "django~=5.2",
    "cairosvg",
    "django-auditlog",
    "django-colorfield",
    "django-cors-headers",
    "django-enumfields2",
    "django-environ",
    "django-extensions",
    "django-filter",
    "django-gisserver",
    "django-health-check",
    "django-helusers",
    "django-import-export",
    "django-mptt",
    "django-storages[azure]",
    "djangorestframework",
    "djangorestframework-gis",
    "docutils",
    "drf-nested-routers",
    "drf-oidc-auth",
    "drf-spectacular",
    "jsonschema",
    "psycopg2~=2.9",
    "python-dateutil",
    "pytz",
    "requests",
    "rsa",
    "sentry-sdk",
    "social-auth-app-django",
    "uWSGI",
    "django-advanced-password-validation",
    "django-axes",
    "django-admin-confirm",
    "django-guardian",
    "django-admin-rangefilter",
]

[dependency-groups]
dev = [
    "bump2version",
    "coverage",
    "django-debug-toolbar",
    "djlint",
    "factory-boy",
    "ipython",
    "jedi",
    "pyobjc-core; sys_platform == 'darwin'",
    "pyobjc-framework-Cocoa; sys_platform == 'darwin'",
    "pyobjc-framework-FSEvents; sys_platform == 'darwin'",
    "pytest",
    "pytest-cov",
    "pytest-django",
    "pytest-watch",
    "rope",
    "ruff",
    "requests-mock",
    "django-zeal",
]

[tool.uv]
default-groups = "all"
exclude-newer = "P7D"
package = false

[tool.ruff]
extend-select = [
    "F",   # pyflakes
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "C90", # mccabe
    "I",   # isort
]
extend-exclude = ["migrations"]
line-length = 120
target-version = "py312"

[tool.ruff.extend-per-file-ignores]
"__init__.py" = ["F401"]

[tool.ruff.mccabe]
max-complexity = 10

[tool.ruff.lint.isort]
combine-as-imports = true
order-by-type = false


[tool.djlint]
# T003: Endblock should have name
# H023: Entity references must end with a semicolon
# H030: Consider adding meta tag to viewport
# H031: Consider adding meta tag to cache-control
# H021: Inline styles should be avoided - necessary for email client compatibility
ignore = "T003,H023,H030,H031,H021"
use_gitignore = true
extend_exclude = "map-view"
profile = "django"
max_line_length = 120
max_blank_lines = 1
max_attribute_length = 20
close_void_tags = true


[tool.pydocstyle]
match_dir = '[^\.,venv,.venv,migrations].*'
ignore = ["D100", "D104", "D105", "D200", "D203", "D400"]


[tool.pytest.ini_options]
norecursedirs = ["node_modules", ".git", "venv", ".venv"]
DJANGO_SETTINGS_MODULE = "cityinfra.settings"
doctest_optionflags = [
    "NORMALIZE_WHITESPACE",
    "IGNORE_EXCEPTION_DETAIL",
    "ALLOW_UNICODE",
]
filterwarnings = [
    "ignore:The FORMS_URLFIELD_ASSUME_HTTPS transitional setting is deprecated.:django.utils.deprecation.RemovedInDjango60Warning",
]


[tool.coverage.run]
branch = true
omit = ["*/migrations/*", "venv/*", ".venv/*", "*/tests/*", "test_*.py"]
