# Generated by Django 2.2.14 on 2020-08-21 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Layer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identifier",
                    models.CharField(max_length=200, verbose_name="identifier"),
                ),
                (
                    "name_fi",
                    models.CharField(max_length=200, verbose_name="Finnish name"),
                ),
                (
                    "name_en",
                    models.CharField(max_length=200, verbose_name="English name"),
                ),
                (
                    "is_basemap",
                    models.BooleanField(default=False, verbose_name="is basemap"),
                ),
                ("order", models.IntegerField(default=1, verbose_name="order")),
            ],
            options={
                "verbose_name": "layer",
                "verbose_name_plural": "layers",
                "ordering": ("is_basemap", "order"),
            },
        ),
    ]
