# Generated by Django 2.2.27 on 2022-03-10 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_unify_field_verbose_name_cases'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='app_name',
            field=models.CharField(default='traffic_control', max_length=200, verbose_name='App Name'),
        ),
    ]
