# Generated by Django 3.2.12 on 2022-04-07 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_add_app_name_to_map_layer'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='filter_fields',
            field=models.CharField(blank=True, max_length=200, verbose_name='Filter fields'),
        ),
    ]
