# Generated by Django 3.2.12 on 2022-04-07 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_add_filter_fields_to_layer'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='use_traffic_sign_icons',
            field=models.BooleanField(default=False, verbose_name='Use Traffic Sign Icons'),
        ),
    ]
