# Generated by Django 4.2.20 on 2025-04-22 09:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_add_use_traffic_sign_icons_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureTypeEditMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(help_text='Name of feature type', max_length=200, unique=True, verbose_name='Name')),
                ('edit_name', models.CharField(help_text='Edit name, used in map-view FeatureInfo component edit link', max_length=200)),
            ],
        ),
    ]
