# Generated by Django 4.2.20 on 2025-04-25 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_featuretypeeditmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='clustered',
            field=models.BooleanField(default=True, verbose_name='Clustered'),
        ),
    ]
