# Generated by Django 4.2.20 on 2025-05-19 09:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_layer_clustered'),
    ]

    operations = [
        migrations.CreateModel(
            name='IconDrawingConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Name')),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
                ('image_type', models.CharField(choices=[('png', 'png'), ('svg', 'svg')], max_length=10, verbose_name='Image Type')),
                ('png_size', models.IntegerField(choices=[(32, 'Small'), (64, 'Medium'), (128, 'Large'), (256, 'Extra Large')], verbose_name='PNG Size')),
                ('scale', models.FloatField(default=None, null=True, verbose_name='Scale')),
            ],
        ),
    ]
