# Generated by Django 4.2.20 on 2025-05-20 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0008_icondrawingconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='name_sv',
            field=models.CharField(default='Missing SW translation', max_length=200, verbose_name='Swedish name'),
        ),
    ]
