# Generated by Django 4.2.20 on 2025-06-02 13:27

from django.db import migrations, models
import map.validators


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0009_layer_name_sv'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='extra_feature_info',
            field=models.JSONField(blank=True, help_text='Fields added here need to be included in the corresponding WFS Feature', null=True, validators=[map.validators.validate_layer_extra_feature_info], verbose_name='Extra Feature Info'),
        ),
    ]
