# Generated by Django 4.2.20 on 2025-06-09 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0010_layer_extra_feature_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='icondrawingconfig',
            name='active',
        ),
        migrations.AddField(
            model_name='icondrawingconfig',
            name='enabled',
            field=models.BooleanField(default=False, verbose_name='Enabled'),
        ),
    ]
