# Generated by Django 4.2.20 on 2025-06-10 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0011_remove_icondrawingconfig_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='icondrawingconfig',
            options={'verbose_name': 'IconDrawingConfig', 'verbose_name_plural': 'IconDrawingConfigs'},
        ),
        migrations.AddConstraint(
            model_name='icondrawingconfig',
            constraint=models.UniqueConstraint(fields=('image_type', 'png_size'), name='map_icondrawingconfig_unique_image_type_png_size'),
        ),
        migrations.AddConstraint(
            model_name='icondrawingconfig',
            constraint=models.UniqueConstraint(condition=models.Q(('enabled', True)), fields=('enabled',), name='map_icondrawingconfig_unique_enabled'),
        ),
    ]
