# Generated by Django 5.2.8 on 2026-01-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0012_alter_icondrawingconfig_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featuretypeeditmapping',
            options={'verbose_name': 'Feature Type Edit Mapping', 'verbose_name_plural': 'Feature Type Edit Mappings'},
        ),
        migrations.AlterField(
            model_name='featuretypeeditmapping',
            name='edit_name',
            field=models.CharField(help_text='Edit name, used in map-view FeatureInfo component edit link', max_length=200, verbose_name='Edit name'),
        ),
    ]
