# Generated by Django 5.2.8 on 2026-01-21 10:49

import map.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0013_alter_featuretypeeditmapping_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuretypeeditmapping',
            name='edit_name',
            field=models.CharField(help_text="Name used in the edit link of the map's FeatureInfo component ", max_length=200, verbose_name='Edit name'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='extra_feature_info',
            field=models.JSONField(blank=True, help_text='Fields added here need to be included in the corresponding WFS Feature', null=True, validators=[map.validators.validate_layer_extra_feature_info], verbose_name='Extra feature info'),
        ),
    ]
