# Generated by Django 5.2.12 on 2026-08-05 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrackedManagementCommand',
            fields=[
                ('id', models.CharField(editable=False, max_length=201, primary_key=True, serialize=False)),
                ('app', models.CharField(editable=False, max_length=100)),
                ('command', models.CharField(editable=False, max_length=100)),
                ('comment', models.TextField(blank=True, help_text="Notes on tracking the command or clarifications about the command's purpose")),
                ('latest_tracked_at', models.DateTimeField(editable=False, help_text='Timestamp for moment the command was most recently executed or had its tracking enabled')),
            ],
            options={
                'ordering': ['app', 'command'],
            },
        ),
    ]
