# Generated by Django 5.2.12 on 2026-08-06 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('command_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trackedmanagementcommand',
            old_name='latest_tracked_at',
            new_name='tracking_started_at',
        ),
        migrations.AlterField(
            model_name='trackedmanagementcommand',
            name='tracking_started_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When was usage tracking for this command started'),
        ),
        migrations.AddField(
            model_name='trackedmanagementcommand',
            name='latest_executed_at',
            field=models.DateTimeField(default=None, editable=False, help_text='When was this command last executed. Unknown if it happened before tracking started', null=True),
        ),
    ]
