# Generated by Django 5.2.8 on 2026-01-12 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceMode',
            fields=[
                ('id', models.IntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=False, help_text='When active, all requests (except admin for admin users) will be blocked with 503 status.', verbose_name='Maintenance mode active')),
                ('message_fi', models.TextField(blank=True, default='Järjestelmä on huoltotilassa. Yritä myöhemmin uudelleen.', help_text='Message to display on the maintenance page in Finnish.', verbose_name='Message (Finnish)')),
                ('message_en', models.TextField(blank=True, default='System is under maintenance. Please try again later.', help_text='Message to display on the maintenance page in English.', verbose_name='Message (English)')),
                ('message_sv', models.TextField(blank=True, default='Systemet är under underhåll. Försök igen senare.', help_text='Message to display on the maintenance page in Swedish.', verbose_name='Message (Swedish)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_mode_updates', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Maintenance Mode',
                'verbose_name_plural': 'Maintenance Mode',
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='only_one_maintenance_mode_row')],
            },
        ),
    ]
