# Generated by Django 3.2.12 on 2022-04-13 14:42

import enumfields.fields
from django.db import migrations, models

import traffic_control.enums


def migrate_responsible_entity(apps, schema_editor):
    ResponsibleEntity = apps.get_model("city_furniture", "ResponsibleEntity")

    ResponsibleEntity.objects.filter(organization_level=1).update(organization_level=10)
    ResponsibleEntity.objects.filter(organization_level=2).update(organization_level=20)
    ResponsibleEntity.objects.filter(organization_level=3).update(organization_level=40)


class Migration(migrations.Migration):

    dependencies = [
        ('city_furniture', '0003_responsible_entity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsibleentity',
            name='organization_level',
            field=enumfields.fields.EnumIntegerField(default=50, enum=traffic_control.enums.OrganizationLevel, verbose_name='Organization level'),
        ),
        migrations.AlterField(
            model_name='responsibleentity',
            name='name',
            field=models.CharField(help_text='Name (for projects use Projectwise ID)', max_length=254,
                                   verbose_name='Name'),
        ),
        migrations.RunPython(migrate_responsible_entity, reverse_code=migrations.RunPython.noop),
    ]
