# Generated by Django 3.2.12 on 2022-04-25 16:52

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('city_furniture', '0006_responsible_entity_mptt'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupResponsibleEntity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='group_responsible_entity', to='auth.group', verbose_name='Group')),
                ('responsible_entities', models.ManyToManyField(blank=True, related_name='groups', to='city_furniture.ResponsibleEntity', verbose_name='Responsible Entities')),
            ],
            options={
                'verbose_name': 'Group responsible entity',
                'verbose_name_plural': 'Group responsible entities',
            },
        ),
    ]
