# Generated by Django 3.2.12 on 2022-04-28 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_move_responsible_entity'),
        ('traffic_control', '0048_move_responsible_entity'),
        ('city_furniture', '0008_move_responsible_entity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furnituresignpostplan',
            name='responsible_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='traffic_control.responsibleentity', verbose_name='Responsible entity'),
        ),
        migrations.AlterField(
            model_name='furnituresignpostreal',
            name='responsible_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='traffic_control.responsibleentity', verbose_name='Responsible entity'),
        ),
        migrations.DeleteModel(
            name='GroupResponsibleEntity',
        ),
        migrations.DeleteModel(
            name='ResponsibleEntity',
        ),
    ]
