# Generated by Django 3.2.13 on 2022-06-13 09:42

import colorfield.fields
import django.db.models.deletion
import enumfields.fields
from django.db import migrations, models

import city_furniture.enums
import city_furniture.models.furniture_signpost
import traffic_control.enums


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_control', '0051_help_texts'),
        ('city_furniture', '0010_localize_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityfurniturecolor',
            name='name',
            field=models.CharField(help_text='Name of the color in Helsinki Design System or Manual.', max_length=64, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='cityfurniturecolor',
            name='rgb',
            field=colorfield.fields.ColorField(default='#FFFFFF', help_text='RGB Hex value of the color', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='cityfurnituredevicetype',
            name='class_type',
            field=enumfields.fields.EnumIntegerField(enum=city_furniture.enums.CityFurnitureClassType, help_text='OGC CityGML City Furniture Class', verbose_name='City Furniture Class type'),
        ),
        migrations.AlterField(
            model_name='cityfurnituredevicetype',
            name='code',
            field=models.CharField(help_text='Code of the Device Type in the Helsinki Design Manual.', max_length=32, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='cityfurnituredevicetype',
            name='description_en',
            field=models.CharField(blank=True, help_text='Description of the Device Type in English.', max_length=254, null=True, verbose_name='English Description'),
        ),
        migrations.AlterField(
            model_name='cityfurnituredevicetype',
            name='description_fi',
            field=models.CharField(blank=True, help_text='Description of the Device Type in Finnish.', max_length=254, null=True, verbose_name='Finnish Description'),
        ),
        migrations.AlterField(
            model_name='cityfurnituredevicetype',
            name='description_sw',
            field=models.CharField(blank=True, help_text='Description of the Device Type in Swedish.', max_length=254, null=True, verbose_name='Swedish Description'),
        ),
        migrations.AlterField(
            model_name='cityfurnituredevicetype',
            name='function_type',
            field=enumfields.fields.EnumIntegerField(enum=city_furniture.enums.CityFurnitureFunctionType, help_text='OGC CityGML City Furniture Function or Usage type', verbose_name='City Furniture Function or Usage type'),
        ),
        migrations.AlterField(
            model_name='cityfurnituredevicetype',
            name='icon',
            field=models.CharField(blank=True, help_text='Icon of the actual device', max_length=100, verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='cityfurnituredevicetype',
            name='size',
            field=models.CharField(blank=True, help_text='Standard size of the Device Type.', max_length=50, verbose_name='Size'),
        ),
        migrations.AlterField(
            model_name='cityfurnituredevicetype',
            name='target_model',
            field=enumfields.fields.EnumField(blank=True, enum=city_furniture.enums.CityFurnitureDeviceTypeTargetModel, help_text='City Furniture model that this Device Type is usable for.', max_length=32, null=True, verbose_name='Target data model'),
        ),
        migrations.AlterField(
            model_name='cityfurnituretarget',
            name='description',
            field=models.CharField(blank=True, help_text='Description of the target.', max_length=254, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='cityfurnituretarget',
            name='name_en',
            field=models.CharField(blank=True, help_text='Name of the target in English.', max_length=254, null=True, verbose_name='English name'),
        ),
        migrations.AlterField(
            model_name='cityfurnituretarget',
            name='name_fi',
            field=models.CharField(help_text='Name of the target in Finnish.', max_length=254, verbose_name='Finnish name'),
        ),
        migrations.AlterField(
            model_name='cityfurnituretarget',
            name='name_sw',
            field=models.CharField(blank=True, help_text='Name of the target in Swedish.', max_length=254, null=True, verbose_name='Swedish name'),
        ),
        migrations.AlterField(
            model_name='cityfurnituretarget',
            name='source_id',
            field=models.CharField(blank=True, default=None, help_text='ID of the device in the source where this device was imported from.', max_length=64, null=True, verbose_name='Source id'),
        ),
        migrations.AlterField(
            model_name='cityfurnituretarget',
            name='source_name',
            field=models.CharField(blank=True, default=None, help_text='Name of the source for where this device was imported from.', max_length=254, null=True, verbose_name='Source name'),
        ),
        migrations.AlterField(
            model_name='furnituresignpostplan',
            name='arrow_direction',
            field=enumfields.fields.EnumIntegerField(blank=True, enum=city_furniture.models.furniture_signpost.ArrowDirection, help_text='Direction of the arrow on this device in relation to the sign.', null=True, verbose_name='Arrow direction'),
        ),
        migrations.AlterField(
            model_name='furnituresignpostplan',
            name='color',
            field=models.ForeignKey(blank=True, help_text='Color of the device from Helsinki Design Manual.', null=True, on_delete=django.db.models.deletion.PROTECT, to='city_furniture.cityfurniturecolor', verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='furnituresignpostplan',
            name='content_responsible_entity',
            field=models.CharField(blank=True, help_text="Entity responsible for the device's content.", max_length=254, null=True, verbose_name="Content's responsible entity"),
        ),
        migrations.AlterField(
            model_name='furnituresignpostplan',
            name='device_type',
            field=models.ForeignKey(help_text='Type of the device from Helsinki Design Manual.', limit_choices_to=models.Q(models.Q(('target_model', None), ('target_model', city_furniture.enums.CityFurnitureDeviceTypeTargetModel['FURNITURE_SIGNPOST']), _connector='OR')), on_delete=django.db.models.deletion.PROTECT, to='city_furniture.cityfurnituredevicetype', verbose_name='City Furniture Device type'),
        ),
        migrations.AlterField(
            model_name='furnituresignpostplan',
            name='direction',
            field=models.IntegerField(default=0, help_text='The direction in which the person is standing, when looking directly at the sign. e.g. 0 = North, 45 = North East, 90 = East, 180 = South.', verbose_name='Direction'),
        ),
        migrations.AlterField(
            model_name='furnituresignpostplan',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The height of the sign from the ground, measured from the top in centimeters.', max_digits=5, null=True, verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='furnituresignpostplan',
            name='lifecycle',
            field=enumfields.fields.EnumIntegerField(default=3, enum=traffic_control.enums.Lifecycle, help_text='Lifecycle of the device, which describes the activity status of the device.', verbose_name='Lifecycle'),
        ),
        migrations.AlterField(
            model_name='furnituresignpostplan',
            name='location_name_en',
            field=models.CharField(blank=True, help_text='Verbose name for the furniture signposts location in English, e.g. street, park or island.', max_length=254, null=True, verbose_name='English location name'),
        ),
        migrations.AlterField(
            model_name='furnituresignpostplan',
            name='location_name_fi',
            field=models.CharField(blank=True, help_text='Verbose name for the furniture signposts location in Finnish, e.g. street, park or island.', max_length=254, null=True, verbose_name='Finnish location name'),
        ),
        migrations.AlterField(
            model_name='furnituresignpostplan',
            name='location_name_sw',
            field=models.CharField(blank=True, help_text='Verbose name for the furniture signposts location in Swedish, e.g. street, park or island.', max_length=254, null=True, verbose_name='Swedish location name'),
        ),
        migrations.AlterField(
            model_name='furnituresignpostplan',
            name='mount_plan',
            field=models.ForeignKey(blank=True, help_text='Mount that this device is mounted on.', null=True, on_delete=django.db.models.deletion.PROTECT, to='traffic_control.mountplan', verbose_name='Mount Plan'),
        ),
        migrations.AlterField(
            model_name='furnituresignpostplan',
            name='mount_type',
            field=models.ForeignKey(blank=True, help_text='Type of the mount this device is attached to.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='traffic_control.mounttype', verbose_name='Mount type'),
        ),
        migrations.AlterField(
            model_name='furnituresignpostplan',
            name='order',
            field=models.SmallIntegerField(default=1, help_text='The order of the sign in relation to the signs at the same point. Order from top to bottom, from left to right starting at 1.', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='furnituresignpostplan',
            name='owner',
            field=models.ForeignKey(help_text='Owner who orders and is responsible for the maintenance of the device.', on_delete=django.db.models.deletion.PROTECT, to='traffic_control.owner', verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='furnituresignpostplan',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Furniture Signpost inside which this device is located.', null=True, on_delete=django.db.models.deletion.PROTECT, to='city_furniture.furnituresignpostplan', verbose_name='Parent Furniture Signpost Plan'),
        ),
        migrations.AlterField(
            model_name='furnituresignpostplan',
            name='pictogram',
            field=models.CharField(blank=True, help_text='Description of the pictogram on the sign.', max_length=254, null=True, verbose_name='Pictogram'),
        ),
        migrations.AlterField(
            model_name='furnituresignpostplan',
            name='plan',
            field=models.ForeignKey(blank=True, help_text='Plan which this Device Plan is a part of.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='furniture_signpost_plans', to='traffic_control.plan', verbose_name='Plan'),
        ),
        migrations.AlterField(
            model_name='furnituresignpostplan',
            name='responsible_entity',
            field=models.ForeignKey(blank=True, help_text='Organization or project that this device is assigned to.', null=True, on_delete=django.db.models.deletion.PROTECT, to='traffic_control.responsibleentity', verbose_name='Responsible entity'),
        ),
        migrations.AlterField(
            model_name='furnituresignpostplan',
            name='size',
            field=models.CharField(blank=True, help_text='Size of the signpost. Enter only if device has a non-standard size.', max_length=254, null=True, verbose_name='Size'),
        ),
        migrations.AlterField(
            model_name='furnituresignpostplan',
            name='source_id',
            field=models.CharField(blank=True, default=None, help_text='ID of the device in the source where this device was imported from.', max_length=64, null=True, verbose_name='Source id'),
        ),
        migrations.AlterField(
            model_name='furnituresignpostplan',
            name='source_name',
            field=models.CharField(blank=True, default=None, help_text='Name of the source for where this device was imported from.', max_length=254, null=True, verbose_name='Source name'),
        ),
        migrations.AlterField(
            model_name='furnituresignpostplan',
            name='target',
            field=models.ForeignKey(blank=True, help_text='Target subject, which this device relates to.', null=True, on_delete=django.db.models.deletion.PROTECT, to='city_furniture.cityfurnituretarget', verbose_name='Target'),
        ),
        migrations.AlterField(
            model_name='furnituresignpostplan',
            name='text_content_en',
            field=models.TextField(blank=True, help_text='Content of the sign in English.', null=True, verbose_name='English text content'),
        ),
        migrations.AlterField(
            model_name='furnituresignpostplan',
            name='text_content_fi',
            field=models.TextField(blank=True, help_text='Content of the sign in Finnish.', null=True, verbose_name='Finnish text content'),
        ),
        migrations.AlterField(
            model_name='furnituresignpostplan',
            name='text_content_sw',
            field=models.TextField(blank=True, help_text='Content of the sign in Swedish.', null=True, verbose_name='Swedish text content'),
        ),
        migrations.AlterField(
            model_name='furnituresignpostplan',
            name='validity_period_end',
            field=models.DateField(blank=True, help_text='Date after which this device becomes inactive.', null=True, verbose_name='Validity period end'),
        ),
        migrations.AlterField(
            model_name='furnituresignpostplan',
            name='validity_period_start',
            field=models.DateField(blank=True, help_text='Date on which this device becomes active.', null=True, verbose_name='Validity period start'),
        ),
        migrations.AlterField(
            model_name='furnituresignpostplan',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Numeric value on the sign.', max_digits=10, null=True, verbose_name='Furniture signpost value'),
        ),
        migrations.AlterField(
            model_name='furnituresignpostreal',
            name='arrow_direction',
            field=enumfields.fields.EnumIntegerField(blank=True, enum=city_furniture.models.furniture_signpost.ArrowDirection, help_text='Direction of the arrow on this device in relation to the sign.', null=True, verbose_name='Arrow direction'),
        ),
        migrations.AlterField(
            model_name='furnituresignpostreal',
            name='color',
            field=models.ForeignKey(blank=True, help_text='Color of the device from Helsinki Design Manual.', null=True, on_delete=django.db.models.deletion.PROTECT, to='city_furniture.cityfurniturecolor', verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='furnituresignpostreal',
            name='condition',
            field=enumfields.fields.EnumIntegerField(blank=True, default=5, enum=traffic_control.enums.Condition, help_text='Describes the condition of this device.', null=True, verbose_name='Condition'),
        ),
        migrations.AlterField(
            model_name='furnituresignpostreal',
            name='content_responsible_entity',
            field=models.CharField(blank=True, help_text="Entity responsible for the device's content.", max_length=254, null=True, verbose_name="Content's responsible entity"),
        ),
        migrations.AlterField(
            model_name='furnituresignpostreal',
            name='device_type',
            field=models.ForeignKey(help_text='Type of the device from Helsinki Design Manual.', limit_choices_to=models.Q(models.Q(('target_model', None), ('target_model', city_furniture.enums.CityFurnitureDeviceTypeTargetModel['FURNITURE_SIGNPOST']), _connector='OR')), on_delete=django.db.models.deletion.PROTECT, to='city_furniture.cityfurnituredevicetype', verbose_name='City Furniture Device type'),
        ),
        migrations.AlterField(
            model_name='furnituresignpostreal',
            name='direction',
            field=models.IntegerField(default=0, help_text='The direction in which the person is standing, when looking directly at the sign. e.g. 0 = North, 45 = North East, 90 = East, 180 = South.', verbose_name='Direction'),
        ),
        migrations.AlterField(
            model_name='furnituresignpostreal',
            name='furniture_signpost_plan',
            field=models.ForeignKey(blank=True, help_text='The plan for this device.', null=True, on_delete=django.db.models.deletion.PROTECT, to='city_furniture.furnituresignpostplan', verbose_name='Furniture Signpost Plan'),
        ),
        migrations.AlterField(
            model_name='furnituresignpostreal',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The height of the sign from the ground, measured from the top in centimeters.', max_digits=5, null=True, verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='furnituresignpostreal',
            name='installation_date',
            field=models.DateField(blank=True, help_text='Date on which this device was installed on.', null=True, verbose_name='Installation date'),
        ),
        migrations.AlterField(
            model_name='furnituresignpostreal',
            name='installation_status',
            field=enumfields.fields.EnumField(blank=True, default='IN_USE', enum=traffic_control.enums.InstallationStatus, help_text='Describes this devices installation status.', max_length=10, null=True, verbose_name='Installation status'),
        ),
        migrations.AlterField(
            model_name='furnituresignpostreal',
            name='lifecycle',
            field=enumfields.fields.EnumIntegerField(default=3, enum=traffic_control.enums.Lifecycle, help_text='Lifecycle of the device, which describes the activity status of the device.', verbose_name='Lifecycle'),
        ),
        migrations.AlterField(
            model_name='furnituresignpostreal',
            name='location_name_en',
            field=models.CharField(blank=True, help_text='Verbose name for the furniture signposts location in English, e.g. street, park or island.', max_length=254, null=True, verbose_name='English location name'),
        ),
        migrations.AlterField(
            model_name='furnituresignpostreal',
            name='location_name_fi',
            field=models.CharField(blank=True, help_text='Verbose name for the furniture signposts location in Finnish, e.g. street, park or island.', max_length=254, null=True, verbose_name='Finnish location name'),
        ),
        migrations.AlterField(
            model_name='furnituresignpostreal',
            name='location_name_sw',
            field=models.CharField(blank=True, help_text='Verbose name for the furniture signposts location in Swedish, e.g. street, park or island.', max_length=254, null=True, verbose_name='Swedish location name'),
        ),
        migrations.AlterField(
            model_name='furnituresignpostreal',
            name='mount_real',
            field=models.ForeignKey(blank=True, help_text='Mount that this device is mounted on.', null=True, on_delete=django.db.models.deletion.PROTECT, to='traffic_control.mountreal', verbose_name='Mount Real'),
        ),
        migrations.AlterField(
            model_name='furnituresignpostreal',
            name='mount_type',
            field=models.ForeignKey(blank=True, help_text='Type of the mount this device is attached to.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='traffic_control.mounttype', verbose_name='Mount type'),
        ),
        migrations.AlterField(
            model_name='furnituresignpostreal',
            name='order',
            field=models.SmallIntegerField(default=1, help_text='The order of the sign in relation to the signs at the same point. Order from top to bottom, from left to right starting at 1.', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='furnituresignpostreal',
            name='owner',
            field=models.ForeignKey(help_text='Owner who orders and is responsible for the maintenance of the device.', on_delete=django.db.models.deletion.PROTECT, to='traffic_control.owner', verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='furnituresignpostreal',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Furniture Signpost inside which this device is located.', null=True, on_delete=django.db.models.deletion.PROTECT, to='city_furniture.furnituresignpostreal', verbose_name='Parent Furniture Signpost Real'),
        ),
        migrations.AlterField(
            model_name='furnituresignpostreal',
            name='pictogram',
            field=models.CharField(blank=True, help_text='Description of the pictogram on the sign.', max_length=254, null=True, verbose_name='Pictogram'),
        ),
        migrations.AlterField(
            model_name='furnituresignpostreal',
            name='responsible_entity',
            field=models.ForeignKey(blank=True, help_text='Organization or project that this device is assigned to.', null=True, on_delete=django.db.models.deletion.PROTECT, to='traffic_control.responsibleentity', verbose_name='Responsible entity'),
        ),
        migrations.AlterField(
            model_name='furnituresignpostreal',
            name='size',
            field=models.CharField(blank=True, help_text='Size of the signpost. Enter only if device has a non-standard size.', max_length=254, null=True, verbose_name='Size'),
        ),
        migrations.AlterField(
            model_name='furnituresignpostreal',
            name='source_id',
            field=models.CharField(blank=True, default=None, help_text='ID of the device in the source where this device was imported from.', max_length=64, null=True, verbose_name='Source id'),
        ),
        migrations.AlterField(
            model_name='furnituresignpostreal',
            name='source_name',
            field=models.CharField(blank=True, default=None, help_text='Name of the source for where this device was imported from.', max_length=254, null=True, verbose_name='Source name'),
        ),
        migrations.AlterField(
            model_name='furnituresignpostreal',
            name='target',
            field=models.ForeignKey(blank=True, help_text='Target subject, which this device relates to.', null=True, on_delete=django.db.models.deletion.PROTECT, to='city_furniture.cityfurnituretarget', verbose_name='Target'),
        ),
        migrations.AlterField(
            model_name='furnituresignpostreal',
            name='text_content_en',
            field=models.TextField(blank=True, help_text='Content of the sign in English.', null=True, verbose_name='English text content'),
        ),
        migrations.AlterField(
            model_name='furnituresignpostreal',
            name='text_content_fi',
            field=models.TextField(blank=True, help_text='Content of the sign in Finnish.', null=True, verbose_name='Finnish text content'),
        ),
        migrations.AlterField(
            model_name='furnituresignpostreal',
            name='text_content_sw',
            field=models.TextField(blank=True, help_text='Content of the sign in Swedish.', null=True, verbose_name='Swedish text content'),
        ),
        migrations.AlterField(
            model_name='furnituresignpostreal',
            name='validity_period_end',
            field=models.DateField(blank=True, help_text='Date after which this device becomes inactive.', null=True, verbose_name='Validity period end'),
        ),
        migrations.AlterField(
            model_name='furnituresignpostreal',
            name='validity_period_start',
            field=models.DateField(blank=True, help_text='Date on which this device becomes active.', null=True, verbose_name='Validity period start'),
        ),
        migrations.AlterField(
            model_name='furnituresignpostreal',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Numeric value on the sign.', max_digits=10, null=True, verbose_name='Furniture signpost value'),
        ),
    ]
