# Generated by Django 3.2.16 on 2022-12-15 11:54

from django.db import migrations
import enumfields.fields
import traffic_control.enums


class Migration(migrations.Migration):

    dependencies = [
        ('city_furniture', '0011_help_texts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furnituresignpostreal',
            name='condition',
            field=enumfields.fields.EnumIntegerField(blank=True, enum=traffic_control.enums.Condition, help_text='Describes the condition of this device.', null=True, verbose_name='Condition'),
        ),
        migrations.AlterField(
            model_name='furnituresignpostreal',
            name='installation_status',
            field=enumfields.fields.EnumField(blank=True, enum=traffic_control.enums.InstallationStatus, help_text='Describes this devices installation status.', max_length=10, null=True, verbose_name='Installation status'),
        ),
    ]
