# Generated by Django 3.2.21 on 2023-09-22 10:41

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("city_furniture", "0013_device_users_nullable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cityfurniturecolor",
            name="rgb",
            field=colorfield.fields.ColorField(
                default="#FFFFFF", help_text="RGB Hex value of the color", image_field=None, max_length=25, samples=None
            ),
        ),
    ]
