# Generated by Django 3.2.22 on 2023-11-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city_furniture', '0014_alter_cityfurniturecolor_rgb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furnituresignpostplan',
            name='direction',
            field=models.IntegerField(blank=True, help_text='The direction a person is facing when looking perpendicular to the sign. The value is in degrees from 0 to 359, where 0 is north, 90 is east, etc.', null=True, verbose_name='Direction'),
        ),
        migrations.AlterField(
            model_name='furnituresignpostreal',
            name='direction',
            field=models.IntegerField(blank=True, help_text='The direction a person is facing when looking perpendicular to the sign. The value is in degrees from 0 to 359, where 0 is north, 90 is east, etc.', null=True, verbose_name='Direction'),
        ),
    ]
