# Generated by Django 4.0 on 2024-02-16 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_help_texts'),
        ('city_furniture', '0016_source_id_source_name_unique_for_active_objects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furnituresignpostplan',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_%(class)s_set', to='users.user', verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='furnituresignpostplan',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_by_%(class)s_set', to='users.user', verbose_name='Deleted by'),
        ),
        migrations.AlterField(
            model_name='furnituresignpostplan',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_by_%(class)s_set', to='users.user', verbose_name='Updated by'),
        ),
        migrations.AlterField(
            model_name='furnituresignpostreal',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_%(class)s_set', to='users.user', verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='furnituresignpostreal',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_by_%(class)s_set', to='users.user', verbose_name='Deleted by'),
        ),
        migrations.AlterField(
            model_name='furnituresignpostreal',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_by_%(class)s_set', to='users.user', verbose_name='Updated by'),
        ),
        migrations.AlterField(
            model_name='furnituresignpostrealoperation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_%(class)s_set', to='users.user', verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='furnituresignpostrealoperation',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_by_%(class)s_set', to='users.user', verbose_name='Updated by'),
        ),
    ]
