# Generated by Django 4.2.15 on 2024-10-07 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city_furniture', '0018_alter_furnituresignpostplan_height_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='furnituresignpostreal',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('furniture_signpost_plan',), name='city_furniture_furnituresignpostreal_unique_furniture_signpost_plan_id'),
        ),
    ]
