# Generated by Django 4.2.22 on 2025-08-20 11:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('city_furniture', '0019_furnituresignpostreal_city_furniture_furnituresignpostreal_unique_furniture_signpost_plan_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityFurnitureDeviceTypeIcon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('file', models.FileField(upload_to='icons/city_furniture_device_type/', verbose_name='File')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='cityfurnituredevicetype',
            name='icon_file',
            field=models.ForeignKey(blank=True, help_text='Icon of the actual device', null=True, on_delete=django.db.models.deletion.CASCADE, to='city_furniture.cityfurnituredevicetypeicon'),
        ),
    ]
