# Generated by Django 4.2.20 on 2025-09-01 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city_furniture', '0019_furnituresignpostreal_city_furniture_furnituresignpostreal_unique_furniture_signpost_plan_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='furnituresignpostplan',
            name='order',
        ),
        migrations.RemoveField(
            model_name='furnituresignpostreal',
            name='order',
        ),
    ]
