# Generated by Django 4.2.22 on 2025-10-01 07:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('city_furniture', '0020_remove_furnituresignpostplan_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityFurnitureDeviceTypeIcon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('file', models.FileField(upload_to='icons/city_furniture_device_type/svg/', verbose_name='File')),
            ],
            options={
                'verbose_name': 'City Furniture Device Type Icon',
                'verbose_name_plural': 'City Furniture Device Type Icons',
                'db_table': 'city_furniture_device_type_icon',
            },
        ),
        migrations.AddField(
            model_name='cityfurnituredevicetype',
            name='icon_file',
            field=models.ForeignKey(blank=True, help_text='Icon of the actual device', null=True, on_delete=django.db.models.deletion.PROTECT, to='city_furniture.cityfurnituredevicetypeicon'),
        ),
    ]
