# Generated by Django 4.2.22 on 2025-08-20 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city_furniture', '0020_cityfurnituredevicetypeicon_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cityfurnituredevicetypeicon',
            options={'verbose_name': 'City Furniture Device Type Icon', 'verbose_name_plural': 'City Furniture Device Type Icons'},
        ),
        migrations.AlterField(
            model_name='cityfurnituredevicetypeicon',
            name='file',
            field=models.FileField(upload_to='icons/city_furniture_device_type/svg/', verbose_name='File'),
        ),
        migrations.AlterModelTable(
            name='cityfurnituredevicetypeicon',
            table='city_furniture_device_type_icon',
        ),
    ]
