# Generated by Django 4.2.22 on 2025-08-21 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('city_furniture', '0021_alter_cityfurnituredevicetypeicon_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityfurnituredevicetype',
            name='icon_file',
            field=models.ForeignKey(blank=True, help_text='Icon of the actual device', null=True, on_delete=django.db.models.deletion.PROTECT, to='city_furniture.cityfurnituredevicetypeicon'),
        ),
    ]
