# Generated by Django 4.2.22 on 2025-10-01 07:23

import city_furniture.models.common
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city_furniture', '0021_cityfurnituredevicetypeicon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityfurnituredevicetypeicon',
            name='file',
            field=models.FileField(storage=city_furniture.models.common.city_furniture_device_type_icon_storage, unique=True, upload_to='icons/city_furniture_device_type/svg/', verbose_name='File'),
        ),
    ]
