# Generated by Django 4.2.20 on 2025-10-20 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city_furniture', '0022_alter_cityfurnituredevicetypeicon_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cityfurnituredevicetype',
            name='icon',
        ),
    ]
