# Generated by Django 4.2.25 on 2025-10-30 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city_furniture', '0023_remove_cityfurnituredevicetype_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityfurnituredevicetypeicon',
            name='is_public',
            field=models.BooleanField(default=True, help_text='If unchecked, access is restricted to users/groups with appropriate table or file permissions', verbose_name='Is public'),
        ),
        migrations.AddField(
            model_name='furnituresignpostplanfile',
            name='is_public',
            field=models.BooleanField(default=True, help_text='If unchecked, access is restricted to users/groups with appropriate table or file permissions', verbose_name='Is public'),
        ),
        migrations.AddField(
            model_name='furnituresignpostrealfile',
            name='is_public',
            field=models.BooleanField(default=True, help_text='If unchecked, access is restricted to users/groups with appropriate table or file permissions', verbose_name='Is public'),
        ),
    ]
