# Generated by Django 4.2.26 on 2025-12-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city_furniture', '0024_cityfurnituredevicetypeicon_is_public_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furnituresignpostplan',
            name='direction',
            field=models.IntegerField(blank=True, help_text='The orientation of the device’s front side in degrees (0–359): 0 = north, 90 = east, 180 = south, 270 = west. The direction indicates from which side the device is correctly visible.', null=True, verbose_name='Direction'),
        ),
        migrations.AlterField(
            model_name='furnituresignpostreal',
            name='direction',
            field=models.IntegerField(blank=True, help_text='The orientation of the device’s front side in degrees (0–359): 0 = north, 90 = east, 180 = south, 270 = west. The direction indicates from which side the device is correctly visible.', null=True, verbose_name='Direction'),
        ),
    ]
