# Generated by Django 4.2.26 on 2025-12-15 11:10

from django.db import migrations


def set_dummy_device_type_for_null_values(apps, schema_editor):
    """
    Create or get the DummyDT device type and set it for all devices with null device_type.
    This must be done before making the field non-nullable.
    """
    CityFurnitureDeviceType = apps.get_model("city_furniture", "CityFurnitureDeviceType")

    # Get or create the DummyDT device type
    # Using integer values directly since enums may not be available in migrations
    dummy_dt, created = CityFurnitureDeviceType.objects.get_or_create(
        code="DummyDT",
        defaults={
            "description_fi": "Paikanpitäjä laitteille, joilla ei ole device_type asetettu",
            "description_en": "Placeholder for devices that have None set to device_type",
            "class_type": 1030,  # CityFurnitureClassType.OTHERS
            "function_type": 1090,  # CityFurnitureFunctionType.FREE_STANDING_SIGN
            "target_model": None,
        },
    )

    # Models with device_type field in city_furniture app
    models_to_update = [
        "FurnitureSignpostPlan",
        "FurnitureSignpostReal",
    ]

    total_updated = 0
    for model_name in models_to_update:
        try:
            Model = apps.get_model("city_furniture", model_name)
            updated = Model.objects.filter(device_type__isnull=True).update(device_type=dummy_dt)
            if updated > 0:
                print(f"  Updated {updated} {model_name} records with DummyDT device type")
                total_updated += updated
        except LookupError:
            # Model doesn't exist, skip it
            pass

    if total_updated > 0:
        print(f"Total: Updated {total_updated} device records with DummyDT device type")
    else:
        print("No devices with device_type=None found")


def reverse_dummy_device_type(apps, schema_editor):
    """
    Reverse operation: set device_type back to null for all devices using DummyDT.
    Note: This will fail if the field is already non-nullable.
    """
    CityFurnitureDeviceType = apps.get_model("city_furniture", "CityFurnitureDeviceType")

    try:
        dummy_dt = CityFurnitureDeviceType.objects.get(code="DummyDT")
    except CityFurnitureDeviceType.DoesNotExist:
        print("DummyDT device type not found, nothing to reverse")
        return

    models_to_update = [
        "FurnitureSignpostPlan",
        "FurnitureSignpostReal",
    ]

    total_updated = 0
    for model_name in models_to_update:
        try:
            Model = apps.get_model("city_furniture", model_name)
            updated = Model.objects.filter(device_type=dummy_dt).update(device_type=None)
            if updated > 0:
                print(f"  Reversed {updated} {model_name} records back to null device_type")
                total_updated += updated
        except LookupError:
            pass

    if total_updated > 0:
        print(f"Total: Reversed {total_updated} device records back to null device_type")


class Migration(migrations.Migration):

    dependencies = [
        ('city_furniture', '0025_alter_furnituresignpostplan_direction_and_more'),
    ]

    operations = [
        # First, set dummy device type for all null values
        migrations.RunPython(
            set_dummy_device_type_for_null_values,
            reverse_dummy_device_type,
        ),
    ]

