# Generated by Django 4.2.26 on 2025-12-15 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('city_furniture', '0026_set_device_type_non_nullable'),
    ]

    operations = [
        # Make device_type non-nullable for all models
        # Note: Migration 0026 already set DummyDT for all null values
        migrations.AlterField(
            model_name='furnituresignpostplan',
            name='device_type',
            field=models.ForeignKey(
                help_text='Type of the device from Helsinki Design Manual.',
                limit_choices_to=models.Q(models.Q(('target_model', None)), models.Q(('target_model', 'furniture_signpost')), _connector='OR'),
                on_delete=django.db.models.deletion.PROTECT,
                to='city_furniture.cityfurnituredevicetype',
                verbose_name='City Furniture Device type'
            ),
        ),
        migrations.AlterField(
            model_name='furnituresignpostreal',
            name='device_type',
            field=models.ForeignKey(
                help_text='Type of the device from Helsinki Design Manual.',
                limit_choices_to=models.Q(models.Q(('target_model', None)), models.Q(('target_model', 'furniture_signpost')), _connector='OR'),
                on_delete=django.db.models.deletion.PROTECT,
                to='city_furniture.cityfurnituredevicetype',
                verbose_name='City Furniture Device type'
            ),
        ),
    ]

