# Generated by Django 4.2.26 on 2025-12-18 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('city_furniture', '0027_make_device_type_non_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furnituresignpostplan',
            name='device_type',
            field=models.ForeignKey(help_text='Type of the device from Helsinki Design Manual.', limit_choices_to=models.Q(models.Q(('target_model', None), ('target_model', 'furniture_signpost'), _connector='OR')), on_delete=django.db.models.deletion.PROTECT, to='city_furniture.cityfurnituredevicetype', verbose_name='City Furniture Device type'),
        ),
        migrations.AlterField(
            model_name='furnituresignpostreal',
            name='device_type',
            field=models.ForeignKey(help_text='Type of the device from Helsinki Design Manual.', limit_choices_to=models.Q(models.Q(('target_model', None), ('target_model', 'furniture_signpost'), _connector='OR')), on_delete=django.db.models.deletion.PROTECT, to='city_furniture.cityfurnituredevicetype', verbose_name='City Furniture Device type'),
        ),
    ]
