# Generated by Django 5.2.8 on 2026-01-20 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city_furniture', '0028_alter_furnituresignpostplan_device_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityfurnituredevicetype',
            name='icon_file',
            field=models.ForeignKey(blank=True, help_text='Icon of the actual device', null=True, on_delete=django.db.models.deletion.PROTECT, to='city_furniture.cityfurnituredevicetypeicon', verbose_name='Icon file'),
        ),
    ]
