# Generated by Django 2.2.12 on 2020-06-10 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("traffic_control", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="signpostplan", name="mount_type",),
        migrations.RemoveField(model_name="signpostreal", name="mount_type",),
        migrations.RemoveField(model_name="trafficlightplan", name="mount_type",),
        migrations.RemoveField(model_name="trafficlightreal", name="mount_type",),
        migrations.RemoveField(model_name="trafficsignplan", name="mount_type",),
        migrations.RemoveField(model_name="trafficsignreal", name="mount_type",),
    ]
