# Generated by Django 2.2.13 on 2020-06-11 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traffic_control", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="barrierplan",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_by_barrierplan_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AlterField(
            model_name="barrierplan",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="deleted_by_barrierplan_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Deleted by",
            ),
        ),
        migrations.AlterField(
            model_name="barrierplan",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="barrier_plans",
                to="traffic_control.Plan",
                verbose_name="Plan",
            ),
        ),
        migrations.AlterField(
            model_name="barrierplan",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="traffic_control.TrafficSignCode",
                verbose_name="Barrier type",
            ),
        ),
        migrations.AlterField(
            model_name="barrierplan",
            name="updated_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="updated_by_barrierplan_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated by",
            ),
        ),
        migrations.AlterField(
            model_name="barrierreal",
            name="barrier_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="traffic_control.BarrierPlan",
                verbose_name="Barrier Plan",
            ),
        ),
        migrations.AlterField(
            model_name="barrierreal",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_by_barrierreal_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AlterField(
            model_name="barrierreal",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="deleted_by_barrierreal_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Deleted by",
            ),
        ),
        migrations.AlterField(
            model_name="barrierreal",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="traffic_control.TrafficSignCode",
                verbose_name="Barrier type",
            ),
        ),
        migrations.AlterField(
            model_name="barrierreal",
            name="updated_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="updated_by_barrierreal_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated by",
            ),
        ),
        migrations.AlterField(
            model_name="mountplan",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_by_mountplan_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AlterField(
            model_name="mountplan",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="deleted_by_mountplan_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Deleted by",
            ),
        ),
        migrations.AlterField(
            model_name="mountplan",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="mount_plans",
                to="traffic_control.Plan",
                verbose_name="Plan",
            ),
        ),
        migrations.AlterField(
            model_name="mountplan",
            name="portal_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="traffic_control.PortalType",
                verbose_name="Portal type",
            ),
        ),
        migrations.AlterField(
            model_name="mountplan",
            name="updated_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="updated_by_mountplan_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated by",
            ),
        ),
        migrations.AlterField(
            model_name="mountreal",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_by_mountreal_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AlterField(
            model_name="mountreal",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="deleted_by_mountreal_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Deleted by",
            ),
        ),
        migrations.AlterField(
            model_name="mountreal",
            name="mount_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="traffic_control.MountPlan",
                verbose_name="Mount Plan",
            ),
        ),
        migrations.AlterField(
            model_name="mountreal",
            name="portal_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="traffic_control.PortalType",
                verbose_name="Portal type",
            ),
        ),
        migrations.AlterField(
            model_name="mountreal",
            name="updated_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="updated_by_mountreal_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated by",
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_by_plan_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="deleted_by_plan_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Deleted by",
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="updated_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="updated_by_plan_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated by",
            ),
        ),
        migrations.AlterField(
            model_name="roadmarkingplan",
            name="code",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="traffic_control.TrafficSignCode",
                verbose_name="Traffic Sign Code",
            ),
        ),
        migrations.AlterField(
            model_name="roadmarkingplan",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_by_roadmarkingplan_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AlterField(
            model_name="roadmarkingplan",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="deleted_by_roadmarkingplan_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Deleted by",
            ),
        ),
        migrations.AlterField(
            model_name="roadmarkingplan",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="road_marking_plans",
                to="traffic_control.Plan",
                verbose_name="Plan",
            ),
        ),
        migrations.AlterField(
            model_name="roadmarkingplan",
            name="traffic_sign_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="traffic_control.TrafficSignPlan",
                verbose_name="Traffic Sign Plan",
            ),
        ),
        migrations.AlterField(
            model_name="roadmarkingplan",
            name="updated_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="updated_by_roadmarkingplan_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated by",
            ),
        ),
        migrations.AlterField(
            model_name="roadmarkingreal",
            name="code",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="traffic_control.TrafficSignCode",
                verbose_name="Traffic Sign Code",
            ),
        ),
        migrations.AlterField(
            model_name="roadmarkingreal",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_by_roadmarkingreal_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AlterField(
            model_name="roadmarkingreal",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="deleted_by_roadmarkingreal_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Deleted by",
            ),
        ),
        migrations.AlterField(
            model_name="roadmarkingreal",
            name="road_marking_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="traffic_control.RoadMarkingPlan",
                verbose_name="Road Marking Plan",
            ),
        ),
        migrations.AlterField(
            model_name="roadmarkingreal",
            name="traffic_sign_real",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="traffic_control.TrafficSignReal",
                verbose_name="Traffic Sign Real",
            ),
        ),
        migrations.AlterField(
            model_name="roadmarkingreal",
            name="updated_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="updated_by_roadmarkingreal_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated by",
            ),
        ),
        migrations.AlterField(
            model_name="signpostplan",
            name="code",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="traffic_control.TrafficSignCode",
                verbose_name="Signpost Code",
            ),
        ),
        migrations.AlterField(
            model_name="signpostplan",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_by_signpostplan_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AlterField(
            model_name="signpostplan",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="deleted_by_signpostplan_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Deleted by",
            ),
        ),
        migrations.AlterField(
            model_name="signpostplan",
            name="mount_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="traffic_control.MountPlan",
                verbose_name="Mount Plan",
            ),
        ),
        migrations.AlterField(
            model_name="signpostplan",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="traffic_control.SignpostPlan",
                verbose_name="Parent Signpost Plan",
            ),
        ),
        migrations.AlterField(
            model_name="signpostplan",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="signpost_plans",
                to="traffic_control.Plan",
                verbose_name="Plan",
            ),
        ),
        migrations.AlterField(
            model_name="signpostplan",
            name="updated_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="updated_by_signpostplan_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated by",
            ),
        ),
        migrations.AlterField(
            model_name="signpostreal",
            name="code",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="traffic_control.TrafficSignCode",
                verbose_name="Signpost Code",
            ),
        ),
        migrations.AlterField(
            model_name="signpostreal",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_by_signpostreal_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AlterField(
            model_name="signpostreal",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="deleted_by_signpostreal_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Deleted by",
            ),
        ),
        migrations.AlterField(
            model_name="signpostreal",
            name="mount_real",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="traffic_control.MountReal",
                verbose_name="Mount Real",
            ),
        ),
        migrations.AlterField(
            model_name="signpostreal",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="traffic_control.SignpostReal",
                verbose_name="Parent Signpost Real",
            ),
        ),
        migrations.AlterField(
            model_name="signpostreal",
            name="signpost_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="traffic_control.SignpostPlan",
                verbose_name="Signpost Plan",
            ),
        ),
        migrations.AlterField(
            model_name="signpostreal",
            name="updated_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="updated_by_signpostreal_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated by",
            ),
        ),
        migrations.AlterField(
            model_name="trafficlightplan",
            name="code",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="traffic_control.TrafficSignCode",
                verbose_name="Traffic Sign Code",
            ),
        ),
        migrations.AlterField(
            model_name="trafficlightplan",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_by_trafficlightplan_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AlterField(
            model_name="trafficlightplan",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="deleted_by_trafficlightplan_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Deleted by",
            ),
        ),
        migrations.AlterField(
            model_name="trafficlightplan",
            name="mount_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="traffic_control.MountPlan",
                verbose_name="Mount Plan",
            ),
        ),
        migrations.AlterField(
            model_name="trafficlightplan",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="traffic_light_plans",
                to="traffic_control.Plan",
                verbose_name="Plan",
            ),
        ),
        migrations.AlterField(
            model_name="trafficlightplan",
            name="updated_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="updated_by_trafficlightplan_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated by",
            ),
        ),
        migrations.AlterField(
            model_name="trafficlightreal",
            name="code",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="traffic_control.TrafficSignCode",
                verbose_name="Traffic Sign Code",
            ),
        ),
        migrations.AlterField(
            model_name="trafficlightreal",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_by_trafficlightreal_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AlterField(
            model_name="trafficlightreal",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="deleted_by_trafficlightreal_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Deleted by",
            ),
        ),
        migrations.AlterField(
            model_name="trafficlightreal",
            name="mount_real",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="traffic_control.MountReal",
                verbose_name="Mount Real",
            ),
        ),
        migrations.AlterField(
            model_name="trafficlightreal",
            name="traffic_light_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="traffic_control.TrafficLightPlan",
                verbose_name="Traffic Light Plan",
            ),
        ),
        migrations.AlterField(
            model_name="trafficlightreal",
            name="updated_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="updated_by_trafficlightreal_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated by",
            ),
        ),
        migrations.AlterField(
            model_name="trafficsignplan",
            name="code",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="traffic_control.TrafficSignCode",
                verbose_name="Traffic Sign Code",
            ),
        ),
        migrations.AlterField(
            model_name="trafficsignplan",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_by_trafficsignplan_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AlterField(
            model_name="trafficsignplan",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="deleted_by_trafficsignplan_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Deleted by",
            ),
        ),
        migrations.AlterField(
            model_name="trafficsignplan",
            name="mount_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="traffic_control.MountPlan",
                verbose_name="Mount Plan",
            ),
        ),
        migrations.AlterField(
            model_name="trafficsignplan",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="children",
                to="traffic_control.TrafficSignPlan",
                verbose_name="Parent Traffic Sign Plan",
            ),
        ),
        migrations.AlterField(
            model_name="trafficsignplan",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="traffic_sign_plans",
                to="traffic_control.Plan",
                verbose_name="Plan",
            ),
        ),
        migrations.AlterField(
            model_name="trafficsignplan",
            name="updated_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="updated_by_trafficsignplan_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated by",
            ),
        ),
        migrations.AlterField(
            model_name="trafficsignreal",
            name="code",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="traffic_control.TrafficSignCode",
                verbose_name="Traffic Sign Code",
            ),
        ),
        migrations.AlterField(
            model_name="trafficsignreal",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_by_trafficsignreal_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AlterField(
            model_name="trafficsignreal",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="deleted_by_trafficsignreal_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Deleted by",
            ),
        ),
        migrations.AlterField(
            model_name="trafficsignreal",
            name="mount_real",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="traffic_control.MountReal",
                verbose_name="Mount Real",
            ),
        ),
        migrations.AlterField(
            model_name="trafficsignreal",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="children",
                to="traffic_control.TrafficSignReal",
                verbose_name="Parent Traffic Sign Real",
            ),
        ),
        migrations.AlterField(
            model_name="trafficsignreal",
            name="traffic_sign_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="traffic_control.TrafficSignPlan",
                verbose_name="Traffic Sign Plan",
            ),
        ),
        migrations.AlterField(
            model_name="trafficsignreal",
            name="updated_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="updated_by_trafficsignreal_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated by",
            ),
        ),
    ]
