# Generated by Django 2.2.10 on 2020-03-18 14:25

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traffic_control", "0003_change_plan_links_to_plan_documents"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trafficsignplan",
            name="height",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=20,
                null=True,
                verbose_name="Height",
            ),
        ),
        migrations.AlterField(
            model_name="trafficsignplan",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                dim=3, srid=3879, verbose_name="Location (3D)"
            ),
        ),
        migrations.AlterField(
            model_name="trafficsignreal",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                dim=3, srid=3879, verbose_name="Location (3D)"
            ),
        ),
    ]
