# Generated by Django 2.2.13 on 2020-06-15 10:48

import django.db.models.deletion
import enumfields.fields
from django.db import migrations, models

import traffic_control.enums
import traffic_control.models.common


class Migration(migrations.Migration):

    dependencies = [
        ("traffic_control", "0003_rename_traffic_sign_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="trafficcontroldevicetype",
            name="target_model",
            field=enumfields.fields.EnumField(
                blank=True,
                enum=traffic_control.enums.DeviceTypeTargetModel,
                max_length=32,
                null=True,
                verbose_name="Target data model",
            ),
        ),
        migrations.AlterField(
            model_name="barrierplan",
            name="device_type",
            field=models.ForeignKey(
                limit_choices_to=models.Q(
                    models.Q(
                        ("target_model", None),
                        (
                            "target_model",
                            traffic_control.enums.DeviceTypeTargetModel(
                                "barrier"
                            ),
                        ),
                        _connector="OR",
                    )
                ),
                on_delete=django.db.models.deletion.PROTECT,
                to="traffic_control.TrafficControlDeviceType",
                verbose_name="Device type",
            ),
        ),
        migrations.AlterField(
            model_name="barrierreal",
            name="device_type",
            field=models.ForeignKey(
                limit_choices_to=models.Q(
                    models.Q(
                        ("target_model", None),
                        (
                            "target_model",
                            traffic_control.enums.DeviceTypeTargetModel(
                                "barrier"
                            ),
                        ),
                        _connector="OR",
                    )
                ),
                on_delete=django.db.models.deletion.PROTECT,
                to="traffic_control.TrafficControlDeviceType",
                verbose_name="Device type",
            ),
        ),
        migrations.AlterField(
            model_name="roadmarkingplan",
            name="device_type",
            field=models.ForeignKey(
                limit_choices_to=models.Q(
                    models.Q(
                        ("target_model", None),
                        (
                            "target_model",
                            traffic_control.enums.DeviceTypeTargetModel(
                                "road_marking"
                            ),
                        ),
                        _connector="OR",
                    )
                ),
                on_delete=django.db.models.deletion.PROTECT,
                to="traffic_control.TrafficControlDeviceType",
                verbose_name="Device Type",
            ),
        ),
        migrations.AlterField(
            model_name="roadmarkingreal",
            name="device_type",
            field=models.ForeignKey(
                limit_choices_to=models.Q(
                    models.Q(
                        ("target_model", None),
                        (
                            "target_model",
                            traffic_control.enums.DeviceTypeTargetModel(
                                "road_marking"
                            ),
                        ),
                        _connector="OR",
                    )
                ),
                on_delete=django.db.models.deletion.PROTECT,
                to="traffic_control.TrafficControlDeviceType",
                verbose_name="Device type",
            ),
        ),
        migrations.AlterField(
            model_name="signpostplan",
            name="device_type",
            field=models.ForeignKey(
                limit_choices_to=models.Q(
                    models.Q(
                        ("target_model", None),
                        (
                            "target_model",
                            traffic_control.enums.DeviceTypeTargetModel(
                                "signpost"
                            ),
                        ),
                        _connector="OR",
                    )
                ),
                on_delete=django.db.models.deletion.PROTECT,
                to="traffic_control.TrafficControlDeviceType",
                verbose_name="Device type",
            ),
        ),
        migrations.AlterField(
            model_name="signpostreal",
            name="device_type",
            field=models.ForeignKey(
                limit_choices_to=models.Q(
                    models.Q(
                        ("target_model", None),
                        (
                            "target_model",
                            traffic_control.enums.DeviceTypeTargetModel(
                                "signpost"
                            ),
                        ),
                        _connector="OR",
                    )
                ),
                on_delete=django.db.models.deletion.PROTECT,
                to="traffic_control.TrafficControlDeviceType",
                verbose_name="Device type",
            ),
        ),
        migrations.AlterField(
            model_name="trafficlightplan",
            name="device_type",
            field=models.ForeignKey(
                limit_choices_to=models.Q(
                    models.Q(
                        ("target_model", None),
                        (
                            "target_model",
                            traffic_control.enums.DeviceTypeTargetModel(
                                "traffic_light"
                            ),
                        ),
                        _connector="OR",
                    )
                ),
                on_delete=django.db.models.deletion.PROTECT,
                to="traffic_control.TrafficControlDeviceType",
                verbose_name="Device type",
            ),
        ),
        migrations.AlterField(
            model_name="trafficlightreal",
            name="device_type",
            field=models.ForeignKey(
                limit_choices_to=models.Q(
                    models.Q(
                        ("target_model", None),
                        (
                            "target_model",
                            traffic_control.enums.DeviceTypeTargetModel(
                                "traffic_light"
                            ),
                        ),
                        _connector="OR",
                    )
                ),
                on_delete=django.db.models.deletion.PROTECT,
                to="traffic_control.TrafficControlDeviceType",
                verbose_name="Device type",
            ),
        ),
        migrations.AlterField(
            model_name="trafficsignplan",
            name="device_type",
            field=models.ForeignKey(
                limit_choices_to=models.Q(
                    models.Q(
                        ("target_model", None),
                        (
                            "target_model",
                            traffic_control.enums.DeviceTypeTargetModel(
                                "traffic_sign"
                            ),
                        ),
                        _connector="OR",
                    )
                ),
                on_delete=django.db.models.deletion.PROTECT,
                to="traffic_control.TrafficControlDeviceType",
                verbose_name="Device type",
            ),
        ),
        migrations.AlterField(
            model_name="trafficsignreal",
            name="device_type",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to=models.Q(
                    models.Q(
                        ("target_model", None),
                        (
                            "target_model",
                            traffic_control.enums.DeviceTypeTargetModel(
                                "traffic_sign"
                            ),
                        ),
                        _connector="OR",
                    )
                ),
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="traffic_control.TrafficControlDeviceType",
                verbose_name="Device type",
            ),
        ),
    ]
