# Generated by Django 2.2.10 on 2020-03-23 09:52

from django.db import migrations
import enumfields.fields
import traffic_control.models.mount


class Migration(migrations.Migration):

    dependencies = [
        ("traffic_control", "0004_change_traffic_sign_locations_to_3d"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mountplan",
            name="type",
            field=enumfields.fields.EnumField(
                default="PORTAL",
                enum=traffic_control.models.mount.MountType,
                max_length=20,
                verbose_name="Mount type",
            ),
        ),
        migrations.AlterField(
            model_name="mountreal",
            name="type",
            field=enumfields.fields.EnumField(
                default="PORTAL",
                enum=traffic_control.models.mount.MountType,
                max_length=20,
                verbose_name="Mount type",
            ),
        ),
        migrations.AlterField(
            model_name="signpostplan",
            name="mount_type",
            field=enumfields.fields.EnumField(
                blank=True,
                default="OTHER",
                enum=traffic_control.models.mount.MountType,
                max_length=20,
                null=True,
                verbose_name="Mount type",
            ),
        ),
        migrations.AlterField(
            model_name="signpostreal",
            name="mount_type",
            field=enumfields.fields.EnumField(
                blank=True,
                default="OTHER",
                enum=traffic_control.models.mount.MountType,
                max_length=20,
                null=True,
                verbose_name="Mount type",
            ),
        ),
        migrations.AlterField(
            model_name="trafficlightplan",
            name="mount_type",
            field=enumfields.fields.EnumField(
                blank=True,
                default="POST",
                enum=traffic_control.models.mount.MountType,
                max_length=20,
                null=True,
                verbose_name="Mount type",
            ),
        ),
        migrations.AlterField(
            model_name="trafficlightreal",
            name="mount_type",
            field=enumfields.fields.EnumField(
                blank=True,
                default="POST",
                enum=traffic_control.models.mount.MountType,
                max_length=20,
                null=True,
                verbose_name="Mount type",
            ),
        ),
    ]
