# Generated by Django 2.2.13 on 2020-06-22 09:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("traffic_control", "0006_remove_has_rumble_strips"),
    ]

    operations = [
        migrations.RemoveField(model_name="trafficsignplan", name="parent"),
        migrations.RemoveField(model_name="trafficsignreal", name="parent"),
    ]
