# Generated by Django 2.2.10 on 2020-03-24 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("traffic_control", "0005_add_missing_mount_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trafficsignplan",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="traffic_control.TrafficSignPlan",
                verbose_name="Parent Traffic Sign Plan",
            ),
        ),
        migrations.AlterField(
            model_name="trafficsignreal",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="traffic_control.TrafficSignReal",
                verbose_name="Parent Traffic Sign Real",
            ),
        ),
    ]
