# Generated by Django 2.2.10 on 2020-03-23 17:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("traffic_control", "0006_add_children_related_name"),
    ]

    operations = [
        migrations.RemoveField(model_name="barrierplan", name="plan_document",),
        migrations.RemoveField(model_name="mountplan", name="plan_document",),
        migrations.RemoveField(model_name="roadmarkingplan", name="plan_document",),
        migrations.RemoveField(model_name="signpostplan", name="plan_document",),
        migrations.RemoveField(model_name="trafficlightplan", name="plan_document",),
        migrations.RemoveField(model_name="trafficsignplan", name="plan_document",),
        migrations.CreateModel(
            name="TrafficSignPlanFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="planfiles/traffic_sign/", verbose_name="File"
                    ),
                ),
                (
                    "traffic_sign_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="traffic_control.TrafficSignPlan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Traffic Sign Plan File",
                "verbose_name_plural": "Traffic Sign Plan Files",
                "db_table": "traffic_sign_plan_file",
            },
        ),
        migrations.CreateModel(
            name="TrafficLightPlanFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="planfiles/traffic_light/", verbose_name="File"
                    ),
                ),
                (
                    "traffic_light_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="traffic_control.TrafficLightPlan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Traffic Light Plan File",
                "verbose_name_plural": "Traffic Light Plan Files",
                "db_table": "traffic_light_plan_file",
            },
        ),
        migrations.CreateModel(
            name="SignpostPlanFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="planfiles/signpost/", verbose_name="File"
                    ),
                ),
                (
                    "signpost_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="traffic_control.SignpostPlan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Signpost Plan File",
                "verbose_name_plural": "Signpost Plan Files",
                "db_table": "signpost_plan_file",
            },
        ),
        migrations.CreateModel(
            name="RoadMarkingPlanFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="planfiles/road_marking/", verbose_name="File"
                    ),
                ),
                (
                    "road_marking_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="traffic_control.RoadMarkingPlan",
                    ),
                ),
            ],
            options={
                "verbose_name": "RoadMarking Plan File",
                "verbose_name_plural": "RoadMarking Plan Files",
                "db_table": "road_marking_plan_file",
            },
        ),
        migrations.CreateModel(
            name="MountPlanFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to="planfiles/mount/", verbose_name="File"),
                ),
                (
                    "mount_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="traffic_control.MountPlan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mount Plan File",
                "verbose_name_plural": "Mount Plan Files",
                "db_table": "mount_plan_file",
            },
        ),
        migrations.CreateModel(
            name="BarrierPlanFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="planfiles/barrier/", verbose_name="File"
                    ),
                ),
                (
                    "barrier_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="traffic_control.BarrierPlan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Barrier Plan File",
                "verbose_name_plural": "Barrier Plan Files",
                "db_table": "barrier_plan_file",
            },
        ),
    ]
