# Generated by Django 2.2.10 on 2020-03-26 16:11

from django.db import migrations, models
import enumfields.fields
import traffic_control.models.common
import traffic_control.models.traffic_sign


class Migration(migrations.Migration):

    dependencies = [
        ("traffic_control", "0007_add_plan_file_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="trafficsignreal",
            name="attachment_url",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="Attachment url"
            ),
        ),
        migrations.AddField(
            model_name="trafficsignreal",
            name="operation",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="Operation"
            ),
        ),
        migrations.AlterField(
            model_name="trafficsignreal",
            name="color",
            field=enumfields.fields.EnumIntegerField(
                blank=True,
                enum=traffic_control.models.common.Color,
                null=True,
                verbose_name="Color",
            ),
        ),
        migrations.AlterField(
            model_name="trafficsignreal",
            name="condition",
            field=enumfields.fields.EnumIntegerField(
                blank=True,
                enum=traffic_control.models.common.Condition,
                null=True,
                verbose_name="Condition",
            ),
        ),
        migrations.AlterField(
            model_name="trafficsignreal",
            name="installation_status",
            field=enumfields.fields.EnumField(
                blank=True,
                enum=traffic_control.models.common.InstallationStatus,
                max_length=10,
                null=True,
                verbose_name="Installation status",
            ),
        ),
        migrations.AlterField(
            model_name="trafficsignreal",
            name="location_specifier",
            field=enumfields.fields.EnumIntegerField(
                blank=True,
                enum=traffic_control.models.traffic_sign.LocationSpecifier,
                null=True,
                verbose_name="Location specifier",
            ),
        ),
        migrations.AlterField(
            model_name="trafficsignreal",
            name="reflection_class",
            field=enumfields.fields.EnumField(
                blank=True,
                enum=traffic_control.models.common.Reflection,
                max_length=2,
                null=True,
                verbose_name="Reflection",
            ),
        ),
        migrations.AlterField(
            model_name="trafficsignreal",
            name="size",
            field=enumfields.fields.EnumField(
                blank=True,
                enum=traffic_control.models.common.Size,
                max_length=1,
                null=True,
                verbose_name="Size",
            ),
        ),
        migrations.AlterField(
            model_name="trafficsignreal",
            name="surface_class",
            field=enumfields.fields.EnumField(
                blank=True,
                enum=traffic_control.models.common.Surface,
                max_length=6,
                null=True,
                verbose_name="Surface",
            ),
        ),
    ]
