# Generated by Django 2.2.13 on 2020-07-02 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traffic_control", "0008_additional_signs"),
    ]

    operations = [
        migrations.AddField(
            model_name="roadmarkingplan",
            name="source_id",
            field=models.IntegerField(blank=True, null=True, verbose_name="Source id"),
        ),
        migrations.AddField(
            model_name="roadmarkingplan",
            name="source_name",
            field=models.CharField(
                blank=True, max_length=254, verbose_name="Source name"
            ),
        ),
        migrations.AddField(
            model_name="roadmarkingreal",
            name="source_id",
            field=models.IntegerField(blank=True, null=True, verbose_name="Source id"),
        ),
        migrations.AddField(
            model_name="roadmarkingreal",
            name="source_name",
            field=models.CharField(
                blank=True, max_length=254, verbose_name="Source name"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="roadmarkingplan", unique_together={("source_name", "source_id")},
        ),
        migrations.AlterUniqueTogether(
            name="roadmarkingreal", unique_together={("source_name", "source_id")},
        ),
    ]
