# Generated by Django 2.2.13 on 2020-07-03 12:46

import django.contrib.gis.db.models.fields
import enumfields.fields
from django.db import migrations, models

import traffic_control.models.common


class Migration(migrations.Migration):

    dependencies = [
        ("traffic_control", "0010_traffic_sign_updates"),
    ]

    operations = [
        migrations.RemoveField(model_name="additionalsignreal", name="decision_date",),
        migrations.RemoveField(model_name="additionalsignreal", name="decision_id",),
        migrations.AddField(
            model_name="additionalsignplan",
            name="direction",
            field=models.IntegerField(default=0, verbose_name="Direction"),
        ),
        migrations.AddField(
            model_name="additionalsignplan",
            name="height",
            field=models.IntegerField(blank=True, null=True, verbose_name="Height"),
        ),
        migrations.AddField(
            model_name="additionalsignplan",
            name="installation_details",
            field=models.CharField(
                blank=True,
                max_length=254,
                null=True,
                verbose_name="Installation details",
            ),
        ),
        migrations.AddField(
            model_name="additionalsignplan",
            name="source_id",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="Source id"
            ),
        ),
        migrations.AddField(
            model_name="additionalsignplan",
            name="source_name",
            field=models.CharField(
                blank=True, max_length=254, null=True, verbose_name="Source name"
            ),
        ),
        migrations.AddField(
            model_name="additionalsignreal",
            name="attachment_url",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="Attachment url"
            ),
        ),
        migrations.AddField(
            model_name="additionalsignreal",
            name="direction",
            field=models.IntegerField(default=0, verbose_name="Direction"),
        ),
        migrations.AddField(
            model_name="additionalsignreal",
            name="height",
            field=models.IntegerField(blank=True, null=True, verbose_name="Height"),
        ),
        migrations.AddField(
            model_name="additionalsignreal",
            name="installation_details",
            field=models.CharField(
                blank=True,
                max_length=254,
                null=True,
                verbose_name="Installation details",
            ),
        ),
        migrations.AddField(
            model_name="additionalsignreal",
            name="legacy_code",
            field=models.CharField(
                blank=True,
                max_length=32,
                null=True,
                verbose_name="Legacy Traffic Sign Code",
            ),
        ),
        migrations.AddField(
            model_name="additionalsignreal",
            name="operation",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="Operation"
            ),
        ),
        migrations.AddField(
            model_name="additionalsignreal",
            name="permit_decision_id",
            field=models.CharField(
                blank=True, max_length=254, null=True, verbose_name="Decision id (Allu)"
            ),
        ),
        migrations.AddField(
            model_name="additionalsignreal",
            name="scanned_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Scanned at"
            ),
        ),
        migrations.AddField(
            model_name="additionalsignreal",
            name="size",
            field=enumfields.fields.EnumField(
                blank=True,
                enum=traffic_control.models.common.Size,
                max_length=1,
                null=True,
                verbose_name="Size",
            ),
        ),
        migrations.AddField(
            model_name="additionalsignreal",
            name="source_id",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="Source id"
            ),
        ),
        migrations.AddField(
            model_name="additionalsignreal",
            name="source_name",
            field=models.CharField(
                blank=True, max_length=254, null=True, verbose_name="Source name"
            ),
        ),
        migrations.AlterField(
            model_name="additionalsignplan",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                dim=3, srid=3879, verbose_name="Location (3D)"
            ),
        ),
        migrations.AlterField(
            model_name="additionalsignreal",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                dim=3, srid=3879, verbose_name="Location (3D)"
            ),
        ),
    ]
