# Generated by Django 2.2.12 on 2020-05-22 11:54

from django.db import migrations
import enumfields.fields
import traffic_control.models.common


class Migration(migrations.Migration):

    dependencies = [
        ("traffic_control", "0011_plan_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="barrierplan",
            name="lane_number",
            field=enumfields.fields.EnumField(
                blank=True,
                default="11",
                enum=traffic_control.models.common.LaneNumber,
                max_length=10,
                verbose_name="Lane number",
            ),
        ),
        migrations.AlterField(
            model_name="barrierplan",
            name="lane_type",
            field=enumfields.fields.EnumField(
                blank=True,
                default=1,
                enum=traffic_control.models.common.LaneType,
                max_length=10,
                verbose_name="Lane type",
            ),
        ),
        migrations.AlterField(
            model_name="barrierreal",
            name="lane_number",
            field=enumfields.fields.EnumField(
                blank=True,
                default="11",
                enum=traffic_control.models.common.LaneNumber,
                max_length=10,
                verbose_name="Lane number",
            ),
        ),
        migrations.AlterField(
            model_name="barrierreal",
            name="lane_type",
            field=enumfields.fields.EnumField(
                blank=True,
                default=1,
                enum=traffic_control.models.common.LaneType,
                max_length=10,
                verbose_name="Lane type",
            ),
        ),
        migrations.AlterField(
            model_name="roadmarkingplan",
            name="lane_number",
            field=enumfields.fields.EnumField(
                blank=True,
                default="11",
                enum=traffic_control.models.common.LaneNumber,
                max_length=10,
                verbose_name="Lane number",
            ),
        ),
        migrations.AlterField(
            model_name="roadmarkingplan",
            name="lane_type",
            field=enumfields.fields.EnumField(
                blank=True,
                default=1,
                enum=traffic_control.models.common.LaneType,
                max_length=10,
                verbose_name="Lane type",
            ),
        ),
        migrations.AlterField(
            model_name="roadmarkingreal",
            name="lane_number",
            field=enumfields.fields.EnumField(
                blank=True,
                default="11",
                enum=traffic_control.models.common.LaneNumber,
                max_length=10,
                verbose_name="Lane number",
            ),
        ),
        migrations.AlterField(
            model_name="roadmarkingreal",
            name="lane_type",
            field=enumfields.fields.EnumField(
                blank=True,
                default=1,
                enum=traffic_control.models.common.LaneType,
                max_length=10,
                verbose_name="Lane type",
            ),
        ),
        migrations.AlterField(
            model_name="signpostplan",
            name="lane_number",
            field=enumfields.fields.EnumField(
                blank=True,
                default="11",
                enum=traffic_control.models.common.LaneNumber,
                max_length=10,
                verbose_name="Lane number",
            ),
        ),
        migrations.AlterField(
            model_name="signpostplan",
            name="lane_type",
            field=enumfields.fields.EnumField(
                blank=True,
                default=1,
                enum=traffic_control.models.common.LaneType,
                max_length=10,
                verbose_name="Lane type",
            ),
        ),
        migrations.AlterField(
            model_name="signpostreal",
            name="lane_number",
            field=enumfields.fields.EnumField(
                blank=True,
                default="11",
                enum=traffic_control.models.common.LaneNumber,
                max_length=10,
                verbose_name="Lane number",
            ),
        ),
        migrations.AlterField(
            model_name="signpostreal",
            name="lane_type",
            field=enumfields.fields.EnumField(
                blank=True,
                default=1,
                enum=traffic_control.models.common.LaneType,
                max_length=10,
                verbose_name="Lane type",
            ),
        ),
        migrations.AlterField(
            model_name="trafficlightplan",
            name="lane_number",
            field=enumfields.fields.EnumField(
                blank=True,
                default="11",
                enum=traffic_control.models.common.LaneNumber,
                max_length=10,
                verbose_name="Lane number",
            ),
        ),
        migrations.AlterField(
            model_name="trafficlightplan",
            name="lane_type",
            field=enumfields.fields.EnumField(
                blank=True,
                default=1,
                enum=traffic_control.models.common.LaneType,
                max_length=10,
                verbose_name="Lane type",
            ),
        ),
        migrations.AlterField(
            model_name="trafficlightreal",
            name="lane_number",
            field=enumfields.fields.EnumField(
                blank=True,
                default="11",
                enum=traffic_control.models.common.LaneNumber,
                max_length=10,
                verbose_name="Lane number",
            ),
        ),
        migrations.AlterField(
            model_name="trafficlightreal",
            name="lane_type",
            field=enumfields.fields.EnumField(
                blank=True,
                default=1,
                enum=traffic_control.models.common.LaneType,
                max_length=10,
                verbose_name="Lane type",
            ),
        ),
        migrations.AlterField(
            model_name="trafficsignplan",
            name="lane_number",
            field=enumfields.fields.EnumField(
                blank=True,
                default="11",
                enum=traffic_control.models.common.LaneNumber,
                max_length=10,
                verbose_name="Lane number",
            ),
        ),
        migrations.AlterField(
            model_name="trafficsignplan",
            name="lane_type",
            field=enumfields.fields.EnumField(
                blank=True,
                default=1,
                enum=traffic_control.models.common.LaneType,
                max_length=10,
                verbose_name="Lane type",
            ),
        ),
        migrations.AlterField(
            model_name="trafficsignreal",
            name="lane_number",
            field=enumfields.fields.EnumField(
                blank=True,
                default="11",
                enum=traffic_control.models.common.LaneNumber,
                max_length=10,
                verbose_name="Lane number",
            ),
        ),
        migrations.AlterField(
            model_name="trafficsignreal",
            name="lane_type",
            field=enumfields.fields.EnumField(
                blank=True,
                default=1,
                enum=traffic_control.models.common.LaneType,
                max_length=10,
                verbose_name="Lane type",
            ),
        ),
    ]
