# Generated by Django 2.2.14 on 2020-07-06 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traffic_control", "0013_additional_sign_device_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="additionalsignreal",
            name="permit_decision_id",
            field=models.CharField(
                blank=True, max_length=254, null=True, verbose_name="Permit decision id"
            ),
        ),
        migrations.AlterField(
            model_name="trafficsignreal",
            name="permit_decision_id",
            field=models.CharField(
                blank=True, max_length=254, null=True, verbose_name="Permit decision id"
            ),
        ),
    ]
