# Generated by Django 2.2.12 on 2020-05-27 07:13

from django.db import migrations


def create_mount_type_instances(apps, schema_editor):
    MountType = apps.get_model("traffic_control", "MountType")

    mount_types = [
        "portal",
        "post",
        "wall",
        "wire",
        "bridge",
        "other",
        "lightpole",
        "pole",
        "trafficlight",
    ]

    for mount_type in mount_types:
        MountType.objects.create(
            code=mount_type.upper(), description=mount_type.capitalize()
        )


def set_mount_type_for_model(apps, model_name, field):
    MountType = apps.get_model("traffic_control", "MountType")
    ModelClass = apps.get_model("traffic_control", model_name)

    old_field = f"_{field}"
    new_field = field

    for mount_type in ModelClass.objects.values_list(old_field, flat=True).distinct():
        if not mount_type:
            continue

        ModelClass.objects.filter(**{old_field: mount_type}).update(
            **{new_field: MountType.objects.filter(code=mount_type.upper()).first()}
        )


def set_mount_plan_mount_types(apps, schema_editor):
    set_mount_type_for_model(apps, "MountPlan", "type")


def set_mount_real_mount_types(apps, schema_editor):
    set_mount_type_for_model(apps, "MountReal", "type")


def set_signpost_plan_mount_types(apps, schema_editor):
    set_mount_type_for_model(apps, "SignpostPlan", "mount_type")


def set_signpost_real_mount_types(apps, schema_editor):
    set_mount_type_for_model(apps, "SignpostReal", "mount_type")


def set_traffic_light_plan_mount_types(apps, schema_editor):
    set_mount_type_for_model(apps, "TrafficLightPlan", "mount_type")


def set_traffic_light_real_mount_types(apps, schema_editor):
    set_mount_type_for_model(apps, "TrafficLightReal", "mount_type")


class Migration(migrations.Migration):

    dependencies = [
        ("traffic_control", "0014_mount_type_model"),
    ]

    operations = [
        migrations.RunPython(create_mount_type_instances, migrations.RunPython.noop),
        migrations.RunPython(set_mount_plan_mount_types, migrations.RunPython.noop),
        migrations.RunPython(set_mount_real_mount_types, migrations.RunPython.noop),
        migrations.RunPython(set_signpost_plan_mount_types, migrations.RunPython.noop),
        migrations.RunPython(set_signpost_real_mount_types, migrations.RunPython.noop),
        migrations.RunPython(
            set_traffic_light_plan_mount_types, migrations.RunPython.noop
        ),
        migrations.RunPython(
            set_traffic_light_real_mount_types, migrations.RunPython.noop
        ),
    ]
