# Generated by Django 2.2.14 on 2020-07-15 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("traffic_control", "0014_update_permit_decision_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="additionalsignplan",
            name="installation_date",
        ),
        migrations.RemoveField(
            model_name="additionalsignplan",
            name="installation_details",
        ),
        migrations.RemoveField(
            model_name="additionalsignplan",
            name="installation_id",
        ),
        migrations.RemoveField(
            model_name="additionalsignplan",
            name="installation_status",
        ),
        migrations.RemoveField(
            model_name="additionalsignplan",
            name="installed_by",
        ),
    ]
