# Generated by Django 2.2.12 on 2020-05-27 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("traffic_control", "0015_set_mount_type_relations"),
    ]

    operations = [
        migrations.RemoveField(model_name="mountplan", name="_type",),
        migrations.RemoveField(model_name="mountreal", name="_type",),
        migrations.RemoveField(model_name="signpostplan", name="_mount_type",),
        migrations.RemoveField(model_name="signpostreal", name="_mount_type",),
        migrations.RemoveField(model_name="trafficlightplan", name="_mount_type",),
        migrations.RemoveField(model_name="trafficlightreal", name="_mount_type",),
        migrations.RemoveField(model_name="trafficsignplan", name="_mount_type",),
        migrations.RemoveField(model_name="trafficsignplan", name="_mount_type_fi",),
        migrations.RemoveField(model_name="trafficsignreal", name="_mount_type",),
        migrations.RemoveField(model_name="trafficsignreal", name="_mount_type_fi",),
    ]
