# Generated by Django 2.2.14 on 2020-07-17 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traffic_control", "0015_remove_additional_sign_plan_installation_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="mounttype",
            name="description_fi",
            field=models.CharField(
                blank=True, max_length=256, verbose_name="Description (fi)"
            ),
        ),
    ]
