# Generated by Django 2.2.14 on 2020-08-31 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("traffic_control", "0018_plan_location_allow_null"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trafficsignplan",
            name="color",
        ),
        migrations.RemoveField(
            model_name="trafficsignreal",
            name="color",
        ),
    ]
