# Generated by Django 2.2.12 on 2020-06-05 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("traffic_control", "0018_plan_user_relation_on_delete"),
    ]

    operations = [
        migrations.RemoveField(model_name="signpostplan", name="order",),
        migrations.RemoveField(model_name="signpostreal", name="order",),
        migrations.RemoveField(model_name="trafficsignplan", name="order",),
        migrations.RemoveField(model_name="trafficsignreal", name="order",),
    ]
