# Generated by Django 2.2.14 on 2020-08-31 12:34

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traffic_control", "0020_add_source_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="Owner",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name_fi", models.CharField(max_length=254, verbose_name="Name (fi)")),
                ("name_en", models.CharField(max_length=254, verbose_name="Name (en)")),
            ],
            options={
                "verbose_name": "Owner",
                "verbose_name_plural": "Owners",
            },
        ),
        migrations.AddField(
            model_name="additionalsignplan",
            name="owner_obj",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="traffic_control.Owner",
                verbose_name="Owner",
            ),
        ),
        migrations.AddField(
            model_name="additionalsignreal",
            name="owner_obj",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="traffic_control.Owner",
                verbose_name="Owner",
            ),
        ),
        migrations.AddField(
            model_name="barrierplan",
            name="owner_obj",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="traffic_control.Owner",
                verbose_name="Owner",
            ),
        ),
        migrations.AddField(
            model_name="barrierreal",
            name="owner_obj",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="traffic_control.Owner",
                verbose_name="Owner",
            ),
        ),
        migrations.AddField(
            model_name="mountplan",
            name="owner_obj",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="traffic_control.Owner",
                verbose_name="Owner",
            ),
        ),
        migrations.AddField(
            model_name="mountreal",
            name="owner_obj",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="traffic_control.Owner",
                verbose_name="Owner",
            ),
        ),
        migrations.AddField(
            model_name="roadmarkingplan",
            name="owner_obj",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="traffic_control.Owner",
                verbose_name="Owner",
            ),
        ),
        migrations.AddField(
            model_name="roadmarkingreal",
            name="owner_obj",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="traffic_control.Owner",
                verbose_name="Owner",
            ),
        ),
        migrations.AddField(
            model_name="signpostplan",
            name="owner_obj",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="traffic_control.Owner",
                verbose_name="Owner",
            ),
        ),
        migrations.AddField(
            model_name="signpostreal",
            name="owner_obj",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="traffic_control.Owner",
                verbose_name="Owner",
            ),
        ),
        migrations.AddField(
            model_name="trafficlightplan",
            name="owner_obj",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="traffic_control.Owner",
                verbose_name="Owner",
            ),
        ),
        migrations.AddField(
            model_name="trafficlightreal",
            name="owner_obj",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="traffic_control.Owner",
                verbose_name="Owner",
            ),
        ),
        migrations.AddField(
            model_name="trafficsignplan",
            name="owner_obj",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="traffic_control.Owner",
                verbose_name="Owner",
            ),
        ),
        migrations.AddField(
            model_name="trafficsignreal",
            name="owner_obj",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="traffic_control.Owner",
                verbose_name="Owner",
            ),
        ),
    ]
