# Generated by Django 2.2.14 on 2020-09-02 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traffic_control", "0022_initial_owners"),
    ]

    operations = [
        migrations.RemoveField(model_name="additionalsignplan", name="owner",),
        migrations.RemoveField(model_name="additionalsignreal", name="owner",),
        migrations.RemoveField(model_name="barrierplan", name="owner",),
        migrations.RemoveField(model_name="barrierreal", name="owner",),
        migrations.RemoveField(model_name="mountplan", name="owner",),
        migrations.RemoveField(model_name="mountreal", name="owner",),
        migrations.RemoveField(model_name="roadmarkingplan", name="owner",),
        migrations.RemoveField(model_name="roadmarkingreal", name="owner",),
        migrations.RemoveField(model_name="signpostplan", name="owner",),
        migrations.RemoveField(model_name="signpostreal", name="owner",),
        migrations.RemoveField(model_name="trafficlightplan", name="owner",),
        migrations.RemoveField(model_name="trafficlightreal", name="owner",),
        migrations.RemoveField(model_name="trafficsignplan", name="owner",),
        migrations.RemoveField(model_name="trafficsignreal", name="owner",),
        migrations.AlterField(
            model_name="additionalsignplan",
            name="owner_obj",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="traffic_control.Owner",
                verbose_name="Owner",
            ),
        ),
        migrations.AlterField(
            model_name="additionalsignreal",
            name="owner_obj",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="traffic_control.Owner",
                verbose_name="Owner",
            ),
        ),
        migrations.AlterField(
            model_name="barrierplan",
            name="owner_obj",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="traffic_control.Owner",
                verbose_name="Owner",
            ),
        ),
        migrations.AlterField(
            model_name="barrierreal",
            name="owner_obj",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="traffic_control.Owner",
                verbose_name="Owner",
            ),
        ),
        migrations.AlterField(
            model_name="mountplan",
            name="owner_obj",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="traffic_control.Owner",
                verbose_name="Owner",
            ),
        ),
        migrations.AlterField(
            model_name="mountreal",
            name="owner_obj",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="traffic_control.Owner",
                verbose_name="Owner",
            ),
        ),
        migrations.AlterField(
            model_name="roadmarkingplan",
            name="owner_obj",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="traffic_control.Owner",
                verbose_name="Owner",
            ),
        ),
        migrations.AlterField(
            model_name="roadmarkingreal",
            name="owner_obj",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="traffic_control.Owner",
                verbose_name="Owner",
            ),
        ),
        migrations.AlterField(
            model_name="signpostplan",
            name="owner_obj",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="traffic_control.Owner",
                verbose_name="Owner",
            ),
        ),
        migrations.AlterField(
            model_name="signpostreal",
            name="owner_obj",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="traffic_control.Owner",
                verbose_name="Owner",
            ),
        ),
        migrations.AlterField(
            model_name="trafficlightplan",
            name="owner_obj",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="traffic_control.Owner",
                verbose_name="Owner",
            ),
        ),
        migrations.AlterField(
            model_name="trafficlightreal",
            name="owner_obj",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="traffic_control.Owner",
                verbose_name="Owner",
            ),
        ),
        migrations.AlterField(
            model_name="trafficsignplan",
            name="owner_obj",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="traffic_control.Owner",
                verbose_name="Owner",
            ),
        ),
        migrations.AlterField(
            model_name="trafficsignreal",
            name="owner_obj",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="traffic_control.Owner",
                verbose_name="Owner",
            ),
        ),
    ]
