# Generated by Django 2.2.14 on 2020-09-02 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("traffic_control", "0023_remove_owner_char_fields"),
    ]

    operations = [
        migrations.RenameField(
            model_name="additionalsignplan", old_name="owner_obj", new_name="owner",
        ),
        migrations.RenameField(
            model_name="additionalsignreal", old_name="owner_obj", new_name="owner",
        ),
        migrations.RenameField(
            model_name="barrierplan", old_name="owner_obj", new_name="owner",
        ),
        migrations.RenameField(
            model_name="barrierreal", old_name="owner_obj", new_name="owner",
        ),
        migrations.RenameField(
            model_name="mountplan", old_name="owner_obj", new_name="owner",
        ),
        migrations.RenameField(
            model_name="mountreal", old_name="owner_obj", new_name="owner",
        ),
        migrations.RenameField(
            model_name="roadmarkingplan", old_name="owner_obj", new_name="owner",
        ),
        migrations.RenameField(
            model_name="roadmarkingreal", old_name="owner_obj", new_name="owner",
        ),
        migrations.RenameField(
            model_name="signpostplan", old_name="owner_obj", new_name="owner",
        ),
        migrations.RenameField(
            model_name="signpostreal", old_name="owner_obj", new_name="owner",
        ),
        migrations.RenameField(
            model_name="trafficlightplan", old_name="owner_obj", new_name="owner",
        ),
        migrations.RenameField(
            model_name="trafficlightreal", old_name="owner_obj", new_name="owner",
        ),
        migrations.RenameField(
            model_name="trafficsignplan", old_name="owner_obj", new_name="owner",
        ),
        migrations.RenameField(
            model_name="trafficsignreal", old_name="owner_obj", new_name="owner",
        ),
    ]
