# Generated by Django 2.2.14 on 2020-09-04 11:06

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traffic_control", "0024_rename_owner_obj_fields"),
    ]

    operations = [
        migrations.RenameField(
            model_name="operationalarea", old_name="area", new_name="location"
        ),
        migrations.AlterField(
            model_name="operationalarea",
            name="location",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(
                srid=3879, verbose_name="Location (2D)"
            ),
        ),
        migrations.AddField(
            model_name="operationalarea",
            name="area_type",
            field=models.CharField(
                blank=True, max_length=256, verbose_name="Area type"
            ),
        ),
        migrations.AddField(
            model_name="operationalarea",
            name="contractor",
            field=models.CharField(
                blank=True, max_length=256, verbose_name="Contractor"
            ),
        ),
        migrations.AddField(
            model_name="operationalarea",
            name="end_date",
            field=models.DateField(blank=True, null=True, verbose_name="End date"),
        ),
        migrations.AddField(
            model_name="operationalarea",
            name="name_short",
            field=models.CharField(
                blank=True, max_length=256, verbose_name="Name short"
            ),
        ),
        migrations.AddField(
            model_name="operationalarea",
            name="start_date",
            field=models.DateField(blank=True, null=True, verbose_name="Start date"),
        ),
        migrations.AddField(
            model_name="operationalarea",
            name="status",
            field=models.CharField(blank=True, max_length=256, verbose_name="Status"),
        ),
        migrations.AddField(
            model_name="operationalarea",
            name="task",
            field=models.CharField(blank=True, max_length=256, verbose_name="Task"),
        ),
        migrations.AddField(
            model_name="operationalarea",
            name="updated_date",
            field=models.DateField(blank=True, null=True, verbose_name="Updated date"),
        ),
    ]
