# Generated by Django 2.2.16 on 2020-10-13 12:27

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traffic_control", "0026_additional_sign_content_ordering"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParkingAreaCategory",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "verbose_name": "parking area category",
                "verbose_name_plural": "parking area categories",
            },
        ),
        migrations.CreateModel(
            name="ParkingArea",
            fields=[
                (
                    "source_id",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=64,
                        null=True,
                        verbose_name="Source id",
                    ),
                ),
                (
                    "source_name",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=254,
                        null=True,
                        verbose_name="Source name",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "area_type",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="area type"
                    ),
                ),
                (
                    "season",
                    models.CharField(blank=True, max_length=100, verbose_name="season"),
                ),
                (
                    "resident_parking_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="resident parking id"
                    ),
                ),
                (
                    "place_position",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="position"
                    ),
                ),
                (
                    "validity",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="validity"
                    ),
                ),
                (
                    "duration",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="duration"
                    ),
                ),
                (
                    "surface_area",
                    models.FloatField(
                        blank=True, null=True, verbose_name="surface area"
                    ),
                ),
                (
                    "parking_slots",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="parking slots"
                    ),
                ),
                (
                    "additional_info",
                    models.TextField(blank=True, verbose_name="additional info"),
                ),
                (
                    "stopping_prohibited",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="stopping prohibited"
                    ),
                ),
                (
                    "updated_at",
                    models.DateField(blank=True, null=True, verbose_name="updated at"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="traffic_control.Owner",
                        verbose_name="owner",
                    ),
                ),
                (
                    "location",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        srid=3879, verbose_name="location"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="traffic_control.ParkingAreaCategory",
                        verbose_name="category",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
