# Generated by Django 2.2.16 on 2020-10-13 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traffic_control", "0027_parkingarea_parkingareacategory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="additionalsignplan",
            name="affect_area",
        ),
        migrations.RemoveField(
            model_name="additionalsignreal",
            name="affect_area",
        ),
        migrations.RemoveField(
            model_name="trafficsignreal",
            name="affect_area",
        ),
        migrations.AddField(
            model_name="additionalsignreal",
            name="parking_area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="traffic_control.ParkingArea",
                verbose_name="Parking area",
            ),
        ),
        migrations.AddField(
            model_name="trafficsignreal",
            name="parking_area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="traffic_control.ParkingArea",
                verbose_name="Parking area",
            ),
        ),
    ]
