# Generated by Django 2.2.16 on 2020-10-23 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traffic_control", "0028_traffic_sign_real_parking_area"),
    ]

    operations = [
        migrations.RenameField(
            model_name="plan",
            old_name="decision_maker",
            new_name="decision_maker_legacy",
        ),
        migrations.AlterField(
            model_name="plan",
            name="plan_number",
            field=models.CharField(
                help_text="Year and verdict section separated with a dash",
                max_length=16,
                verbose_name="Plan number",
            ),
        ),
    ]
