# Generated by Django 2.2.16 on 2020-10-23 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traffic_control", "0029_plan_decision_maker_legacy"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="decision_maker",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Decision maker"
            ),
        ),
    ]
