# Generated by Django 2.2.16 on 2020-10-23 06:38

from django.db import migrations


def get_user_full_name(user):
    full_name = "%s %s" % (user.first_name, user.last_name)
    return full_name.strip()


def migrate_decision_makers(apps, schema_editor):
    Plan = apps.get_model("traffic_control", "Plan")
    qs = Plan.objects.filter(decision_maker_legacy__isnull=False)
    for plan in qs:
        plan.decision_maker = get_user_full_name(plan.decision_maker_legacy)
        plan.save()


class Migration(migrations.Migration):

    dependencies = [
        ("traffic_control", "0030_plan_decision_maker"),
    ]

    operations = [
        migrations.RunPython(migrate_decision_makers, migrations.RunPython.noop)
    ]
