# Generated by Django 2.2.16 on 2020-10-26 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traffic_control", "0032_remove_plan_decision_maker_legacy"),
    ]

    operations = [
        migrations.AddField(
            model_name="additionalsigncontentplan",
            name="source_id",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=64,
                null=True,
                verbose_name="Source id",
            ),
        ),
        migrations.AddField(
            model_name="additionalsigncontentplan",
            name="source_name",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=254,
                null=True,
                verbose_name="Source name",
            ),
        ),
        migrations.AddField(
            model_name="additionalsigncontentreal",
            name="source_id",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=64,
                null=True,
                verbose_name="Source id",
            ),
        ),
        migrations.AddField(
            model_name="additionalsigncontentreal",
            name="source_name",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=254,
                null=True,
                verbose_name="Source name",
            ),
        ),
    ]
