# Generated by Django 2.2.16 on 2020-10-27 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("traffic_control", "0033_additional_sign_content_source"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="additionalsignplan",
            name="decision_date",
        ),
        migrations.RemoveField(
            model_name="additionalsignplan",
            name="decision_id",
        ),
        migrations.RemoveField(
            model_name="barrierplan",
            name="decision_date",
        ),
        migrations.RemoveField(
            model_name="barrierplan",
            name="decision_id",
        ),
        migrations.RemoveField(
            model_name="mountplan",
            name="decision_date",
        ),
        migrations.RemoveField(
            model_name="mountplan",
            name="decision_id",
        ),
        migrations.RemoveField(
            model_name="roadmarkingplan",
            name="decision_date",
        ),
        migrations.RemoveField(
            model_name="roadmarkingplan",
            name="decision_id",
        ),
        migrations.RemoveField(
            model_name="signpostplan",
            name="decision_date",
        ),
        migrations.RemoveField(
            model_name="signpostplan",
            name="decision_id",
        ),
        migrations.RemoveField(
            model_name="trafficlightplan",
            name="decision_date",
        ),
        migrations.RemoveField(
            model_name="trafficlightplan",
            name="decision_id",
        ),
        migrations.RemoveField(
            model_name="trafficsignplan",
            name="decision_date",
        ),
        migrations.RemoveField(
            model_name="trafficsignplan",
            name="decision_id",
        ),
    ]
