# Generated by Django 2.2.16 on 2020-11-04 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("traffic_control", "0034_remove_decision_date_decision_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="plan",
            old_name="planner",
            new_name="planner_legacy",
        ),
    ]
