# Generated by Django 2.2.16 on 2020-11-04 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traffic_control", "0035_rename_plan_planner_to_planner_legacy"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="planner",
            field=models.CharField(blank=True, max_length=200, verbose_name="Planner"),
        ),
    ]
