# Generated by Django 2.2.16 on 2020-11-04 07:48

from django.db import migrations


def get_user_display_name(user):
    full_name = f"{user.first_name} {user.last_name}".strip()
    return full_name if full_name else user.email


def migrate_planners(apps, schema_editor):
    Plan = apps.get_model("traffic_control", "Plan")
    qs = Plan.objects.filter(planner_legacy__isnull=False)
    for plan in qs:
        plan.planner = get_user_display_name(plan.planner_legacy)
        plan.save()


class Migration(migrations.Migration):

    dependencies = [
        ("traffic_control", "0036_plan_planner"),
    ]

    operations = [migrations.RunPython(migrate_planners, migrations.RunPython.noop)]
