# Generated by Django 2.2.16 on 2020-11-04 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("traffic_control", "0037_migrate_plan_planners"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plan",
            name="planner_legacy",
        ),
    ]
