# Generated by Django 2.2.16 on 2020-11-11 09:47

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("traffic_control", "0038_remove_plan_planner_legacy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="barrierplan",
            name="location",
            field=django.contrib.gis.db.models.fields.GeometryField(
                dim=3, srid=3879, verbose_name="Location (3D)"
            ),
        ),
        migrations.AlterField(
            model_name="barrierreal",
            name="location",
            field=django.contrib.gis.db.models.fields.GeometryField(
                dim=3, srid=3879, verbose_name="Location (3D)"
            ),
        ),
        migrations.AlterField(
            model_name="mountplan",
            name="location",
            field=django.contrib.gis.db.models.fields.GeometryField(
                dim=3, srid=3879, verbose_name="Location (3D)"
            ),
        ),
        migrations.AlterField(
            model_name="mountreal",
            name="location",
            field=django.contrib.gis.db.models.fields.GeometryField(
                dim=3, srid=3879, verbose_name="Location (3D)"
            ),
        ),
        migrations.AlterField(
            model_name="operationalarea",
            name="location",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(
                dim=3, srid=3879, verbose_name="Location (3D)"
            ),
        ),
        migrations.AlterField(
            model_name="parkingarea",
            name="location",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(
                dim=3, srid=3879, verbose_name="location (3D)"
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="location",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(
                blank=True, dim=3, null=True, srid=3879, verbose_name="Location (3D)"
            ),
        ),
        migrations.AlterField(
            model_name="roadmarkingplan",
            name="location",
            field=django.contrib.gis.db.models.fields.GeometryField(
                dim=3, srid=3879, verbose_name="Location (3D)"
            ),
        ),
        migrations.AlterField(
            model_name="roadmarkingreal",
            name="location",
            field=django.contrib.gis.db.models.fields.GeometryField(
                dim=3, srid=3879, verbose_name="Location (3D)"
            ),
        ),
        migrations.AlterField(
            model_name="signpostplan",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                dim=3, srid=3879, verbose_name="Location (3D)"
            ),
        ),
        migrations.AlterField(
            model_name="signpostreal",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                dim=3, srid=3879, verbose_name="Location (3D)"
            ),
        ),
        migrations.AlterField(
            model_name="trafficlightplan",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                dim=3, srid=3879, verbose_name="Location (3D)"
            ),
        ),
        migrations.AlterField(
            model_name="trafficlightreal",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                dim=3, srid=3879, verbose_name="Location (3D)"
            ),
        ),
    ]
