# Generated by Django 2.2.16 on 2020-11-23 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("traffic_control", "0040_traffic_control_operations"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ParkingArea",
            new_name="CoverageArea",
        ),
        migrations.RenameModel(
            old_name="ParkingAreaCategory",
            new_name="CoverageAreaCategory",
        ),
        migrations.RenameField(
            model_name="additionalsignreal",
            old_name="parking_area",
            new_name="coverage_area",
        ),
        migrations.RenameField(
            model_name="trafficsignreal",
            old_name="parking_area",
            new_name="coverage_area",
        ),
    ]
