# Generated by Django 2.2.16 on 2020-11-23 12:32

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traffic_control", "0041_rename_parking_area_to_coverage_area"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="coveragearea",
            options={
                "verbose_name": "Coverage area",
                "verbose_name_plural": "Coverage areas",
            },
        ),
        migrations.AlterModelOptions(
            name="coverageareacategory",
            options={
                "verbose_name": "Coverage area category",
                "verbose_name_plural": "Coverage area categories",
            },
        ),
        migrations.AlterField(
            model_name="additionalsignreal",
            name="coverage_area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="traffic_control.CoverageArea",
                verbose_name="Coverage area",
            ),
        ),
        migrations.AlterField(
            model_name="coveragearea",
            name="additional_info",
            field=models.TextField(blank=True, verbose_name="Additional info"),
        ),
        migrations.AlterField(
            model_name="coveragearea",
            name="area_type",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Area type"
            ),
        ),
        migrations.AlterField(
            model_name="coveragearea",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="traffic_control.CoverageAreaCategory",
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="coveragearea",
            name="duration",
            field=models.CharField(blank=True, max_length=100, verbose_name="Duration"),
        ),
        migrations.AlterField(
            model_name="coveragearea",
            name="location",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(
                dim=3, srid=3879, verbose_name="Location (3D)"
            ),
        ),
        migrations.AlterField(
            model_name="coveragearea",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="traffic_control.Owner",
                verbose_name="Owner",
            ),
        ),
        migrations.AlterField(
            model_name="coveragearea",
            name="parking_slots",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Parking slots"
            ),
        ),
        migrations.AlterField(
            model_name="coveragearea",
            name="place_position",
            field=models.CharField(blank=True, max_length=100, verbose_name="Position"),
        ),
        migrations.AlterField(
            model_name="coveragearea",
            name="resident_parking_id",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Resident parking id"
            ),
        ),
        migrations.AlterField(
            model_name="coveragearea",
            name="season",
            field=models.CharField(blank=True, max_length=100, verbose_name="Season"),
        ),
        migrations.AlterField(
            model_name="coveragearea",
            name="stopping_prohibited",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Stopping prohibited"
            ),
        ),
        migrations.AlterField(
            model_name="coveragearea",
            name="surface_area",
            field=models.FloatField(blank=True, null=True, verbose_name="Surface area"),
        ),
        migrations.AlterField(
            model_name="coveragearea",
            name="updated_at",
            field=models.DateField(blank=True, null=True, verbose_name="Updated at"),
        ),
        migrations.AlterField(
            model_name="coveragearea",
            name="validity",
            field=models.CharField(blank=True, max_length=100, verbose_name="Validity"),
        ),
        migrations.AlterField(
            model_name="trafficsignreal",
            name="coverage_area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="traffic_control.CoverageArea",
                verbose_name="Coverage area",
            ),
        ),
    ]
