# Generated by Django 2.2.16 on 2020-11-23 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traffic_control", "0042_update_coverage_area_verbose_names"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="operationtype",
            options={
                "verbose_name": "Operation type",
                "verbose_name_plural": "Operation types",
            },
        ),
        migrations.AlterField(
            model_name="additionalsignrealoperation",
            name="operation_date",
            field=models.DateField(verbose_name="Operation date"),
        ),
        migrations.AlterField(
            model_name="additionalsignrealoperation",
            name="quality_requirements_fulfilled",
            field=models.BooleanField(
                default=False, verbose_name="Quality requirements fulfilled"
            ),
        ),
        migrations.AlterField(
            model_name="additionalsignrealoperation",
            name="straightness_value",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Straightness value"
            ),
        ),
        migrations.AlterField(
            model_name="barrierrealoperation",
            name="operation_date",
            field=models.DateField(verbose_name="Operation date"),
        ),
        migrations.AlterField(
            model_name="barrierrealoperation",
            name="quality_requirements_fulfilled",
            field=models.BooleanField(
                default=False, verbose_name="Quality requirements fulfilled"
            ),
        ),
        migrations.AlterField(
            model_name="barrierrealoperation",
            name="straightness_value",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Straightness value"
            ),
        ),
        migrations.AlterField(
            model_name="mountrealoperation",
            name="operation_date",
            field=models.DateField(verbose_name="Operation date"),
        ),
        migrations.AlterField(
            model_name="mountrealoperation",
            name="quality_requirements_fulfilled",
            field=models.BooleanField(
                default=False, verbose_name="Quality requirements fulfilled"
            ),
        ),
        migrations.AlterField(
            model_name="mountrealoperation",
            name="straightness_value",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Straightness value"
            ),
        ),
        migrations.AlterField(
            model_name="operationtype",
            name="additional_sign",
            field=models.BooleanField(default=False, verbose_name="Additional sign"),
        ),
        migrations.AlterField(
            model_name="operationtype",
            name="barrier",
            field=models.BooleanField(default=False, verbose_name="Barrier"),
        ),
        migrations.AlterField(
            model_name="operationtype",
            name="mount",
            field=models.BooleanField(default=False, verbose_name="Mount"),
        ),
        migrations.AlterField(
            model_name="operationtype",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="operationtype",
            name="road_marking",
            field=models.BooleanField(default=False, verbose_name="Road marking"),
        ),
        migrations.AlterField(
            model_name="operationtype",
            name="signpost",
            field=models.BooleanField(default=False, verbose_name="Signpost"),
        ),
        migrations.AlterField(
            model_name="operationtype",
            name="traffic_light",
            field=models.BooleanField(default=False, verbose_name="Traffic light"),
        ),
        migrations.AlterField(
            model_name="operationtype",
            name="traffic_sign",
            field=models.BooleanField(default=False, verbose_name="Traffic sign"),
        ),
        migrations.AlterField(
            model_name="roadmarkingrealoperation",
            name="operation_date",
            field=models.DateField(verbose_name="Operation date"),
        ),
        migrations.AlterField(
            model_name="roadmarkingrealoperation",
            name="quality_requirements_fulfilled",
            field=models.BooleanField(
                default=False, verbose_name="Quality requirements fulfilled"
            ),
        ),
        migrations.AlterField(
            model_name="roadmarkingrealoperation",
            name="straightness_value",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Straightness value"
            ),
        ),
        migrations.AlterField(
            model_name="signpostrealoperation",
            name="operation_date",
            field=models.DateField(verbose_name="Operation date"),
        ),
        migrations.AlterField(
            model_name="signpostrealoperation",
            name="quality_requirements_fulfilled",
            field=models.BooleanField(
                default=False, verbose_name="Quality requirements fulfilled"
            ),
        ),
        migrations.AlterField(
            model_name="signpostrealoperation",
            name="straightness_value",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Straightness value"
            ),
        ),
        migrations.AlterField(
            model_name="trafficlightrealoperation",
            name="operation_date",
            field=models.DateField(verbose_name="Operation date"),
        ),
        migrations.AlterField(
            model_name="trafficlightrealoperation",
            name="quality_requirements_fulfilled",
            field=models.BooleanField(
                default=False, verbose_name="Quality requirements fulfilled"
            ),
        ),
        migrations.AlterField(
            model_name="trafficlightrealoperation",
            name="straightness_value",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Straightness value"
            ),
        ),
        migrations.AlterField(
            model_name="trafficsignrealoperation",
            name="operation_date",
            field=models.DateField(verbose_name="Operation date"),
        ),
        migrations.AlterField(
            model_name="trafficsignrealoperation",
            name="quality_requirements_fulfilled",
            field=models.BooleanField(
                default=False, verbose_name="Quality requirements fulfilled"
            ),
        ),
        migrations.AlterField(
            model_name="trafficsignrealoperation",
            name="straightness_value",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Straightness value"
            ),
        ),
    ]
