# Generated by Django 2.2.17 on 2020-12-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traffic_control", "0044_value_decimal_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="trafficcontroldevicetype",
            name="icon",
            field=models.CharField(blank=True, max_length=100, verbose_name="Icon"),
        ),
        migrations.AddField(
            model_name="trafficcontroldevicetype",
            name="size",
            field=models.CharField(blank=True, max_length=50, verbose_name="Size"),
        ),
        migrations.AddField(
            model_name="trafficcontroldevicetype",
            name="unit",
            field=models.CharField(blank=True, max_length=50, verbose_name="Unit"),
        ),
        migrations.AddField(
            model_name="trafficcontroldevicetype",
            name="value",
            field=models.CharField(blank=True, max_length=50, verbose_name="Value"),
        ),
    ]
