# Generated by Django 2.2.26 on 2022-01-21 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_control', '0046_update_field_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationtype',
            name='furniture_signpost',
            field=models.BooleanField(default=False, verbose_name='Furniture signpost'),
        ),
    ]
