# Generated by Django 3.2.12 on 2022-04-28 12:19

import uuid

import django.db.models.deletion
import enumfields.fields
import mptt.fields
from django.db import migrations, models

import city_furniture.enums


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('traffic_control', '0047_city_furniture'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponsibleEntity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(help_text='Name (for projects use Projectwise ID)', max_length=254, verbose_name='Name')),
                ('organization_level', enumfields.fields.EnumIntegerField(default=50, enum=city_furniture.enums.OrganizationLevel, verbose_name='Organization level')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='traffic_control.responsibleentity', verbose_name='Parent Responsible Entity')),
            ],
            options={
                'verbose_name': 'Responsible Entity',
                'verbose_name_plural': 'Responsible Entities',
            },
        ),
        migrations.CreateModel(
            name='GroupResponsibleEntity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='group_responsible_entity', to='auth.group', verbose_name='Group')),
                ('responsible_entities', models.ManyToManyField(blank=True, related_name='groups', to='traffic_control.ResponsibleEntity', verbose_name='Responsible Entities')),
            ],
            options={
                'verbose_name': 'Group responsible entity',
                'verbose_name_plural': 'Group responsible entities',
            },
        ),
    ]
