# Generated by Django 3.2.12 on 2022-04-28 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_control', '0048_move_responsible_entity'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalsignplan',
            name='responsible_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='traffic_control.responsibleentity', verbose_name='Responsible entity'),
        ),
        migrations.AddField(
            model_name='additionalsignreal',
            name='responsible_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='traffic_control.responsibleentity', verbose_name='Responsible entity'),
        ),
        migrations.AddField(
            model_name='barrierplan',
            name='responsible_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='traffic_control.responsibleentity', verbose_name='Responsible entity'),
        ),
        migrations.AddField(
            model_name='barrierreal',
            name='responsible_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='traffic_control.responsibleentity', verbose_name='Responsible entity'),
        ),
        migrations.AddField(
            model_name='mountplan',
            name='responsible_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='traffic_control.responsibleentity', verbose_name='Responsible entity'),
        ),
        migrations.AddField(
            model_name='mountreal',
            name='responsible_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='traffic_control.responsibleentity', verbose_name='Responsible entity'),
        ),
        migrations.AddField(
            model_name='roadmarkingplan',
            name='responsible_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='traffic_control.responsibleentity', verbose_name='Responsible entity'),
        ),
        migrations.AddField(
            model_name='roadmarkingreal',
            name='responsible_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='traffic_control.responsibleentity', verbose_name='Responsible entity'),
        ),
        migrations.AddField(
            model_name='trafficlightplan',
            name='responsible_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='traffic_control.responsibleentity', verbose_name='Responsible entity'),
        ),
        migrations.AddField(
            model_name='trafficlightreal',
            name='responsible_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='traffic_control.responsibleentity', verbose_name='Responsible entity'),
        ),
        migrations.AddField(
            model_name='trafficsignplan',
            name='responsible_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='traffic_control.responsibleentity', verbose_name='Responsible entity'),
        ),
        migrations.AddField(
            model_name='trafficsignreal',
            name='responsible_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='traffic_control.responsibleentity', verbose_name='Responsible entity'),
        ),
        migrations.AlterField(
            model_name='signpostplan',
            name='responsible_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='traffic_control.responsibleentity', verbose_name='Responsible entity'),
        ),
        migrations.AlterField(
            model_name='signpostreal',
            name='responsible_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='traffic_control.responsibleentity', verbose_name='Responsible entity'),
        ),
    ]
