# Generated by Django 3.2.13 on 2022-05-09 10:57

from django.db import migrations, models

from traffic_control.models import ResponsibleEntity


def remove_responsible_entity_person_option(apps, schema_editor):
    # Remove parent from projects, if parent is a person
    ResponsibleEntity.objects.filter(organization_level=50, parent__organization_level=40).update(parent=None)
    ResponsibleEntity.objects.filter(organization_level=50).update(parent=None)
    # Remove person level ResponsibleEntities
    ResponsibleEntity.objects.filter(organization_level=40).delete()



class Migration(migrations.Migration):

    dependencies = [
        ('traffic_control', '0049_responsible_entity_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsibleentity',
            name='external_id',
            field=models.CharField(blank=True, help_text='Use Projectwise ID for projects, can also be an abbreviation if entity has no ID', max_length=254, null=True, verbose_name='External ID'),
        ),
        migrations.RunPython(
            remove_responsible_entity_person_option, migrations.RunPython.noop
        )
    ]
