# Generated by Django 3.2.13 on 2022-06-13 13:01

import django.db.models.deletion
from django.db import migrations, models

import traffic_control.enums


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_control', '0051_help_texts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadmarkingplan',
            name='device_type',
            field=models.ForeignKey(help_text='Type of the device from Helsinki Design Manual.', limit_choices_to=models.Q(models.Q(('target_model', None), ('target_model', traffic_control.enums.DeviceTypeTargetModel['ROAD_MARKING']), _connector='OR')), on_delete=django.db.models.deletion.PROTECT, to='traffic_control.trafficcontroldevicetype', verbose_name='Device type'),
        ),
    ]
