# Generated by Django 3.2.14 on 2022-08-11 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traffic_control", "0052_alter_roadmarkingplan_device_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mountplan",
            name="base",
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name="Base"),
        ),
        migrations.AlterField(
            model_name="mountreal",
            name="base",
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name="Base"),
        ),
    ]
