# Generated by Django 3.2.14 on 2022-08-17 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_control', '0052_alter_roadmarkingplan_device_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalsignplan',
            name='content_s',
            field=models.JSONField(blank=True, help_text='Additional sign content as JSON document', null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='additionalsignreal',
            name='content_s',
            field=models.JSONField(blank=True, help_text='Additional sign content as JSON document', null=True, verbose_name='Content'),
        ),
    ]
