# Generated by Django 3.2.14 on 2022-08-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_control', '0054_add_additional_sign_device_type_and_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficcontroldevicetype',
            name='content_schema',
            field=models.JSONField(blank=True, null=True, verbose_name='Content schema'),
        ),
    ]
