# Generated by Django 3.2.15 on 2022-09-05 14:49

from django.db import migrations, models
import django.db.models.deletion
import traffic_control.enums


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_control', '0055_add_device_type_content_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalsignplan',
            name='device_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('target_model', None), ('target_model', traffic_control.enums.DeviceTypeTargetModel['ADDITIONAL_SIGN']), _connector='OR')), null=True, on_delete=django.db.models.deletion.PROTECT, to='traffic_control.trafficcontroldevicetype', verbose_name='Device type'),
        ),
        migrations.AlterField(
            model_name='additionalsignreal',
            name='device_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('target_model', None), ('target_model', traffic_control.enums.DeviceTypeTargetModel['ADDITIONAL_SIGN']), _connector='OR')), null=True, on_delete=django.db.models.deletion.PROTECT, to='traffic_control.trafficcontroldevicetype', verbose_name='Device type'),
        ),
    ]
