# Generated by Django 3.2.15 on 2022-09-05 14:56

from django.db import migrations
import traffic_control.models.common


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_control', '0056_additional_sign_json_validation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafficcontroldevicetype',
            name='content_schema',
            field=traffic_control.models.common.JSONSchemaField(blank=True, null=True, verbose_name='Content schema'),
        ),
    ]
