# Generated by Django 3.2.15 on 2022-09-07 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("traffic_control", "0059_additional_sign_installed_by_nullable"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="additionalsigncontentreal",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="additionalsigncontentreal",
            name="device_type",
        ),
        migrations.RemoveField(
            model_name="additionalsigncontentreal",
            name="parent",
        ),
        migrations.RemoveField(
            model_name="additionalsigncontentreal",
            name="updated_by",
        ),
        migrations.DeleteModel(
            name="AdditionalSignContentPlan",
        ),
        migrations.DeleteModel(
            name="AdditionalSignContentReal",
        ),
    ]
