# Generated by Django 3.2.16 on 2022-12-15 11:54

from django.db import migrations
import enumfields.fields
import traffic_control.enums
import traffic_control.models.additional_sign
import traffic_control.models.barrier
import traffic_control.models.road_marking
import traffic_control.models.signpost
import traffic_control.models.traffic_light
import traffic_control.models.traffic_sign


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_control', '0060_remove_additional_sign_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalsignplan',
            name='color',
            field=enumfields.fields.EnumIntegerField(blank=True, enum=traffic_control.models.additional_sign.Color, null=True, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='additionalsignplan',
            name='lane_number',
            field=enumfields.fields.EnumField(blank=True, enum=traffic_control.enums.LaneNumber, help_text='Describes which lane of the road this sign affects.', max_length=10, null=True, verbose_name='Lane number'),
        ),
        migrations.AlterField(
            model_name='additionalsignplan',
            name='lane_type',
            field=enumfields.fields.EnumField(blank=True, enum=traffic_control.enums.LaneType, help_text='The type of lane which this sign affects.', max_length=10, null=True, verbose_name='Lane type'),
        ),
        migrations.AlterField(
            model_name='additionalsignplan',
            name='location_specifier',
            field=enumfields.fields.EnumIntegerField(blank=True, enum=traffic_control.models.traffic_sign.LocationSpecifier, help_text='Specifies where the sign is in relation to the road.', null=True, verbose_name='Location specifier'),
        ),
        migrations.AlterField(
            model_name='additionalsignplan',
            name='reflection_class',
            field=enumfields.fields.EnumField(blank=True, enum=traffic_control.enums.Reflection, max_length=2, null=True, verbose_name='Reflection'),
        ),
        migrations.AlterField(
            model_name='additionalsignplan',
            name='surface_class',
            field=enumfields.fields.EnumField(blank=True, enum=traffic_control.enums.Surface, max_length=6, null=True, verbose_name='Surface'),
        ),
        migrations.AlterField(
            model_name='additionalsignreal',
            name='color',
            field=enumfields.fields.EnumIntegerField(blank=True, enum=traffic_control.models.additional_sign.Color, null=True, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='additionalsignreal',
            name='condition',
            field=enumfields.fields.EnumIntegerField(blank=True, enum=traffic_control.enums.Condition, help_text='Describes the condition of this device.', null=True, verbose_name='Condition'),
        ),
        migrations.AlterField(
            model_name='additionalsignreal',
            name='installation_status',
            field=enumfields.fields.EnumField(blank=True, enum=traffic_control.enums.InstallationStatus, help_text='Describes this devices installation status.', max_length=10, null=True, verbose_name='Installation status'),
        ),
        migrations.AlterField(
            model_name='additionalsignreal',
            name='lane_number',
            field=enumfields.fields.EnumField(blank=True, enum=traffic_control.enums.LaneNumber, help_text='Describes which lane of the road this sign affects.', max_length=10, null=True, verbose_name='Lane number'),
        ),
        migrations.AlterField(
            model_name='additionalsignreal',
            name='lane_type',
            field=enumfields.fields.EnumField(blank=True, enum=traffic_control.enums.LaneType, help_text='The type of lane which this sign affects.', max_length=10, null=True, verbose_name='Lane type'),
        ),
        migrations.AlterField(
            model_name='additionalsignreal',
            name='location_specifier',
            field=enumfields.fields.EnumIntegerField(blank=True, enum=traffic_control.models.traffic_sign.LocationSpecifier, help_text='Specifies where the sign is in relation to the road.', null=True, verbose_name='Location specifier'),
        ),
        migrations.AlterField(
            model_name='additionalsignreal',
            name='reflection_class',
            field=enumfields.fields.EnumField(blank=True, enum=traffic_control.enums.Reflection, max_length=2, null=True, verbose_name='Reflection'),
        ),
        migrations.AlterField(
            model_name='additionalsignreal',
            name='size',
            field=enumfields.fields.EnumField(blank=True, enum=traffic_control.enums.Size, max_length=1, null=True, verbose_name='Size'),
        ),
        migrations.AlterField(
            model_name='additionalsignreal',
            name='surface_class',
            field=enumfields.fields.EnumField(blank=True, enum=traffic_control.enums.Surface, max_length=6, null=True, verbose_name='Surface'),
        ),
        migrations.AlterField(
            model_name='barrierplan',
            name='lane_number',
            field=enumfields.fields.EnumField(blank=True, enum=traffic_control.enums.LaneNumber, help_text='Describes which lane of the road this barrier affects.', max_length=10, null=True, verbose_name='Lane number'),
        ),
        migrations.AlterField(
            model_name='barrierplan',
            name='lane_type',
            field=enumfields.fields.EnumField(blank=True, enum=traffic_control.enums.LaneType, help_text='The type of lane which this barrier affects.', max_length=10, null=True, verbose_name='Lane type'),
        ),
        migrations.AlterField(
            model_name='barrierplan',
            name='location_specifier',
            field=enumfields.fields.EnumIntegerField(blank=True, enum=traffic_control.models.barrier.LocationSpecifier, help_text='Specifies where the barrier is in relation to the road.', null=True, verbose_name='Location specifier'),
        ),
        migrations.AlterField(
            model_name='barrierreal',
            name='condition',
            field=enumfields.fields.EnumIntegerField(blank=True, enum=traffic_control.enums.Condition, help_text='Describes the condition of this device.', null=True, verbose_name='Condition'),
        ),
        migrations.AlterField(
            model_name='barrierreal',
            name='installation_status',
            field=enumfields.fields.EnumField(blank=True, enum=traffic_control.enums.InstallationStatus, help_text='Describes this devices installation status.', max_length=10, null=True, verbose_name='Installation status'),
        ),
        migrations.AlterField(
            model_name='barrierreal',
            name='lane_number',
            field=enumfields.fields.EnumField(blank=True, enum=traffic_control.enums.LaneNumber, help_text='Describes which lane of the road this barrier affects.', max_length=10, null=True, verbose_name='Lane number'),
        ),
        migrations.AlterField(
            model_name='barrierreal',
            name='lane_type',
            field=enumfields.fields.EnumField(blank=True, enum=traffic_control.enums.LaneType, help_text='The type of lane which this barrier affects.', max_length=10, null=True, verbose_name='Lane type'),
        ),
        migrations.AlterField(
            model_name='barrierreal',
            name='location_specifier',
            field=enumfields.fields.EnumIntegerField(blank=True, enum=traffic_control.models.barrier.LocationSpecifier, help_text='Specifies where the barrier is in relation to the road.', null=True, verbose_name='Location specifier'),
        ),
        migrations.AlterField(
            model_name='mountreal',
            name='condition',
            field=enumfields.fields.EnumIntegerField(blank=True, enum=traffic_control.enums.Condition, help_text='Describes the condition of this device.', null=True, verbose_name='Condition'),
        ),
        migrations.AlterField(
            model_name='mountreal',
            name='installation_status',
            field=enumfields.fields.EnumField(blank=True, enum=traffic_control.enums.InstallationStatus, help_text='Describes this devices installation status.', max_length=10, null=True, verbose_name='Installation status'),
        ),
        migrations.AlterField(
            model_name='roadmarkingplan',
            name='color',
            field=enumfields.fields.EnumIntegerField(blank=True, enum=traffic_control.models.road_marking.RoadMarkingColor, null=True, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='roadmarkingplan',
            name='lane_number',
            field=enumfields.fields.EnumField(blank=True, enum=traffic_control.enums.LaneNumber, help_text='Describes which lane of the road this road marking affects.', max_length=10, null=True, verbose_name='Lane number'),
        ),
        migrations.AlterField(
            model_name='roadmarkingplan',
            name='lane_type',
            field=enumfields.fields.EnumField(blank=True, enum=traffic_control.enums.LaneType, help_text='The type of lane which this road marking affects.', max_length=10, null=True, verbose_name='Lane type'),
        ),
        migrations.AlterField(
            model_name='roadmarkingplan',
            name='line_direction',
            field=enumfields.fields.EnumField(blank=True, enum=traffic_control.models.road_marking.LineDirection, max_length=10, null=True, verbose_name='Line direction'),
        ),
        migrations.AlterField(
            model_name='roadmarkingplan',
            name='location_specifier',
            field=enumfields.fields.EnumIntegerField(blank=True, enum=traffic_control.models.road_marking.LocationSpecifier, help_text='Specifies where the road marking is in relation to the lane.', null=True, verbose_name='Location specifier'),
        ),
        migrations.AlterField(
            model_name='roadmarkingreal',
            name='color',
            field=enumfields.fields.EnumIntegerField(blank=True, enum=traffic_control.models.road_marking.RoadMarkingColor, null=True, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='roadmarkingreal',
            name='condition',
            field=enumfields.fields.EnumIntegerField(blank=True, enum=traffic_control.enums.Condition, help_text='Describes the condition of this device.', null=True, verbose_name='Condition'),
        ),
        migrations.AlterField(
            model_name='roadmarkingreal',
            name='installation_status',
            field=enumfields.fields.EnumField(blank=True, enum=traffic_control.enums.InstallationStatus, help_text='Describes this devices installation status.', max_length=10, null=True, verbose_name='Installation status'),
        ),
        migrations.AlterField(
            model_name='roadmarkingreal',
            name='lane_number',
            field=enumfields.fields.EnumField(blank=True, enum=traffic_control.enums.LaneNumber, help_text='Describes which lane of the road this road marking affects.', max_length=10, null=True, verbose_name='Lane number'),
        ),
        migrations.AlterField(
            model_name='roadmarkingreal',
            name='lane_type',
            field=enumfields.fields.EnumField(blank=True, enum=traffic_control.enums.LaneType, help_text='The type of lane which this road marking affects.', max_length=10, null=True, verbose_name='Lane type'),
        ),
        migrations.AlterField(
            model_name='roadmarkingreal',
            name='line_direction',
            field=enumfields.fields.EnumField(blank=True, enum=traffic_control.models.road_marking.LineDirection, max_length=10, null=True, verbose_name='Line direction'),
        ),
        migrations.AlterField(
            model_name='roadmarkingreal',
            name='location_specifier',
            field=enumfields.fields.EnumIntegerField(blank=True, enum=traffic_control.models.road_marking.LocationSpecifier, help_text='Specifies where the road marking is in relation to the lane.', null=True, verbose_name='Location specifier'),
        ),
        migrations.AlterField(
            model_name='signpostplan',
            name='lane_number',
            field=enumfields.fields.EnumField(blank=True, enum=traffic_control.enums.LaneNumber, help_text='Describes which lane of the road this sign affects.', max_length=10, null=True, verbose_name='Lane number'),
        ),
        migrations.AlterField(
            model_name='signpostplan',
            name='lane_type',
            field=enumfields.fields.EnumField(blank=True, enum=traffic_control.enums.LaneType, help_text='The type of lane which this sign affects.', max_length=10, null=True, verbose_name='Lane type'),
        ),
        migrations.AlterField(
            model_name='signpostplan',
            name='location_specifier',
            field=enumfields.fields.EnumIntegerField(blank=True, enum=traffic_control.models.signpost.LocationSpecifier, help_text='Specifies where the sign is in relation to the road.', null=True, verbose_name='Location specifier'),
        ),
        migrations.AlterField(
            model_name='signpostplan',
            name='reflection_class',
            field=enumfields.fields.EnumField(blank=True, enum=traffic_control.enums.Reflection, max_length=2, null=True, verbose_name='Reflection'),
        ),
        migrations.AlterField(
            model_name='signpostplan',
            name='size',
            field=enumfields.fields.EnumField(blank=True, enum=traffic_control.enums.Size, max_length=1, null=True, verbose_name='Size'),
        ),
        migrations.AlterField(
            model_name='signpostreal',
            name='condition',
            field=enumfields.fields.EnumIntegerField(blank=True, enum=traffic_control.enums.Condition, help_text='Describes the condition of this device.', null=True, verbose_name='Condition'),
        ),
        migrations.AlterField(
            model_name='signpostreal',
            name='installation_status',
            field=enumfields.fields.EnumField(blank=True, enum=traffic_control.enums.InstallationStatus, help_text='Describes this devices installation status.', max_length=10, null=True, verbose_name='Installation status'),
        ),
        migrations.AlterField(
            model_name='signpostreal',
            name='lane_number',
            field=enumfields.fields.EnumField(blank=True, enum=traffic_control.enums.LaneNumber, help_text='Describes which lane of the road this sign affects.', max_length=10, null=True, verbose_name='Lane number'),
        ),
        migrations.AlterField(
            model_name='signpostreal',
            name='lane_type',
            field=enumfields.fields.EnumField(blank=True, enum=traffic_control.enums.LaneType, help_text='The type of lane which this sign affects.', max_length=10, null=True, verbose_name='Lane type'),
        ),
        migrations.AlterField(
            model_name='signpostreal',
            name='location_specifier',
            field=enumfields.fields.EnumIntegerField(blank=True, enum=traffic_control.models.signpost.LocationSpecifier, help_text='Specifies where the sign is in relation to the road.', null=True, verbose_name='Location specifier'),
        ),
        migrations.AlterField(
            model_name='signpostreal',
            name='reflection_class',
            field=enumfields.fields.EnumField(blank=True, enum=traffic_control.enums.Reflection, max_length=2, null=True, verbose_name='Reflection'),
        ),
        migrations.AlterField(
            model_name='signpostreal',
            name='size',
            field=enumfields.fields.EnumField(blank=True, enum=traffic_control.enums.Size, max_length=1, null=True, verbose_name='Size'),
        ),
        migrations.AlterField(
            model_name='trafficlightplan',
            name='lane_number',
            field=enumfields.fields.EnumField(blank=True, enum=traffic_control.enums.LaneNumber, help_text='Describes which lane of the road this traffic light affects.', max_length=10, null=True, verbose_name='Lane number'),
        ),
        migrations.AlterField(
            model_name='trafficlightplan',
            name='lane_type',
            field=enumfields.fields.EnumField(blank=True, enum=traffic_control.enums.LaneType, help_text='The type of lane which this traffic light affects.', max_length=10, null=True, verbose_name='Lane type'),
        ),
        migrations.AlterField(
            model_name='trafficlightplan',
            name='location_specifier',
            field=enumfields.fields.EnumIntegerField(blank=True, enum=traffic_control.models.traffic_light.LocationSpecifier, help_text='Specifies where the traffic light is in relation to the road.', null=True, verbose_name='Location specifier'),
        ),
        migrations.AlterField(
            model_name='trafficlightreal',
            name='condition',
            field=enumfields.fields.EnumIntegerField(blank=True, enum=traffic_control.enums.Condition, help_text='Describes the condition of this device.', null=True, verbose_name='Condition'),
        ),
        migrations.AlterField(
            model_name='trafficlightreal',
            name='installation_status',
            field=enumfields.fields.EnumField(blank=True, enum=traffic_control.enums.InstallationStatus, help_text='Describes this devices installation status.', max_length=10, null=True, verbose_name='Installation status'),
        ),
        migrations.AlterField(
            model_name='trafficlightreal',
            name='lane_number',
            field=enumfields.fields.EnumField(blank=True, enum=traffic_control.enums.LaneNumber, help_text='Describes which lane of the road this traffic light affects.', max_length=10, null=True, verbose_name='Lane number'),
        ),
        migrations.AlterField(
            model_name='trafficlightreal',
            name='lane_type',
            field=enumfields.fields.EnumField(blank=True, enum=traffic_control.enums.LaneType, help_text='The type of lane which this traffic light affects.', max_length=10, null=True, verbose_name='Lane type'),
        ),
        migrations.AlterField(
            model_name='trafficlightreal',
            name='location_specifier',
            field=enumfields.fields.EnumIntegerField(blank=True, enum=traffic_control.models.traffic_light.LocationSpecifier, help_text='Specifies where the traffic light is in relation to the road.', null=True, verbose_name='Location specifier'),
        ),
        migrations.AlterField(
            model_name='trafficsignplan',
            name='lane_number',
            field=enumfields.fields.EnumField(blank=True, enum=traffic_control.enums.LaneNumber, help_text='Describes which lane of the road this sign affects.', max_length=10, null=True, verbose_name='Lane number'),
        ),
        migrations.AlterField(
            model_name='trafficsignplan',
            name='lane_type',
            field=enumfields.fields.EnumField(blank=True, enum=traffic_control.enums.LaneType, help_text='The type of lane which this sign affects.', max_length=10, null=True, verbose_name='Lane type'),
        ),
        migrations.AlterField(
            model_name='trafficsignplan',
            name='location_specifier',
            field=enumfields.fields.EnumIntegerField(blank=True, enum=traffic_control.models.traffic_sign.LocationSpecifier, help_text='Specifies where the sign is in relation to the road.', null=True, verbose_name='Location specifier'),
        ),
        migrations.AlterField(
            model_name='trafficsignplan',
            name='reflection_class',
            field=enumfields.fields.EnumField(blank=True, enum=traffic_control.enums.Reflection, max_length=2, null=True, verbose_name='Reflection'),
        ),
        migrations.AlterField(
            model_name='trafficsignplan',
            name='size',
            field=enumfields.fields.EnumField(blank=True, enum=traffic_control.enums.Size, max_length=1, null=True, verbose_name='Size'),
        ),
        migrations.AlterField(
            model_name='trafficsignplan',
            name='surface_class',
            field=enumfields.fields.EnumField(blank=True, enum=traffic_control.enums.Surface, max_length=6, null=True, verbose_name='Surface'),
        ),
        migrations.AlterField(
            model_name='trafficsignreal',
            name='condition',
            field=enumfields.fields.EnumIntegerField(blank=True, enum=traffic_control.enums.Condition, help_text='Describes the condition of this device.', null=True, verbose_name='Condition'),
        ),
        migrations.AlterField(
            model_name='trafficsignreal',
            name='installation_status',
            field=enumfields.fields.EnumField(blank=True, enum=traffic_control.enums.InstallationStatus, help_text='Describes this devices installation status.', max_length=10, null=True, verbose_name='Installation status'),
        ),
        migrations.AlterField(
            model_name='trafficsignreal',
            name='lane_number',
            field=enumfields.fields.EnumField(blank=True, enum=traffic_control.enums.LaneNumber, help_text='Describes which lane of the road this sign affects.', max_length=10, null=True, verbose_name='Lane number'),
        ),
        migrations.AlterField(
            model_name='trafficsignreal',
            name='lane_type',
            field=enumfields.fields.EnumField(blank=True, enum=traffic_control.enums.LaneType, help_text='The type of lane which this sign affects.', max_length=10, null=True, verbose_name='Lane type'),
        ),
        migrations.AlterField(
            model_name='trafficsignreal',
            name='location_specifier',
            field=enumfields.fields.EnumIntegerField(blank=True, enum=traffic_control.models.traffic_sign.LocationSpecifier, help_text='Specifies where the sign is in relation to the road.', null=True, verbose_name='Location specifier'),
        ),
        migrations.AlterField(
            model_name='trafficsignreal',
            name='reflection_class',
            field=enumfields.fields.EnumField(blank=True, enum=traffic_control.enums.Reflection, max_length=2, null=True, verbose_name='Reflection'),
        ),
        migrations.AlterField(
            model_name='trafficsignreal',
            name='size',
            field=enumfields.fields.EnumField(blank=True, enum=traffic_control.enums.Size, max_length=1, null=True, verbose_name='Size'),
        ),
        migrations.AlterField(
            model_name='trafficsignreal',
            name='surface_class',
            field=enumfields.fields.EnumField(blank=True, enum=traffic_control.enums.Surface, max_length=6, null=True, verbose_name='Surface'),
        ),
    ]
