# Generated by Django 3.2.17 on 2023-02-08 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_control', '0064_blank_mount_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='decision_maker',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='planner',
        ),
    ]
