# Generated by Django 3.2.20 on 2023-08-14 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_control', '0066_device_users_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='diary_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Diary number'),
        ),
        migrations.AddField(
            model_name='plan',
            name='drawing_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Drawing number'),
        ),
    ]
