# Generated by Django 3.2.22 on 2023-10-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_control', '0070_plan_number_to_decision_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafficsignplan',
            name='road_name',
            field=models.CharField(blank=True, help_text='Name of the road this traffic sign is installed at.', max_length=254, null=True, verbose_name='Road name'),
        ),
        migrations.AlterField(
            model_name='trafficsignreal',
            name='road_name',
            field=models.CharField(blank=True, help_text='Name of the road this traffic sign is installed at.', max_length=254, null=True, verbose_name='Road name'),
        ),
    ]
