# Generated by Django 3.2.22 on 2023-11-07 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_control', '0071_fix_road_name_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalsignplan',
            name='missing_content',
            field=models.BooleanField(default=False, help_text='Content (content_s) is not available although the device type content schema requires it.', verbose_name='Missing content'),
        ),
        migrations.AddField(
            model_name='additionalsignreal',
            name='missing_content',
            field=models.BooleanField(default=False, help_text='Content (content_s) is not available although the device type content schema requires it.', verbose_name='Missing content'),
        ),
    ]
