# Generated by Django 3.2.22 on 2023-11-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_control', '0073_additional_sign_additional_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalsignplan',
            name='direction',
            field=models.IntegerField(blank=True, help_text='The direction a person is facing when looking perpendicular to the sign. The value is in degrees from 0 to 359, where 0 is north, 90 is east, etc.', null=True, verbose_name='Direction'),
        ),
        migrations.AlterField(
            model_name='additionalsignreal',
            name='direction',
            field=models.IntegerField(blank=True, help_text='The direction a person is facing when looking perpendicular to the sign. The value is in degrees from 0 to 359, where 0 is north, 90 is east, etc.', null=True, verbose_name='Direction'),
        ),
        migrations.AlterField(
            model_name='signpostplan',
            name='direction',
            field=models.IntegerField(blank=True, help_text='The direction a person is facing when looking perpendicular to the sign. The value is in degrees from 0 to 359, where 0 is north, 90 is east, etc.', null=True, verbose_name='Direction'),
        ),
        migrations.AlterField(
            model_name='signpostreal',
            name='direction',
            field=models.IntegerField(blank=True, help_text='The direction a person is facing when looking perpendicular to the sign. The value is in degrees from 0 to 359, where 0 is north, 90 is east, etc.', null=True, verbose_name='Direction'),
        ),
        migrations.AlterField(
            model_name='trafficlightplan',
            name='direction',
            field=models.IntegerField(blank=True, help_text='The direction a person is facing when looking perpendicular to the traffic light. The value is in degrees from 0 to 359, where 0 is north, 90 is east, etc.', null=True, verbose_name='Direction'),
        ),
        migrations.AlterField(
            model_name='trafficlightreal',
            name='direction',
            field=models.IntegerField(blank=True, help_text='The direction a person is facing when looking perpendicular to the traffic light. The value is in degrees from 0 to 359, where 0 is north, 90 is east, etc.', null=True, verbose_name='Direction'),
        ),
        migrations.AlterField(
            model_name='trafficsignplan',
            name='direction',
            field=models.IntegerField(blank=True, help_text='The direction a person is facing when looking perpendicular to the sign. The value is in degrees from 0 to 359, where 0 is north, 90 is east, etc.', null=True, verbose_name='Direction'),
        ),
        migrations.AlterField(
            model_name='trafficsignreal',
            name='direction',
            field=models.IntegerField(blank=True, help_text='The direction a person is facing when looking perpendicular to the sign. The value is in degrees from 0 to 359, where 0 is north, 90 is east, etc.', null=True, verbose_name='Direction'),
        ),
    ]
