# Generated by Django 3.2.23 on 2023-12-19 11:10

from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import traffic_control.enums


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_control', '0074_nullable_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficcontroldevicetype',
            name='corresponding_valid_device_type',
            field=models.ForeignKey(blank=True, help_text='The corresponding valid device type if this device type is obsolete or obsolete.', limit_choices_to={'validity': traffic_control.enums.TrafficControlDeviceTypeValidity['VALID']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='traffic_control.trafficcontroldevicetype', verbose_name='Corresponding valid device type'),
        ),
        migrations.AddField(
            model_name='trafficcontroldevicetype',
            name='validity',
            field=enumfields.fields.EnumField(default='valid', enum=traffic_control.enums.TrafficControlDeviceTypeValidity, help_text='Defines if this device type is valid, obsolescent or obsolete.', max_length=32, verbose_name='Validity'),
        ),
    ]
