# Generated by Django 3.2.23 on 2024-02-01 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_control', '0075_source_id_source_name_unique_for_active_objects'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficSignPlanReplacement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('new', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='replacement_to_old', to='traffic_control.trafficsignplan', verbose_name='New')),
                ('old', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='replacement_to_new', to='traffic_control.trafficsignplan', verbose_name='Old')),
            ],
            options={
                'verbose_name': 'Traffic Sign Plan Replacement',
                'verbose_name_plural': 'Traffic Sign Plan Replacements',
                'db_table': 'traffic_sign_plan_replacement',
            },
        ),
        migrations.CreateModel(
            name='TrafficLightPlanReplacement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('new', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='replacement_to_old', to='traffic_control.trafficlightplan', verbose_name='New')),
                ('old', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='replacement_to_new', to='traffic_control.trafficlightplan', verbose_name='Old')),
            ],
            options={
                'verbose_name': 'Traffic Light Plan Replacement',
                'verbose_name_plural': 'Traffic Light Plan Replacements',
                'db_table': 'traffic_light_plan_replacement',
            },
        ),
        migrations.CreateModel(
            name='SignpostPlanReplacement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('new', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='replacement_to_old', to='traffic_control.signpostplan', verbose_name='New')),
                ('old', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='replacement_to_new', to='traffic_control.signpostplan', verbose_name='Old')),
            ],
            options={
                'verbose_name': 'Signpost Plan Replacement',
                'verbose_name_plural': 'Signpost Plan Replacements',
                'db_table': 'signpost_plan_replacement',
            },
        ),
        migrations.CreateModel(
            name='RoadMarkingPlanReplacement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('new', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='replacement_to_old', to='traffic_control.roadmarkingplan', verbose_name='New')),
                ('old', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='replacement_to_new', to='traffic_control.roadmarkingplan', verbose_name='Old')),
            ],
            options={
                'verbose_name': 'Road Marking Plan Replacement',
                'verbose_name_plural': 'Road Marking Plan Replacements',
                'db_table': 'road_marking_plan_replacement',
            },
        ),
        migrations.CreateModel(
            name='MountPlanReplacement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('new', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='replacement_to_old', to='traffic_control.mountplan', verbose_name='New')),
                ('old', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='replacement_to_new', to='traffic_control.mountplan', verbose_name='Old')),
            ],
            options={
                'verbose_name': 'Mount Plan Replacement',
                'verbose_name_plural': 'Mount Plan Replacements',
                'db_table': 'mount_plan_replacement',
            },
        ),
        migrations.CreateModel(
            name='BarrierPlanReplacement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('new', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='replacement_to_old', to='traffic_control.barrierplan', verbose_name='New')),
                ('old', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='replacement_to_new', to='traffic_control.barrierplan', verbose_name='Old')),
            ],
            options={
                'verbose_name': 'Barrier Plan Replacement',
                'verbose_name_plural': 'Barrier Plan Replacements',
                'db_table': 'barrier_plan_replacement',
            },
        ),
        migrations.CreateModel(
            name='AdditionalSignPlanReplacement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('new', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='replacement_to_old', to='traffic_control.additionalsignplan', verbose_name='New')),
                ('old', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='replacement_to_new', to='traffic_control.additionalsignplan', verbose_name='Old')),
            ],
            options={
                'verbose_name': 'Additional Sign Plan Replacement',
                'verbose_name_plural': 'Additional Sign Plan Replacements',
                'db_table': 'additional_sign_plan_replacement',
            },
        ),
    ]
