# Generated by Django 4.2.10 on 2024-04-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_control', '0077_alter_additionalsignplan_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='diary_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Diary number'),
        ),
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('diary_number',), name='traffic_control_plan_unique_diary_number_id'),
        ),
    ]
