# Generated by Django 4.2.13 on 2024-08-09 12:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_control', '0078_alter_plan_diary_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalSignRealFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('file', models.FileField(upload_to='realfiles/additional_sign/', verbose_name='File')),
                ('additional_sign_real', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='traffic_control.additionalsignreal')),
            ],
            options={
                'verbose_name': 'Additional Sign Real File',
                'verbose_name_plural': 'Additional Sign Real Files',
                'db_table': 'additional_sign_real_file',
            },
        ),
        migrations.CreateModel(
            name='AdditionalSignPlanFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('file', models.FileField(upload_to='planfiles/additional_sign/', verbose_name='File')),
                ('additional_sign_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='traffic_control.additionalsignplan')),
            ],
            options={
                'verbose_name': 'Additional Sign Plan File',
                'verbose_name_plural': 'Additional Sign Plan Files',
                'db_table': 'additional_sign_plan_file',
            },
        ),
    ]
