# Generated by Django 4.2.15 on 2024-09-16 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_control', '0080_mountplan_location_specifier_mountplan_road_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mountreal',
            name='attachment_url',
            field=models.URLField(blank=True, help_text='URL to a file attachment related to this mount.', max_length=500, null=True, verbose_name='Attachment url'),
        ),
    ]
