# Generated by Django 4.2.15 on 2024-09-20 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_control', '0081_mountreal_attachment_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalsignplan',
            name='height',
            field=models.IntegerField(blank=True, help_text='The height of the sign from the ground, measured from the bottom in centimeters.', null=True, verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='additionalsignreal',
            name='height',
            field=models.IntegerField(blank=True, help_text='The height of the sign from the ground, measured from the bottom in centimeters.', null=True, verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='signpostplan',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The height of the sign from the ground, measured from the bottom in centimeters.', max_digits=5, null=True, verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='signpostreal',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The height of the sign from the ground, measured from the bottom in centimeters.', max_digits=5, null=True, verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='trafficlightplan',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The height of the sign from the ground, measured from the bottom in centimeters.', max_digits=5, null=True, verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='trafficlightreal',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The height of the sign from the ground, measured from the bottom in centimeters.', max_digits=5, null=True, verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='trafficsignplan',
            name='height',
            field=models.IntegerField(blank=True, help_text='The height of the sign from the ground, measured from the bottom in centimeters.', null=True, verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='trafficsignreal',
            name='height',
            field=models.IntegerField(blank=True, help_text='The height of the sign from the ground, measured from the bottom in centimeters.', null=True, verbose_name='Height'),
        ),
    ]
