# Generated by Django 4.2.15 on 2024-10-07 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_control', '0082_alter_additionalsignplan_height_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='additionalsignreal',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('additional_sign_plan',), name='traffic_control_additionalsignreal_unique_additional_sign_plan_id'),
        ),
        migrations.AddConstraint(
            model_name='barrierreal',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('barrier_plan',), name='traffic_control_barrierreal_unique_barrier_plan_id'),
        ),
        migrations.AddConstraint(
            model_name='mountreal',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('mount_plan',), name='traffic_control_mountreal_unique_mount_plan_id'),
        ),
        migrations.AddConstraint(
            model_name='roadmarkingreal',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('road_marking_plan',), name='traffic_control_roadmarkingreal_unique_road_marking_plan_id'),
        ),
        migrations.AddConstraint(
            model_name='signpostreal',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('signpost_plan',), name='traffic_control_signpostreal_unique_signpost_plan_id'),
        ),
        migrations.AddConstraint(
            model_name='trafficlightreal',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('traffic_light_plan',), name='traffic_control_trafficlightreal_unique_traffic_light_plan'),
        ),
        migrations.AddConstraint(
            model_name='trafficsignreal',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('traffic_sign_plan',), name='traffic_control_trafficsignreal_unique_traffic_sign_plan_id'),
        ),
    ]
