# Generated by Django 4.2.16 on 2024-10-21 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_control', '0084_alter_roadmarkingplan_arrow_direction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='decision_date',
            field=models.DateField(blank=True, help_text='Decision date for this plan.', null=True, verbose_name='Decision date'),
        ),
    ]
