# Generated by Django 4.2.16 on 2024-10-21 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_control', '0085_plan_decision_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='decision_date',
            field=models.DateField(blank=True, help_text='Date on which a decision was made on the plan.', null=True, verbose_name='Decision date'),
        ),
    ]
