# Generated by Django 4.2.16 on 2025-01-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_control', '0087_alter_additionalsignreal_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='decision_url',
            field=models.URLField(blank=True, help_text='URL to decision web page', max_length=500, null=True, verbose_name='Decision url'),
        ),
    ]
