# Generated by Django 4.2.18 on 2025-03-20 10:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_control', '0088_plan_decision_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingZoneUpdateInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('update_infos', models.JSONField(null=True)),
                ('update_errors', models.JSONField(null=True)),
                ('database_update', models.BooleanField(default=False)),
            ],
        ),
    ]
