# Generated by Django 4.2.20 on 2025-04-07 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_control', '0089_parkingzoneupdateinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalsignplan',
            name='parent',
            field=models.ForeignKey(default=1, help_text='The traffic sign to which this additional sign is associated.', on_delete=django.db.models.deletion.PROTECT, related_name='additional_signs', to='traffic_control.trafficsignplan', verbose_name='Parent Traffic Sign Plan'),
            preserve_default=False,
        ),
    ]
