# Generated by Django 4.2.20 on 2025-06-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_control', '0090_alter_additionalsignplan_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalsignplan',
            name='seasonal_validity_period_end',
        ),
        migrations.RemoveField(
            model_name='additionalsignplan',
            name='seasonal_validity_period_start',
        ),
        migrations.RemoveField(
            model_name='additionalsignreal',
            name='seasonal_validity_period_end',
        ),
        migrations.RemoveField(
            model_name='additionalsignreal',
            name='seasonal_validity_period_start',
        ),
        migrations.RemoveField(
            model_name='roadmarkingplan',
            name='seasonal_validity_period_end',
        ),
        migrations.RemoveField(
            model_name='roadmarkingplan',
            name='seasonal_validity_period_start',
        ),
        migrations.RemoveField(
            model_name='roadmarkingreal',
            name='seasonal_validity_period_end',
        ),
        migrations.RemoveField(
            model_name='roadmarkingreal',
            name='seasonal_validity_period_start',
        ),
        migrations.RemoveField(
            model_name='signpostplan',
            name='seasonal_validity_period_end',
        ),
        migrations.RemoveField(
            model_name='signpostplan',
            name='seasonal_validity_period_start',
        ),
        migrations.RemoveField(
            model_name='signpostreal',
            name='seasonal_validity_period_end',
        ),
        migrations.RemoveField(
            model_name='signpostreal',
            name='seasonal_validity_period_start',
        ),
        migrations.RemoveField(
            model_name='trafficsignplan',
            name='seasonal_validity_period_end',
        ),
        migrations.RemoveField(
            model_name='trafficsignplan',
            name='seasonal_validity_period_start',
        ),
        migrations.RemoveField(
            model_name='trafficsignreal',
            name='seasonal_validity_period_end',
        ),
        migrations.RemoveField(
            model_name='trafficsignreal',
            name='seasonal_validity_period_start',
        ),
        migrations.AddField(
            model_name='additionalsignplan',
            name='seasonal_validity_period_information',
            field=models.TextField(blank=True, default='', help_text='Seasonal validity period information related to this device.', verbose_name='Seasonal validity period information'),
        ),
        migrations.AddField(
            model_name='additionalsignreal',
            name='seasonal_validity_period_information',
            field=models.TextField(blank=True, default='', help_text='Seasonal validity period information related to this device.', verbose_name='Seasonal validity period information'),
        ),
        migrations.AddField(
            model_name='roadmarkingplan',
            name='seasonal_validity_period_information',
            field=models.TextField(blank=True, default='', help_text='Seasonal validity period information related to this device.', verbose_name='Seasonal validity period information'),
        ),
        migrations.AddField(
            model_name='roadmarkingreal',
            name='seasonal_validity_period_information',
            field=models.TextField(blank=True, default='', help_text='Seasonal validity period information related to this device.', verbose_name='Seasonal validity period information'),
        ),
        migrations.AddField(
            model_name='signpostplan',
            name='seasonal_validity_period_information',
            field=models.TextField(blank=True, default='', help_text='Seasonal validity period information related to this device.', verbose_name='Seasonal validity period information'),
        ),
        migrations.AddField(
            model_name='signpostreal',
            name='seasonal_validity_period_information',
            field=models.TextField(blank=True, default='', help_text='Seasonal validity period information related to this device.', verbose_name='Seasonal validity period information'),
        ),
        migrations.AddField(
            model_name='trafficsignplan',
            name='seasonal_validity_period_information',
            field=models.TextField(blank=True, default='', help_text='Seasonal validity period information related to this device.', verbose_name='Seasonal validity period information'),
        ),
        migrations.AddField(
            model_name='trafficsignreal',
            name='seasonal_validity_period_information',
            field=models.TextField(blank=True, default='', help_text='Seasonal validity period information related to this device.', verbose_name='Seasonal validity period information'),
        ),
        migrations.AlterField(
            model_name='roadmarkingplan',
            name='validity_period_end',
            field=models.DateField(blank=True, help_text='Date after which this sign becomes inactive.', null=True, verbose_name='Validity period end'),
        ),
        migrations.AlterField(
            model_name='roadmarkingplan',
            name='validity_period_start',
            field=models.DateField(blank=True, help_text='Date on which this sign becomes active.', null=True, verbose_name='Validity period start'),
        ),
        migrations.AlterField(
            model_name='roadmarkingreal',
            name='validity_period_end',
            field=models.DateField(blank=True, help_text='Date after which this sign becomes inactive.', null=True, verbose_name='Validity period end'),
        ),
        migrations.AlterField(
            model_name='roadmarkingreal',
            name='validity_period_start',
            field=models.DateField(blank=True, help_text='Date on which this sign becomes active.', null=True, verbose_name='Validity period start'),
        ),
    ]
