# Generated by Django 4.2.20 on 2025-08-29 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_control', '0091_remove_additionalsignplan_seasonal_validity_period_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mounttype',
            name='description_sv',
            field=models.CharField(blank=True, max_length=256, verbose_name='Description (sv)'),
        ),
    ]
