# Generated by Django 4.2.20 on 2025-08-05 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_control', '0091_remove_additionalsignplan_seasonal_validity_period_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalsignplan',
            name='order',
        ),
        migrations.RemoveField(
            model_name='additionalsignreal',
            name='order',
        ),
    ]
