# Generated by Django 4.2.20 on 2025-09-01 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_control', '0092_mounttype_description_sv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalsignplan',
            name='order',
        ),
        migrations.RemoveField(
            model_name='additionalsignreal',
            name='order',
        ),
    ]
