# Generated by Django 4.2.20 on 2025-09-15 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_control', '0093_remove_additionalsignplan_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signpostplan',
            name='double_sided',
            field=models.BooleanField(default=False, help_text='Indicates if this object is double sided', verbose_name='Double sided'),
        ),
        migrations.AddField(
            model_name='signpostreal',
            name='double_sided',
            field=models.BooleanField(default=False, help_text='Indicates if this object is double sided', verbose_name='Double sided'),
        ),
        migrations.AddField(
            model_name='trafficsignplan',
            name='double_sided',
            field=models.BooleanField(default=False, help_text='Indicates if this object is double sided', verbose_name='Double sided'),
        ),
        migrations.AddField(
            model_name='trafficsignreal',
            name='double_sided',
            field=models.BooleanField(default=False, help_text='Indicates if this object is double sided', verbose_name='Double sided'),
        ),
    ]
