# Generated by Django 4.2.22 on 2025-10-01 07:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_control', '0094_signpostplan_double_sided_signpostreal_double_sided_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficControlDeviceTypeIcon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('file', models.FileField(upload_to='icons/traffic_control_device_type/svg/', verbose_name='File')),
            ],
            options={
                'verbose_name': 'Traffic Control Device Type Icon',
                'verbose_name_plural': 'Traffic Control Device Type Icons',
                'db_table': 'traffic_control_device_type_icon',
            },
        ),
        migrations.AddField(
            model_name='trafficcontroldevicetype',
            name='icon_file',
            field=models.ForeignKey(blank=True, help_text='Icon of the actual device', null=True, on_delete=django.db.models.deletion.PROTECT, to='traffic_control.trafficcontroldevicetypeicon'),
        ),
    ]
