# Generated by Django 4.2.22 on 2025-10-01 07:23

from django.db import migrations, models
import traffic_control.models.common


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_control', '0095_trafficcontroldevicetypeicon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafficcontroldevicetypeicon',
            name='file',
            field=models.FileField(storage=traffic_control.models.common.traffic_control_device_type_icon_storage, upload_to='icons/traffic_control_device_type/svg/', verbose_name='File'),
        ),
    ]
