# Generated by Django 4.2.25 on 2025-10-08 06:49

from django.db import migrations, models
import traffic_control.models.common


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_control', '0096_alter_trafficcontroldevicetypeicon_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafficcontroldevicetypeicon',
            name='file',
            field=models.FileField(storage=traffic_control.models.common.traffic_control_device_type_icon_storage, unique=True, upload_to='icons/traffic_control_device_type/svg/', verbose_name='File'),
        ),
    ]
