# Generated by Django 4.2.20 on 2025-10-20 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_control', '0097_alter_trafficcontroldevicetypeicon_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trafficcontroldevicetype',
            name='icon',
        ),
    ]
