# Generated by Django 4.2.25 on 2025-10-30 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_control', '0098_remove_trafficcontroldevicetype_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalsignplanfile',
            name='is_public',
            field=models.BooleanField(default=True, help_text='If unchecked, access is restricted to users/groups with appropriate table or file permissions', verbose_name='Is public'),
        ),
        migrations.AddField(
            model_name='additionalsignrealfile',
            name='is_public',
            field=models.BooleanField(default=True, help_text='If unchecked, access is restricted to users/groups with appropriate table or file permissions', verbose_name='Is public'),
        ),
        migrations.AddField(
            model_name='barrierplanfile',
            name='is_public',
            field=models.BooleanField(default=True, help_text='If unchecked, access is restricted to users/groups with appropriate table or file permissions', verbose_name='Is public'),
        ),
        migrations.AddField(
            model_name='barrierrealfile',
            name='is_public',
            field=models.BooleanField(default=True, help_text='If unchecked, access is restricted to users/groups with appropriate table or file permissions', verbose_name='Is public'),
        ),
        migrations.AddField(
            model_name='mountplanfile',
            name='is_public',
            field=models.BooleanField(default=True, help_text='If unchecked, access is restricted to users/groups with appropriate table or file permissions', verbose_name='Is public'),
        ),
        migrations.AddField(
            model_name='mountrealfile',
            name='is_public',
            field=models.BooleanField(default=True, help_text='If unchecked, access is restricted to users/groups with appropriate table or file permissions', verbose_name='Is public'),
        ),
        migrations.AddField(
            model_name='roadmarkingplanfile',
            name='is_public',
            field=models.BooleanField(default=True, help_text='If unchecked, access is restricted to users/groups with appropriate table or file permissions', verbose_name='Is public'),
        ),
        migrations.AddField(
            model_name='roadmarkingrealfile',
            name='is_public',
            field=models.BooleanField(default=True, help_text='If unchecked, access is restricted to users/groups with appropriate table or file permissions', verbose_name='Is public'),
        ),
        migrations.AddField(
            model_name='signpostplanfile',
            name='is_public',
            field=models.BooleanField(default=True, help_text='If unchecked, access is restricted to users/groups with appropriate table or file permissions', verbose_name='Is public'),
        ),
        migrations.AddField(
            model_name='signpostrealfile',
            name='is_public',
            field=models.BooleanField(default=True, help_text='If unchecked, access is restricted to users/groups with appropriate table or file permissions', verbose_name='Is public'),
        ),
        migrations.AddField(
            model_name='trafficcontroldevicetypeicon',
            name='is_public',
            field=models.BooleanField(default=True, help_text='If unchecked, access is restricted to users/groups with appropriate table or file permissions', verbose_name='Is public'),
        ),
        migrations.AddField(
            model_name='trafficlightplanfile',
            name='is_public',
            field=models.BooleanField(default=True, help_text='If unchecked, access is restricted to users/groups with appropriate table or file permissions', verbose_name='Is public'),
        ),
        migrations.AddField(
            model_name='trafficlightrealfile',
            name='is_public',
            field=models.BooleanField(default=True, help_text='If unchecked, access is restricted to users/groups with appropriate table or file permissions', verbose_name='Is public'),
        ),
        migrations.AddField(
            model_name='trafficsignplanfile',
            name='is_public',
            field=models.BooleanField(default=True, help_text='If unchecked, access is restricted to users/groups with appropriate table or file permissions', verbose_name='Is public'),
        ),
        migrations.AddField(
            model_name='trafficsignrealfile',
            name='is_public',
            field=models.BooleanField(default=True, help_text='If unchecked, access is restricted to users/groups with appropriate table or file permissions', verbose_name='Is public'),
        ),
    ]
