# Generated by Django 4.2.26 on 2025-11-16 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_control', '0099_additionalsignplanfile_is_public_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficsignplan',
            name='peak_fastened',
            field=models.BooleanField(default=False, help_text='Indicates if this object is peak fastened', verbose_name='Peak fastened'),
        ),
        migrations.AddField(
            model_name='trafficsignreal',
            name='peak_fastened',
            field=models.BooleanField(default=False, help_text='Indicates if this object is peak fastened', verbose_name='Peak fastened'),
        ),
    ]
