# Generated by Django 4.2.26 on 2025-11-17 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_control', '0100_trafficsignplan_peak_fastened_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalsignreal',
            name='coverage_area',
        ),
        migrations.RemoveField(
            model_name='trafficsignreal',
            name='coverage_area',
        ),
        migrations.DeleteModel(
            name='CoverageArea',
        ),
        migrations.DeleteModel(
            name='CoverageAreaCategory',
        ),
    ]
