# Generated by Django 4.2.26 on 2025-11-21 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_control', '0101_remove_additionalsignreal_coverage_area_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalsignplan',
            name='responsible_entity',
        ),
        migrations.RemoveField(
            model_name='additionalsignreal',
            name='responsible_entity',
        ),
        migrations.RemoveField(
            model_name='barrierplan',
            name='responsible_entity',
        ),
        migrations.RemoveField(
            model_name='barrierreal',
            name='responsible_entity',
        ),
        migrations.RemoveField(
            model_name='mountplan',
            name='responsible_entity',
        ),
        migrations.RemoveField(
            model_name='mountreal',
            name='responsible_entity',
        ),
        migrations.RemoveField(
            model_name='roadmarkingplan',
            name='responsible_entity',
        ),
        migrations.RemoveField(
            model_name='roadmarkingreal',
            name='responsible_entity',
        ),
        migrations.RemoveField(
            model_name='signpostplan',
            name='responsible_entity',
        ),
        migrations.RemoveField(
            model_name='signpostreal',
            name='responsible_entity',
        ),
        migrations.RemoveField(
            model_name='trafficlightplan',
            name='responsible_entity',
        ),
        migrations.RemoveField(
            model_name='trafficlightreal',
            name='responsible_entity',
        ),
        migrations.RemoveField(
            model_name='trafficsignplan',
            name='responsible_entity',
        ),
        migrations.RemoveField(
            model_name='trafficsignreal',
            name='responsible_entity',
        ),
    ]
