# Generated by Django 4.2.26 on 2025-11-27 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_control', '0102_remove_additionalsignplan_responsible_entity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mountplan',
            name='validity_period_end',
        ),
        migrations.RemoveField(
            model_name='mountplan',
            name='validity_period_start',
        ),
        migrations.RemoveField(
            model_name='mountreal',
            name='validity_period_end',
        ),
        migrations.RemoveField(
            model_name='mountreal',
            name='validity_period_start',
        ),
    ]
