# Generated by Django 4.2.26 on 2025-12-15 11:08

from django.db import migrations


def set_dummy_device_type_for_null_values(apps, schema_editor):
    """
    Create or get the DummyDT device type and set it for all devices with null device_type.
    This must be done before making the field non-nullable.
    """
    TrafficControlDeviceType = apps.get_model("traffic_control", "TrafficControlDeviceType")

    # Get or create the DummyDT device type
    dummy_dt, created = TrafficControlDeviceType.objects.get_or_create(
        code="DummyDT",
        defaults={
            "description": "Placeholder for devices that have None set to device_type",
            "target_model": None,
        },
    )

    # Models with device_type field in traffic_control app
    models_to_update = [
        "AdditionalSignPlan",
        "AdditionalSignReal",
        "BarrierPlan",
        "BarrierReal",
        "RoadMarkingPlan",
        "RoadMarkingReal",
        "SignpostPlan",
        "SignpostReal",
        "TrafficLightPlan",
        "TrafficLightReal",
        "TrafficSignPlan",
        "TrafficSignReal",
    ]

    total_updated = 0
    for model_name in models_to_update:
        try:
            Model = apps.get_model("traffic_control", model_name)
            updated = Model.objects.filter(device_type__isnull=True).update(device_type=dummy_dt)
            if updated > 0:
                print(f"  Updated {updated} {model_name} records with DummyDT device type")
                total_updated += updated
        except LookupError:
            # Model doesn't exist, skip it
            pass

    if total_updated > 0:
        print(f"Total: Updated {total_updated} device records with DummyDT device type")
    else:
        print("No devices with device_type=None found")


def reverse_dummy_device_type(apps, schema_editor):
    """
    Reverse operation: set device_type back to null for all devices using DummyDT.
    Note: This will fail if the field is already non-nullable.
    """
    TrafficControlDeviceType = apps.get_model("traffic_control", "TrafficControlDeviceType")

    try:
        dummy_dt = TrafficControlDeviceType.objects.get(code="DummyDT")
    except TrafficControlDeviceType.DoesNotExist:
        print("DummyDT device type not found, nothing to reverse")
        return

    models_to_update = [
        "AdditionalSignPlan",
        "AdditionalSignReal",
        "BarrierPlan",
        "BarrierReal",
        "RoadMarkingPlan",
        "RoadMarkingReal",
        "SignpostPlan",
        "SignpostReal",
        "TrafficLightPlan",
        "TrafficLightReal",
        "TrafficSignPlan",
        "TrafficSignReal",
    ]

    total_updated = 0
    for model_name in models_to_update:
        try:
            Model = apps.get_model("traffic_control", model_name)
            updated = Model.objects.filter(device_type=dummy_dt).update(device_type=None)
            if updated > 0:
                print(f"  Reversed {updated} {model_name} records back to null device_type")
                total_updated += updated
        except LookupError:
            pass

    if total_updated > 0:
        print(f"Total: Reversed {total_updated} device records back to null device_type")


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_control', '0104_alter_additionalsignplan_direction_and_more'),
    ]

    operations = [
        # First, set dummy device type for all null values
        migrations.RunPython(
            set_dummy_device_type_for_null_values,
            reverse_dummy_device_type,
        ),
    ]

