# Generated by Django 4.2.26 on 2025-12-15 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_control', '0105_set_device_type_non_nullable'),
    ]

    operations = [
        # Make device_type non-nullable for all models
        # Note: Migration 0105 already set DummyDT for all null values
        migrations.AlterField(
            model_name='additionalsignplan',
            name='device_type',
            field=models.ForeignKey(
                help_text='Type of the device from Helsinki Design Manual.',
                on_delete=django.db.models.deletion.PROTECT,
                to='traffic_control.trafficcontroldevicetype',
                verbose_name='Device type'
            ),
        ),
        migrations.AlterField(
            model_name='additionalsignreal',
            name='device_type',
            field=models.ForeignKey(
                help_text='Type of the device from Helsinki Design Manual.',
                on_delete=django.db.models.deletion.PROTECT,
                to='traffic_control.trafficcontroldevicetype',
                verbose_name='Device type'
            ),
        ),
        migrations.AlterField(
            model_name='barrierplan',
            name='device_type',
            field=models.ForeignKey(
                help_text='Type of the device from Helsinki Design Manual.',
                limit_choices_to=models.Q(models.Q(('target_model', None)), models.Q(('target_model', 'barrier')), _connector='OR'),
                on_delete=django.db.models.deletion.PROTECT,
                to='traffic_control.trafficcontroldevicetype',
                verbose_name='Device type'
            ),
        ),
        migrations.AlterField(
            model_name='barrierreal',
            name='device_type',
            field=models.ForeignKey(
                help_text='Type of the device from Helsinki Design Manual.',
                limit_choices_to=models.Q(models.Q(('target_model', None)), models.Q(('target_model', 'barrier')), _connector='OR'),
                on_delete=django.db.models.deletion.PROTECT,
                to='traffic_control.trafficcontroldevicetype',
                verbose_name='Device type'
            ),
        ),
        migrations.AlterField(
            model_name='roadmarkingplan',
            name='device_type',
            field=models.ForeignKey(
                help_text='Type of the device from Helsinki Design Manual.',
                limit_choices_to=models.Q(models.Q(('target_model', None)), models.Q(('target_model', 'road_marking')), _connector='OR'),
                on_delete=django.db.models.deletion.PROTECT,
                to='traffic_control.trafficcontroldevicetype',
                verbose_name='Device type'
            ),
        ),
        migrations.AlterField(
            model_name='roadmarkingreal',
            name='device_type',
            field=models.ForeignKey(
                help_text='Type of the device from Helsinki Design Manual.',
                limit_choices_to=models.Q(models.Q(('target_model', None)), models.Q(('target_model', 'road_marking')), _connector='OR'),
                on_delete=django.db.models.deletion.PROTECT,
                to='traffic_control.trafficcontroldevicetype',
                verbose_name='Device type'
            ),
        ),
        migrations.AlterField(
            model_name='signpostplan',
            name='device_type',
            field=models.ForeignKey(
                help_text='Type of the device from Helsinki Design Manual.',
                limit_choices_to=models.Q(models.Q(('target_model', None)), models.Q(('target_model', 'signpost')), _connector='OR'),
                on_delete=django.db.models.deletion.PROTECT,
                to='traffic_control.trafficcontroldevicetype',
                verbose_name='Device type'
            ),
        ),
        migrations.AlterField(
            model_name='signpostreal',
            name='device_type',
            field=models.ForeignKey(
                help_text='Type of the device from Helsinki Design Manual.',
                limit_choices_to=models.Q(models.Q(('target_model', None)), models.Q(('target_model', 'signpost')), _connector='OR'),
                on_delete=django.db.models.deletion.PROTECT,
                to='traffic_control.trafficcontroldevicetype',
                verbose_name='Device type'
            ),
        ),
        migrations.AlterField(
            model_name='trafficlightplan',
            name='device_type',
            field=models.ForeignKey(
                help_text='Type of the device from Helsinki Design Manual.',
                limit_choices_to=models.Q(models.Q(('target_model', None)), models.Q(('target_model', 'traffic_light')), _connector='OR'),
                on_delete=django.db.models.deletion.PROTECT,
                to='traffic_control.trafficcontroldevicetype',
                verbose_name='Device type'
            ),
        ),
        migrations.AlterField(
            model_name='trafficlightreal',
            name='device_type',
            field=models.ForeignKey(
                help_text='Type of the device from Helsinki Design Manual.',
                limit_choices_to=models.Q(models.Q(('target_model', None)), models.Q(('target_model', 'traffic_light')), _connector='OR'),
                on_delete=django.db.models.deletion.PROTECT,
                to='traffic_control.trafficcontroldevicetype',
                verbose_name='Device type'
            ),
        ),
        migrations.AlterField(
            model_name='trafficsignplan',
            name='device_type',
            field=models.ForeignKey(
                help_text='Type of the device from Helsinki Design Manual.',
                limit_choices_to=models.Q(models.Q(('target_model', None)), models.Q(('target_model', 'traffic_sign')), _connector='OR'),
                on_delete=django.db.models.deletion.PROTECT,
                to='traffic_control.trafficcontroldevicetype',
                verbose_name='Device type'
            ),
        ),
        migrations.AlterField(
            model_name='trafficsignreal',
            name='device_type',
            field=models.ForeignKey(
                help_text='Type of the device from Helsinki Design Manual.',
                limit_choices_to=models.Q(models.Q(('target_model', None)), models.Q(('target_model', 'traffic_sign')), _connector='OR'),
                on_delete=django.db.models.deletion.PROTECT,
                to='traffic_control.trafficcontroldevicetype',
                verbose_name='Device type'
            ),
        ),
    ]

