# Generated by Django 4.2.26 on 2025-12-18 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_control', '0106_make_device_type_non_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalsignplan',
            name='device_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('target_model', None), ('target_model', 'additional_sign'), _connector='OR')), on_delete=django.db.models.deletion.PROTECT, to='traffic_control.trafficcontroldevicetype', verbose_name='Device type'),
        ),
        migrations.AlterField(
            model_name='additionalsignreal',
            name='device_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('target_model', None), ('target_model', 'additional_sign'), _connector='OR')), on_delete=django.db.models.deletion.PROTECT, to='traffic_control.trafficcontroldevicetype', verbose_name='Device type'),
        ),
        migrations.AlterField(
            model_name='barrierplan',
            name='device_type',
            field=models.ForeignKey(help_text='Type of the device from Helsinki Design Manual.', limit_choices_to=models.Q(models.Q(('target_model', None), ('target_model', 'barrier'), _connector='OR')), on_delete=django.db.models.deletion.PROTECT, to='traffic_control.trafficcontroldevicetype', verbose_name='Device type'),
        ),
        migrations.AlterField(
            model_name='barrierreal',
            name='device_type',
            field=models.ForeignKey(help_text='Type of the device from Helsinki Design Manual.', limit_choices_to=models.Q(models.Q(('target_model', None), ('target_model', 'barrier'), _connector='OR')), on_delete=django.db.models.deletion.PROTECT, to='traffic_control.trafficcontroldevicetype', verbose_name='Device type'),
        ),
        migrations.AlterField(
            model_name='roadmarkingplan',
            name='device_type',
            field=models.ForeignKey(help_text='Type of the device from Helsinki Design Manual.', limit_choices_to=models.Q(models.Q(('target_model', None), ('target_model', 'road_marking'), _connector='OR')), on_delete=django.db.models.deletion.PROTECT, to='traffic_control.trafficcontroldevicetype', verbose_name='Device type'),
        ),
        migrations.AlterField(
            model_name='roadmarkingreal',
            name='device_type',
            field=models.ForeignKey(help_text='Type of the device from Helsinki Design Manual.', limit_choices_to=models.Q(models.Q(('target_model', None), ('target_model', 'road_marking'), _connector='OR')), on_delete=django.db.models.deletion.PROTECT, to='traffic_control.trafficcontroldevicetype', verbose_name='Device type'),
        ),
        migrations.AlterField(
            model_name='signpostplan',
            name='device_type',
            field=models.ForeignKey(help_text='Type of the device from Helsinki Design Manual.', limit_choices_to=models.Q(models.Q(('target_model', None), ('target_model', 'signpost'), _connector='OR')), on_delete=django.db.models.deletion.PROTECT, to='traffic_control.trafficcontroldevicetype', verbose_name='Device type'),
        ),
        migrations.AlterField(
            model_name='signpostreal',
            name='device_type',
            field=models.ForeignKey(help_text='Type of the device from Helsinki Design Manual.', limit_choices_to=models.Q(models.Q(('target_model', None), ('target_model', 'signpost'), _connector='OR')), on_delete=django.db.models.deletion.PROTECT, to='traffic_control.trafficcontroldevicetype', verbose_name='Device type'),
        ),
        migrations.AlterField(
            model_name='trafficlightplan',
            name='device_type',
            field=models.ForeignKey(help_text='Type of the device from Helsinki Design Manual.', limit_choices_to=models.Q(models.Q(('target_model', None), ('target_model', 'traffic_light'), _connector='OR')), on_delete=django.db.models.deletion.PROTECT, to='traffic_control.trafficcontroldevicetype', verbose_name='Device type'),
        ),
        migrations.AlterField(
            model_name='trafficlightreal',
            name='device_type',
            field=models.ForeignKey(help_text='Type of the device from Helsinki Design Manual.', limit_choices_to=models.Q(models.Q(('target_model', None), ('target_model', 'traffic_light'), _connector='OR')), on_delete=django.db.models.deletion.PROTECT, to='traffic_control.trafficcontroldevicetype', verbose_name='Device type'),
        ),
        migrations.AlterField(
            model_name='trafficsignplan',
            name='device_type',
            field=models.ForeignKey(help_text='Type of the device from Helsinki Design Manual.', limit_choices_to=models.Q(models.Q(('target_model', None), ('target_model', 'traffic_sign'), _connector='OR')), on_delete=django.db.models.deletion.PROTECT, to='traffic_control.trafficcontroldevicetype', verbose_name='Device type'),
        ),
        migrations.AlterField(
            model_name='trafficsignreal',
            name='device_type',
            field=models.ForeignKey(help_text='Type of the device from Helsinki Design Manual.', limit_choices_to=models.Q(models.Q(('target_model', None), ('target_model', 'traffic_sign'), _connector='OR')), on_delete=django.db.models.deletion.PROTECT, to='traffic_control.trafficcontroldevicetype', verbose_name='Device type'),
        ),
    ]
