# Generated by Django 5.2.8 on 2026-01-20 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_control', '0107_alter_additionalsignplan_device_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafficcontroldevicetype',
            name='icon_file',
            field=models.ForeignKey(blank=True, help_text='Icon of the actual device', null=True, on_delete=django.db.models.deletion.PROTECT, to='traffic_control.trafficcontroldevicetypeicon', verbose_name='Icon file'),
        ),
    ]
