# Generated by Django 5.2.8 on 2026-01-26 10:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_control', '0108_alter_trafficcontroldevicetype_icon_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanGeometryImportLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(verbose_name='Start time')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='End time')),
                ('file_path', models.CharField(max_length=500, verbose_name='File path')),
                ('output_dir', models.CharField(max_length=500, verbose_name='Output directory')),
                ('dry_run', models.BooleanField(default=False, verbose_name='Dry run')),
                ('results', models.JSONField(blank=True, help_text='List of import results for each CSV row', null=True, verbose_name='Results')),
            ],
            options={
                'verbose_name': 'Plan Geometry Import Log',
                'verbose_name_plural': 'Plan Geometry Import Logs',
                'ordering': ['-start_time'],
            },
        ),
    ]
