# Generated by Django 5.2.12 on 2026-04-30 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_control', '0111_signpostreal_attachment_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalsignplan',
            name='signpost_plan',
            field=models.ForeignKey(blank=True, help_text='The signpost plan to which this additional sign is associated (set after signpost migration).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='additional_signs', to='traffic_control.signpostplan', verbose_name='Parent Signpost Plan'),
        ),
        migrations.AddField(
            model_name='additionalsignreal',
            name='signpost_real',
            field=models.ForeignKey(blank=True, help_text='The signpost real to which this additional sign is associated (set after signpost migration).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='additional_signs', to='traffic_control.signpostreal', verbose_name='Parent Signpost Real'),
        ),
    ]
