# Generated by Django 5.2.12 on 2026-05-28 12:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_control', '0112_add_signpost_parent_to_additional_sign'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreetScanImportRun',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the import run was started.', verbose_name='Started at')),
                ('completed_at', models.DateTimeField(blank=True, help_text='Timestamp when the import run finished.', null=True, verbose_name='Completed at')),
                ('dry_run', models.BooleanField(default=False, help_text='True if the run was executed with --dry-run (no DB writes performed).', verbose_name='Dry run')),
                ('mount_file', models.CharField(help_text='Path or name of the mount CSV file used for this run.', max_length=512, verbose_name='Mount file')),
                ('sign_file', models.CharField(help_text='Path or name of the sign CSV file used for this run.', max_length=512, verbose_name='Sign file')),
                ('mounts_created', models.IntegerField(default=0, verbose_name='Mounts created')),
                ('mounts_updated', models.IntegerField(default=0, verbose_name='Mounts updated')),
                ('signs_created', models.IntegerField(default=0, verbose_name='Signs created')),
                ('signs_updated', models.IntegerField(default=0, verbose_name='Signs updated')),
                ('signs_deactivated', models.IntegerField(default=0, help_text='TrafficSignReal records whose lifecycle was set to INACTIVE.', verbose_name='Signs deactivated')),
                ('signposts_created', models.IntegerField(default=0, verbose_name='Signposts created')),
                ('signposts_updated', models.IntegerField(default=0, verbose_name='Signposts updated')),
                ('signposts_deactivated', models.IntegerField(default=0, verbose_name='Signposts deactivated')),
                ('additional_signs_created', models.IntegerField(default=0, verbose_name='Additional signs created')),
                ('additional_signs_updated', models.IntegerField(default=0, verbose_name='Additional signs updated')),
                ('additional_signs_deactivated', models.IntegerField(default=0, verbose_name='Additional signs deactivated')),
                ('skipped_count', models.IntegerField(default=0, help_text='Total rows skipped due to invalid geometry, unreadable text, missing device type code, etc.', verbose_name='Skipped count')),
                ('warning_count', models.IntegerField(default=0, help_text='Total warning-level events: imported without a mount, without a parent, traffic sign with ignored parent value, etc.', verbose_name='Warning count')),
                ('error_count', models.IntegerField(default=0, help_text='Total error-level events (unexpected exceptions during the run).', verbose_name='Error count')),
                ('phase_durations', models.JSONField(default=dict, help_text="Nested dict of seconds spent in each phase: {object_type: {phase: duration_s}}. Also contains a 'preprocessing' key for CSV loading and DB map building time. Populated progressively as phases complete.", verbose_name='Phase durations')),
                ('details', models.JSONField(default=list, help_text="Full list of per-row skip, warning and error entries. Each entry has at minimum: level ('skip'/'warning'/'error'), source_id, reason.", verbose_name='Details')),
                ('processed_mount_source_ids', models.JSONField(default=list, help_text='List of MountReal source_ids successfully upserted in this run.', verbose_name='Processed mount source IDs')),
                ('processed_sign_source_ids', models.JSONField(default=list, help_text='List of TrafficSignReal source_ids successfully upserted in this run.', verbose_name='Processed sign source IDs')),
                ('processed_signpost_source_ids', models.JSONField(default=list, help_text='List of SignpostReal source_ids successfully upserted in this run.', verbose_name='Processed signpost source IDs')),
                ('processed_additional_sign_source_ids', models.JSONField(default=list, help_text='List of AdditionalSignReal source_ids successfully upserted in this run.', verbose_name='Processed additional sign source IDs')),
            ],
            options={
                'verbose_name': 'StreetScan import run',
                'verbose_name_plural': 'StreetScan import runs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='StreetScanImportRevertFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_public', models.BooleanField(default=True, help_text='If unchecked, access is restricted to users/groups with appropriate table or file permissions', verbose_name='Is public')),
                ('file', models.FileField(help_text='JSONL file containing pre-update snapshots and created-object IDs for this run.', upload_to='streetscan_import/revert/', verbose_name='File')),
                ('import_run', models.ForeignKey(help_text='The import run this revert file belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='revert_files', to='traffic_control.streetscanimportrun', verbose_name='Import run')),
            ],
            options={
                'verbose_name': 'StreetScan import revert file',
                'verbose_name_plural': 'StreetScan import revert files',
                'db_table': 'streetscan_import_revert_file',
            },
        ),
    ]
