# Generated by Django 5.2.12 on 2026-06-06 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_control', '0113_streetscanimportrun_streetscanimportrevertfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streetscanimportrevertfile',
            name='file',
            field=models.FileField(help_text='JSONL file containing pre-update snapshots and created-object IDs for this run.', upload_to='management_commands/streetscan_revert/', verbose_name='File'),
        ),
    ]
