# Generated by Django 5.2.12 on 2026-07-01 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_control', '0114_alter_streetscanimportrevertfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='streetscanimportrun',
            name='orphan_mount_source_ids',
            field=models.JSONField(default=list, help_text='List of source_ids for MountReal records hard-deleted as orphans in this run.', verbose_name='Orphan mount source IDs'),
        ),
        migrations.AddField(
            model_name='streetscanimportrun',
            name='orphans_deleted',
            field=models.IntegerField(default=0, help_text='Number of orphan MountReal records hard-deleted after the import phases.', verbose_name='Orphans deleted'),
        ),
    ]
