# Generated by Django 5.2.16 on 2026-08-19 12:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_control', '0115_streetscanimportrun_orphan_mount_source_ids_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkAdditionalSignParentsRunInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('dry_run', models.BooleanField(default=False)),
                ('total_candidates', models.IntegerField(default=0, help_text='Total AdditionalSignReal instances that were candidates for linking')),
                ('successfully_linked', models.IntegerField(default=0, help_text='Number of AdditionalSignReal instances successfully linked')),
                ('skipped_no_match', models.IntegerField(default=0, help_text='Number skipped due to no matching active TrafficSignReal or SignpostReal')),
                ('skipped_no_active_above', models.IntegerField(default=0, help_text='Number skipped because no active candidates were positioned above the additional sign')),
                ('linked_records', models.JSONField(blank=True, help_text='List of dicts with keys: additional_sign_real_id, traffic_sign_real_id, signpost_real_id, mount_real_id', null=True)),
                ('skipped_records', models.JSONField(blank=True, help_text='List of dicts with keys: additional_sign_real_id, mount_real_id, reason', null=True)),
            ],
            options={
                'verbose_name': 'Link Additional Sign Parents Run Info',
                'verbose_name_plural': 'Link Additional Sign Parents Run Infos',
                'db_table': 'link_additional_sign_parents_run_info',
                'ordering': ['-started_at'],
            },
        ),
    ]
