# Generated by Django 5.2.16 on 2026-08-24 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_control', '0116_linkadditionalsignparentsruninfo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='operationalarea',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='portaltype',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='operationalarea',
            constraint=models.UniqueConstraint(fields=('source_name', 'source_id'), name='traffic_control_operationalarea_unique_source_name_id'),
        ),
        migrations.AddConstraint(
            model_name='portaltype',
            constraint=models.UniqueConstraint(fields=('structure', 'build_type', 'model'), name='traffic_control_portaltype_unique_structure_build_type_model'),
        ),
    ]
