# Generated by Django 5.2.16 on 2026-08-27 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_control', '0117_alter_operationalarea_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevertStreetScanImportRun',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the import run was started', verbose_name='Started at')),
                ('completed_at', models.DateTimeField(blank=True, help_text='Timestamp when the import run finished.', null=True, verbose_name='Completed at')),
                ('dry_run', models.BooleanField(default=False, help_text='True if the run was executed with --dry-run (no DB writes performed).', verbose_name='Dry run')),
                ('file_path', models.CharField(help_text='Path or name of the JSON file containing the operations to be reverted.', max_length=512, verbose_name='Revert file')),
                ('ids_param', models.JSONField(help_text='--ids parameter of the run.')),
                ('models_param', models.JSONField(help_text='--models parameter of the run.')),
                ('execution_log', models.TextField(help_text='Detailed log information of the command run.')),
            ],
        ),
    ]
