# Generated by Django 5.2.16 on 2026-09-15 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_control', '0118_revertstreetscanimportrun'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchOrphanFilesRunInfo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the import run was started', verbose_name='Started at')),
                ('completed_at', models.DateTimeField(blank=True, help_text='Timestamp when the import run finished.', null=True, verbose_name='Completed at')),
                ('execution_log', models.TextField(help_text='Detailed log information of the command run.')),
            ],
        ),
    ]
