# Generated by Django 5.2.16 on 2026-09-17 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_control', '0119_searchorphanfilesruninfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revertstreetscanimportrun',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the import run was started.', verbose_name='Started at'),
        ),
        migrations.AlterField(
            model_name='searchorphanfilesruninfo',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the import run was started.', verbose_name='Started at'),
        ),
    ]
