# Generated by Django 5.2.16 on 2026-09-18 07:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_control', '0120_alter_revertstreetscanimportrun_started_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficControlDeviceTypeTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(help_text='Name of the tag.', max_length=64, unique=True, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=254, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Traffic Control Device Type Tag',
                'verbose_name_plural': 'Traffic Control Device Type Tags',
                'db_table': 'traffic_control_device_type_tag',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='trafficcontroldevicetype',
            name='tags',
            field=models.ManyToManyField(blank=True, db_table='traffic_control_device_type_tags', help_text='Tags describing this device type.', related_name='device_types', to='traffic_control.trafficcontroldevicetypetag', verbose_name='Tags'),
        ),
    ]
