# Generated by Django 5.2.16 on 2026-09-24 09:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_control', '0121_trafficcontroldevicetypetag_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficSignValueCheckRunInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(help_text='Timestamp when the run was started.', verbose_name='Start time')),
                ('end_time', models.DateTimeField(help_text='Timestamp when the run finished.', verbose_name='End time')),
                ('checked_codes', models.JSONField(help_text='Device type codes that were included in the run.', null=True, verbose_name='Checked codes')),
                ('problems', models.JSONField(help_text='Value problems that were found, including what was done about each of them.', null=True, verbose_name='Problems')),
                ('checked_count', models.PositiveIntegerField(default=0, help_text='Number of traffic sign reals that were checked.', verbose_name='Checked count')),
                ('problem_count', models.PositiveIntegerField(default=0, help_text='Number of traffic sign reals that had a value problem.', verbose_name='Problem count')),
                ('fixed_count', models.PositiveIntegerField(default=0, help_text='Number of problems that were corrected, or that would be corrected on a dry run.', verbose_name='Fixed count')),
                ('skipped_fix_count', models.PositiveIntegerField(default=0, help_text='Number of problems that could not be corrected.', verbose_name='Skipped fix count')),
                ('database_update', models.BooleanField(default=False, help_text='Whether the run actually updated traffic sign reals.', verbose_name='Database updated')),
            ],
            options={
                'verbose_name': 'Traffic sign value check run info',
                'verbose_name_plural': 'Traffic sign value check run infos',
                'ordering': ('-start_time',),
            },
        ),
    ]
