# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: City Infrastructure Platform

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      DEBUG: 1
      OIDC_AUTHENTICATION_ENABLED: 0
      # Database for tests
      DATABASE_URL: postgis://postgres:postgres@localhost/city-infrastructure-platform

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install required Ubuntu packages
      run: |
        sudo apt-get install gdal-bin
    - name: Install PyPI dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt -r requirements-dev.txt
    - name: Run Python side code neatness tests
      run: |
        flake8
        black --check .
        isort . -c
    - name: Test with pytest
      run: |
        pytest -ra -vvv --cov=.

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
