name: City Infrastructure Platform tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    # NOTE (2026-05-20 thiago)
    # Bookworm isn't available as a standard GitHub-provided runner
    # https://docs.github.com/en/actions/reference/runners/github-hosted-runners#standard-github-hosted-runners-for-public-repositories
    runs-on: ubuntu-latest

    env:
      DEBUG: 1
      # Disable OIDC to allow for minimal test configuration
      OIDC_AUTHENTICATION_ENABLED: 0
      # Database for tests
      DATABASE_URL: postgis://postgres:postgres@localhost/city-infrastructure-platform

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # release 6.0.2 (2026-01-09)
        with:
          persist-credentials: false
          # https://github.com/SonarSource/sonarqube-scan-action/tree/7006c4492b2e0ee0f816d36501671557c97f5995#3-quick-start-workflow-example-for-sonarqube-cloud
          # Disabling shallow clones is recommended for improving the relevancy of reporting
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # release 6.2.0 (2026-01-22)
        with:
          python-version: "3.11"

      - name: Set up NodeJS 24
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # release 6.4.0 (2026-04-20)
        with:
          node-version: "24"
          package-manager-cache: false

      - name: Install required Ubuntu packages
        run: |
          sudo apt-get update
          sudo apt-get install gdal-bin

      # https://github.com/astral-sh/setup-uv?tab=readme-ov-file#usage
      - name: Install uv
        uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57 # release 8.0.0 (2026-03-26)
        with:
          enable-cache: true
          version: "0.11.14" # 2026-05-12
          # checksum for Linux x64: https://github.com/astral-sh/uv/releases/tag/0.11.14
          checksum: "f3b623eb0e6141a7053d571d59a0bdc341e0f238ea8f5f0b4815ddbec9a2a296"

      - name: Install test dependencies
        run: uv sync --frozen

      - name: Add virtual environment to PATH
        run: echo "$GITHUB_WORKSPACE/.venv/bin" >> $GITHUB_PATH

      - name: Run Python side code neatness tests
        run: |
          ruff check --output-format=github .
          ruff format --check --diff .
          djlint .
          djlint --check .

      - name: Run pytest code functionality tests
        run: |
          pytest -ra -vvv --cov=. --cov-report=xml --junitxml=test-results.xml

      - name: Run openapi schema validations
        run: |
          ./scripts/check-open-api-schema.sh

      - name: Install NodeJS dependencies
        run: |
          corepack enable
          YARN_ENABLE_SCRIPTS=false yarn --cwd map-view install --immutable --immutable-cache --check-cache

      - name: Run NodeJS code neatness tests
        run: |
          yarn --cwd map-view prettier
          yarn --cwd map-view lint
          yarn --cwd map-view validate-ts

      - name: Run NodeJS build
        run: |
          yarn --cwd map-view build

      - name: Run NodeJS code functionality tests
        run: |
          yarn --cwd map-view test:ci

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@59db25f34e16620e48ab4bb9e4a5dce155cb5432 # release 8.0.0 (2026-04-29)
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=City-of-Helsinki_city-infrastructure-platform
            -Dsonar.organization=city-of-helsinki
            -Dsonar.python.version=3.8

    # Majority of the tests require database
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgis/postgis:17-master
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
          PGUSER: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
